// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  clearAllProviderGroups: typeof import('./actions/clearAllProviderGroups')['default']
  clearProviderGroups: typeof import('./actions/clearProviderGroups')['default']
  getProviderGroupsData: typeof import('./actions/getProviderGroupsData')['default']
  loadAllGroups: typeof import('./actions/loadAllGroups')['default']
  loadGroupsForProvider: typeof import('./actions/loadGroupsForProvider')['default']
}
