// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  clearError: typeof import('./actions/clearError')['default']
  continueRun: typeof import('./actions/continueRun')['default']
  continueSeries: typeof import('./actions/continueSeries')['default']
  createTask: typeof import('./actions/createTask')['default']
  deleteTask: typeof import('./actions/deleteTask')['default']
  loadRuns: typeof import('./actions/loadRuns')['default']
  loadTasks: typeof import('./actions/loadTasks')['default']
  runNow: typeof import('./actions/runNow')['default']
  setEnabled: typeof import('./actions/setEnabled')['default']
  testFire: typeof import('./actions/testFire')['default']
  updateTask: typeof import('./actions/updateTask')['default']
}
