// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  assignUserToUserGroup: typeof import('./actions/assignUserToUserGroup')['default']
  clearError: typeof import('./actions/clearError')['default']
  createUserGroup: typeof import('./actions/createUserGroup')['default']
  deleteUserGroup: typeof import('./actions/deleteUserGroup')['default']
  loadUserGroupMembers: typeof import('./actions/loadUserGroupMembers')['default']
  loadUserGroups: typeof import('./actions/loadUserGroups')['default']
  removeUserFromUserGroup: typeof import('./actions/removeUserFromUserGroup')['default']
  updateUserGroup: typeof import('./actions/updateUserGroup')['default']
}
