// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  clearError: typeof import('./actions/clearError')['default']
  loadInstance: typeof import('./actions/loadInstance')['default']
  restartInstance: typeof import('./actions/restartInstance')['default']
  stopInstance: typeof import('./actions/stopInstance')['default']
}
