// Request/response types for the project↔mcp routes.
// Wire shape preserved from the OLD `UpdateProjectMcpSettingsRequest`
// (previously in `project/types.rs`) so frontend `ApiClient.Project.{get,update}McpSettings`
// keeps working unchanged. Sub-types (AutoApprovedServer, DisabledServer,
// ApprovalMode) are reused from mcp/chat_extension/approval/models.rs +
// chat_extension/defaults/models.rs — they were already the typed
// canonical shapes, just not used by project before.

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::modules::mcp::chat_extension::approval::models::{
    ApprovalMode, AutoApprovedServer, DisabledServer,
};
use crate::modules::mcp::chat_extension::defaults::models::LoopSettings;

/// PUT body + GET response for `/api/projects/{id}/mcp-settings`.
///
/// Field shapes match the legacy `UpdateProjectMcpSettingsRequest` so
/// the OpenAPI schema (and therefore the autogenerated TS client) is
/// wire-compatible. The naming is now consistent with mcp's other
/// settings types (typed enum/structs instead of raw strings/Value).
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct ProjectMcpSettingsRequest {
    pub approval_mode: ApprovalMode,
    #[serde(default)]
    pub auto_approved_tools: Vec<AutoApprovedServer>,
    #[serde(default)]
    pub disabled_servers: Vec<DisabledServer>,
    /// Optional — None preserves the existing row's loop_settings.
    /// `LoopSettings` is fully typed (matches chat_extension's
    /// settings shape).
    #[serde(default)]
    pub loop_settings: Option<LoopSettings>,
}
