// AUTO-GENERATED by scripts/gen-gallery-coverage.mjs — DO NOT EDIT.
// Run `npm run gen:gallery-coverage` to refresh. 19 gallery surfaces
// (every page/component .tsx under src/modules + src/components/ui). The
// hand-maintained coverage.ts must map EVERY one of these (entry or allow-list
// reason) — a missing key is a compile error (the coverage gate).

export const GALLERY_SURFACES = [
  "modules/auth/AuthGuard",
  "modules/hardware/HardwareMonitorButton",
  "modules/host-mount/conversation-extension/components/ConversationMountsControl",
  "modules/host-mount/pages/HostMountPolicyPage",
  "modules/host-mount/project-extension/components/ProjectMountsPanel",
  "modules/host-mount/project-extension/extension",
  "modules/layouts/app-layout/components/Drawer",
  "modules/layouts/app-layout/components/HeaderBarContainer",
  "modules/layouts/app-layout/components/LeftSidebar",
  "modules/layouts/app-layout/components/SidebarHeaderSpacer",
  "modules/layouts/app-layout/components/SidebarToggleButton",
  "modules/llm-provider/components/ProviderGroupAssignmentCard",
  "modules/memory/pages/MemoryCombinedPage",
  "modules/remote-access/pages/RemoteAccessPage",
  "modules/settings/SettingsPage",
  "modules/tunnel-auth/MagicLinkPage",
  "modules/tunnel-auth/PhoneAuthPage",
  "modules/updater/components/UpdateBanner",
  "modules/updater/pages/AboutPage",
] as const

/** Every visual surface (page/component) the gallery must account for. */
export type GallerySurface = (typeof GALLERY_SURFACES)[number]
