// AUTO-GENERATED by scripts/gen-state-matrix.mjs — DO NOT EDIT.
// Run `npm run gen:state-matrix` to refresh. This is PART 1 of the exhaustive-
// state mechanism: the mechanically-extracted required-state matrix (conditional
// renders + overlay triggers + panel/slot registrations) that the reconciliation
// gate (scripts/reconcile-state-matrix.mjs) checks the gallery entries against.
//
// 15 surfaces carry renderable-state signals; 91 signals total.

/** A signal is one mechanically-detected render fork (a state the surface can be in). */
export interface StateSignal {
  kind: 'loading' | 'error' | 'empty' | 'branch' | 'overlay' | 'panel'
  /** The governing condition text (or the overlay tag / registration). */
  condition: string
  line: number
}

export interface SurfaceStateMatrix {
  surface: string
  /** Gallery states this surface's signals demand (delayed/error/empty/open/panel-open). */
  requiredStates: string[]
  signals: StateSignal[]
}

/** Every panel renderer registered via `registerPanelRenderer('type', …)`. */
export interface PanelRegistration {
  type: string
  surface: string
  line: number
}

/** Every module-system slot registration (sidebarContent, settings*Pages, …). */
export interface SlotRegistration {
  slot: string
  surface: string
  line: number
}

export const STATE_MATRIX: Record<string, SurfaceStateMatrix> = {
  "modules/auth/AuthGuard": {
    surface: "modules/auth/AuthGuard",
    requiredStates: [],
    signals: [
      { kind: "branch", condition: "!isAuthenticated", line: 61 },
      { kind: "branch", condition: "!isTauriView", line: 65 },
    ],
  },
  "modules/hardware/HardwareMonitorButton": {
    surface: "modules/hardware/HardwareMonitorButton",
    requiredStates: [],
    signals: [
      { kind: "branch", condition: "!canMonitor", line: 29 },
      { kind: "branch", condition: "existing", line: 35 },
    ],
  },
  "modules/host-mount/conversation-extension/components/ConversationMountsControl": {
    surface: "modules/host-mount/conversation-extension/components/ConversationMountsControl",
    requiredStates: ["empty","open"],
    signals: [
      { kind: "branch", condition: "!conversationId", line: 24 },
      { kind: "branch", condition: "!picked || Array.isArray(picked)", line: 43 },
      { kind: "branch", condition: "draft.some((m) => m.host_path === picked)", line: 44 },
      { kind: "empty", condition: "draft.length === 0", line: 67 },
      { kind: "overlay", condition: "<Popover open>", line: 118 },
    ],
  },
  "modules/host-mount/project-extension/components/ProjectMountsPanel": {
    surface: "modules/host-mount/project-extension/components/ProjectMountsPanel",
    requiredStates: ["delayed","empty"],
    signals: [
      { kind: "branch", condition: "!project", line: 41 },
      { kind: "branch", condition: "!picked || Array.isArray(picked)", line: 49 },
      { kind: "branch", condition: "draft.some((m) => m.host_path === picked)", line: 50 },
      { kind: "loading", condition: "loading && draft.length === 0", line: 102 },
      { kind: "empty", condition: "draft.length === 0", line: 107 },
    ],
  },
  "modules/layouts/app-layout/components/Drawer": {
    surface: "modules/layouts/app-layout/components/Drawer",
    requiredStates: ["empty"],
    signals: [
      { kind: "branch", condition: "!isTauriView", line: 119 },
      { kind: "branch", condition: "!open", line: 120 },
      { kind: "branch", condition: "!isTauriView", line: 154 },
      { kind: "branch", condition: "isLinux", line: 155 },
      { kind: "branch", condition: "e.button !== 0", line: 156 },
      { kind: "branch", condition: "target.closest?.(INTERACTIVE_SEL)", line: 158 },
      { kind: "branch", condition: "!isTauriView", line: 167 },
      { kind: "branch", condition: "isLinux", line: 168 },
      { kind: "branch", condition: "target.closest?.(INTERACTIVE_SEL)", line: 170 },
      { kind: "branch", condition: "Array.isArray(footer)", line: 204 },
      { kind: "branch", condition: "showOverlay", line: 230 },
      { kind: "branch", condition: "title != null", line: 249 },
      { kind: "branch", condition: "typeof title === 'string'", line: 261 },
      { kind: "branch", condition: "extra != null", line: 266 },
      { kind: "branch", condition: "closable", line: 267 },
      { kind: "empty", condition: "noBodyScrollWrap", line: 277 },
      { kind: "branch", condition: "footerNode != null", line: 280 },
      { kind: "branch", condition: "title == null", line: 287 },
    ],
  },
  "modules/layouts/app-layout/components/HeaderBarContainer": {
    surface: "modules/layouts/app-layout/components/HeaderBarContainer",
    requiredStates: [],
    signals: [
      { kind: "branch", condition: "!isTauriView", line: 128 },
      { kind: "branch", condition: "isLinux", line: 133 },
      { kind: "branch", condition: "e.button !== 0", line: 134 },
      { kind: "branch", condition: "target.closest?.(INTERACTIVE_SEL)", line: 136 },
      { kind: "branch", condition: "!isTauriView", line: 147 },
      { kind: "branch", condition: "isLinux", line: 148 },
      { kind: "branch", condition: "target.closest?.(INTERACTIVE_SEL)", line: 150 },
    ],
  },
  "modules/layouts/app-layout/components/LeftSidebar": {
    surface: "modules/layouts/app-layout/components/LeftSidebar",
    requiredStates: [],
    signals: [
      { kind: "branch", condition: "!glassActive", line: 135 },
      { kind: "branch", condition: "showResizeHandle", line: 231 },
      { kind: "branch", condition: "!realHandle", line: 237 },
    ],
  },
  "modules/layouts/app-layout/components/SidebarHeaderSpacer": {
    surface: "modules/layouts/app-layout/components/SidebarHeaderSpacer",
    requiredStates: [],
    signals: [
      { kind: "branch", condition: "!isTauriView", line: 30 },
      { kind: "branch", condition: "isLinux", line: 32 },
      { kind: "branch", condition: "e.button !== 0", line: 33 },
      { kind: "branch", condition: "target.closest?.(INTERACTIVE_SEL)", line: 35 },
      { kind: "branch", condition: "!isTauriView", line: 44 },
      { kind: "branch", condition: "isLinux", line: 45 },
      { kind: "branch", condition: "target.closest?.(INTERACTIVE_SEL)", line: 47 },
    ],
  },
  "modules/layouts/app-layout/components/SidebarToggleButton": {
    surface: "modules/layouts/app-layout/components/SidebarToggleButton",
    requiredStates: [],
    signals: [
      { kind: "branch", condition: "isSidebarCollapsed", line: 76 },
    ],
  },
  "modules/remote-access/pages/RemoteAccessPage": {
    surface: "modules/remote-access/pages/RemoteAccessPage",
    requiredStates: ["delayed","error"],
    signals: [
      { kind: "branch", condition: "isTunneledView", line: 122 },
      { kind: "loading", condition: "loading && !status", line: 146 },
      { kind: "branch", condition: "!status", line: 154 },
      { kind: "error", condition: "error", line: 186 },
      { kind: "branch", condition: "status.auth_token_set", line: 239 },
      { kind: "branch", condition: "status.ngrok_domain", line: 293 },
      { kind: "branch", condition: "!tunnelReady", line: 363 },
      { kind: "branch", condition: "tunnelReady && !tunnelConnected", line: 371 },
      { kind: "branch", condition: "status.auto_start_tunnel && status.last_error", line: 373 },
      { kind: "branch", condition: "!status.auto_start_tunnel && status.last_error", line: 395 },
      { kind: "branch", condition: "tunnelConnected && status.public_url", line: 404 },
      { kind: "branch", condition: "magicLink", line: 425 },
      { kind: "branch", condition: "status.password_auth_enabled", line: 459 },
      { kind: "branch", condition: "v.new_password !== v.confirm", line: 538 },
      { kind: "branch", condition: "v && needsRotationToEnable", line: 579 },
      { kind: "branch", condition: "status.password_auth_enabled && status.password_rotated", line: 601 },
      { kind: "branch", condition: "showChangePassword", line: 612 },
      { kind: "branch", condition: "needsRotationToEnable", line: 619 },
    ],
  },
  "modules/settings/SettingsPage": {
    surface: "modules/settings/SettingsPage",
    requiredStates: [],
    signals: [
      { kind: "branch", condition: "useMobileLayout", line: 196 },
      { kind: "branch", condition: "!useMobileLayout", line: 229 },
    ],
  },
  "modules/tunnel-auth/MagicLinkPage": {
    surface: "modules/tunnel-auth/MagicLinkPage",
    requiredStates: [],
    signals: [
      { kind: "branch", condition: "!token", line: 54 },
      { kind: "branch", condition: "unmounted", line: 59 },
      { kind: "branch", condition: "!token", line: 71 },
      { kind: "branch", condition: "exchangingToken === token && !exchangeError", line: 84 },
      { kind: "branch", condition: "exchangeError", line: 93 },
      { kind: "branch", condition: "Stores.Auth.__state.isAuthenticated", line: 99 },
    ],
  },
  "modules/tunnel-auth/PhoneAuthPage": {
    surface: "modules/tunnel-auth/PhoneAuthPage",
    requiredStates: [],
    signals: [
      { kind: "branch", condition: "configError && !authConfig", line: 92 },
      { kind: "branch", condition: "loadingConfig || !authConfig", line: 105 },
      { kind: "branch", condition: "!authConfig.password_auth_enabled", line: 113 },
      { kind: "branch", condition: "submitError", line: 159 },
    ],
  },
  "modules/updater/components/UpdateBanner": {
    surface: "modules/updater/components/UpdateBanner",
    requiredStates: ["error"],
    signals: [
      { kind: "branch", condition: "!available || dismissed", line: 32 },
      { kind: "branch", condition: "version", line: 44 },
      { kind: "branch", condition: "installing", line: 51 },
      { kind: "error", condition: "error", line: 79 },
    ],
  },
  "modules/updater/pages/AboutPage": {
    surface: "modules/updater/pages/AboutPage",
    requiredStates: ["error"],
    signals: [
      { kind: "error", condition: "error", line: 62 },
      { kind: "branch", condition: "available && version", line: 72 },
      { kind: "branch", condition: "notes", line: 78 },
      { kind: "branch", condition: "downloading", line: 82 },
      { kind: "branch", condition: "available && !readyToInstall", line: 105 },
      { kind: "branch", condition: "readyToInstall", line: 116 },
      { kind: "branch", condition: "upToDate && currentVersion", line: 127 },
    ],
  },
}

/** Right-panel renderers — each is a distinct right-panel-open state to render. */
export const PANEL_RENDERERS: PanelRegistration[] = [

]

/** Slot registrations (discoverability map for sidebar/settings/panel mount points). */
export const SLOT_REGISTRATIONS: SlotRegistration[] = [
  { slot: "chatConversationHeaderTrailing", surface: "modules/host-mount/module", line: 68 },
  { slot: "settingsAdminPages", surface: "modules/host-mount/module", line: 57 },
  { slot: "settingsAdminPages", surface: "modules/remote-access/module", line: 53 },
  { slot: "settingsUserPages", surface: "modules/memory/module", line: 42 },
  { slot: "settingsUserPages", surface: "modules/updater/module", line: 49 },
]

export type StateMatrixSurface = keyof typeof STATE_MATRIX

/**
 * The TSC-ENFORCED coverage key set: one `"<surface>:<state>"` per named
 * required state extracted above. `stateCoverage.ts` declares
 * `STATE_COVERAGE satisfies Record<RequiredState, StateCoverageEntry>`, so a
 * newly-extracted state with no entry is a compile error (mirrors how
 * galleryCoverage.generated.ts's `GallerySurface` gates coverage.ts).
 * 9 keys.
 */
export type RequiredState =
  | "modules/host-mount/conversation-extension/components/ConversationMountsControl:empty"
  | "modules/host-mount/conversation-extension/components/ConversationMountsControl:open"
  | "modules/host-mount/project-extension/components/ProjectMountsPanel:delayed"
  | "modules/host-mount/project-extension/components/ProjectMountsPanel:empty"
  | "modules/layouts/app-layout/components/Drawer:empty"
  | "modules/remote-access/pages/RemoteAccessPage:delayed"
  | "modules/remote-access/pages/RemoteAccessPage:error"
  | "modules/updater/components/UpdateBanner:error"
  | "modules/updater/pages/AboutPage:error"

/** Every required-state key, at runtime (for the scaffold + reporting). */
export const REQUIRED_STATE_KEYS = [
  "modules/host-mount/conversation-extension/components/ConversationMountsControl:empty",
  "modules/host-mount/conversation-extension/components/ConversationMountsControl:open",
  "modules/host-mount/project-extension/components/ProjectMountsPanel:delayed",
  "modules/host-mount/project-extension/components/ProjectMountsPanel:empty",
  "modules/layouts/app-layout/components/Drawer:empty",
  "modules/remote-access/pages/RemoteAccessPage:delayed",
  "modules/remote-access/pages/RemoteAccessPage:error",
  "modules/updater/components/UpdateBanner:error",
  "modules/updater/pages/AboutPage:error",
] as const
