// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  clearError: typeof import('./actions/clearError')['default']
  loadCalls: typeof import('./actions/loadCalls')['default']
  setHideBuiltIn: typeof import('./actions/setHideBuiltIn')['default']
  setPage: typeof import('./actions/setPage')['default']
}
