// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  attachFor: typeof import('./actions/attachFor')['default']
  detachFor: typeof import('./actions/detachFor')['default']
  loadForConversation: typeof import('./actions/loadForConversation')['default']
  loadInheritedFor: typeof import('./actions/loadInheritedFor')['default']
  resetPending: typeof import('./actions/resetPending')['default']
  transferPending: typeof import('./actions/transferPending')['default']
}
