/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by vite-plugin-component-types.js
 * Automatically regenerated when .tsx files change
 *
 * Contains TypeScript types for all React component names in the codebase.
 * Used to provide IntelliSense when selecting components in tests.
 *
 * Last generated: 2025-11-07T17:42:55.673Z
 */

/**
 * Union type of all available React component names in the application
 *
 * This type is used by test helpers to provide autocomplete/IntelliSense
 * when selecting components by their data-component-name attribute.
 *
 * @example
 * getComponent(page, 'UsersSettings')  // IntelliSense shows all component names
 */
export type ComponentName =
  | 'AddLocalLlmModelDownloadDrawer'
  | 'AddLocalLlmModelUploadDrawer'
  | 'AddRemoteLlmModelDrawer'
  | 'AppLayout'
  | 'AssignGroupDrawer'
  | 'AssistantCard'
  | 'AssistantFormDrawer'
  | 'AssistantsSettings'
  | 'BlankLayout'
  | 'CreateUserDrawer'
  | 'DownloadIndicatorWidget'
  | 'DownloadItem'
  | 'DownloadProgress'
  | 'DownloadsSection'
  | 'EditLlmModelDrawer'
  | 'EditUserDrawer'
  | 'EditUserGroupDrawer'
  | 'GlobalComponentRenderer'
  | 'GroupListItem'
  | 'GroupLlmProvidersAssignmentDrawer'
  | 'GroupMembersDrawer'
  | 'GroupSystemMcpServersAssignmentDrawer'
  | 'GroupSystemMcpServersWidget'
  | 'HardwareMonitor'
  | 'LLMProviderGroupWidget'
  | 'LeftSidebar'
  | 'LlamaCppLlmModelSettingsSection'
  | 'LlmModelCapabilitiesSection'
  | 'LlmModelLlamaCppSettingsSection'
  | 'LlmModelMistralRsSettingsSection'
  | 'LlmModelParameterField'
  | 'LlmModelParametersSection'
  | 'LlmModelsSection'
  | 'LlmProviderDrawer'
  | 'LlmProviderGroupsAssignmentDrawer'
  | 'LlmProviderSettings'
  | 'LlmRepositoryDrawer'
  | 'LlmRepositorySettings'
  | 'LocalLlmModelCommonFields'
  | 'LocalProviderSettings'
  | 'McpServerCard'
  | 'McpServerDrawer'
  | 'McpServerGroupsAssignmentCard'
  | 'McpServerGroupsAssignmentDrawer'
  | 'McpServersSettings'
  | 'MistralRsLlmModelSettingsSection'
  | 'ProviderGroupAssignmentCard'
  | 'ProviderHeader'
  | 'ProviderProxySettingsForm'
  | 'RemoteProviderSettings'
  | 'ResetPasswordDrawer'
  | 'ResizeHandle'
  | 'SettingsPageContainer'
  | 'SidebarToggleButton'
  | 'SystemMcpServersPage'
  | 'SystemServersTab'
  | 'ThemeProvider'
  | 'ThemeSettings'
  | 'TitleBarWrapper'
  | 'UserAssistantsPage'
  | 'UserGroupsDrawer'
  | 'UserGroupsSettings'
  | 'UserProfileWidget'
  | 'UserRegistrationSettings'
  | 'UsersSettings'
  | 'WidgetRenderer'

/**
 * Total number of components: 66
 */
