// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  clearLlmRepositoryStoreError: typeof import('./actions/clearLlmRepositoryStoreError')['default']
  createLlmRepository: typeof import('./actions/createLlmRepository')['default']
  deleteLlmRepository: typeof import('./actions/deleteLlmRepository')['default']
  findLlmRepositoryById: typeof import('./actions/findLlmRepositoryById')['default']
  llmRepositoryHasCredentials: typeof import('./actions/llmRepositoryHasCredentials')['default']
  loadLlmRepositories: typeof import('./actions/loadLlmRepositories')['default']
  testLlmRepositoryById: typeof import('./actions/testLlmRepositoryById')['default']
  testLlmRepositoryConnection: typeof import('./actions/testLlmRepositoryConnection')['default']
  updateLlmRepository: typeof import('./actions/updateLlmRepository')['default']
}
