// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  closePane: typeof import('./actions/closePane')['default']
  focusPane: typeof import('./actions/focusPane')['default']
  hydrateWorkspace: typeof import('./actions/hydrateWorkspace')['default']
  openConversationInWorkspace: typeof import('./actions/openConversationInWorkspace')['default']
  openPane: typeof import('./actions/openPane')['default']
  reorderPanes: typeof import('./actions/reorderPanes')['default']
  reset: typeof import('./actions/reset')['default']
  setDividerWidth: typeof import('./actions/setDividerWidth')['default']
  setMode: typeof import('./actions/setMode')['default']
  setPaneConversation: typeof import('./actions/setPaneConversation')['default']
  setPaneManagerOpen: typeof import('./actions/setPaneManagerOpen')['default']
}
