// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  closeMobileOverlay: typeof import('./actions/closeMobileOverlay')['default']
  setHeaderHidden: typeof import('./actions/setHeaderHidden')['default']
  setIsFullscreen: typeof import('./actions/setIsFullscreen')['default']
  setIsMobile: typeof import('./actions/setIsMobile')['default']
  setMainContentWidth: typeof import('./actions/setMainContentWidth')['default']
  setMobileOverlayOpen: typeof import('./actions/setMobileOverlayOpen')['default']
  setNativeScroll: typeof import('./actions/setNativeScroll')['default']
  setSidebarCollapsed: typeof import('./actions/setSidebarCollapsed')['default']
  setSidebarWidth: typeof import('./actions/setSidebarWidth')['default']
  toggleSidebar: typeof import('./actions/toggleSidebar')['default']
}
