/**
 * Gallery coverage registry — the ENFORCED gate.
 *
 * `GALLERY_COVERAGE` maps EVERY generated `GallerySurface` (see
 * galleryCoverage.generated.ts) to how the gallery covers it. Because the object
 * is `satisfies Record<GallerySurface, Coverage>`, a surface with no entry is a
 * COMPILE error, and a stale key (deleted file) is also a compile error.
 *
 * Coverage kinds:
 *   - page(id)    — this surface IS a seeded gallery page (see ALL_PAGES).
 *   - story(id)   — covered by a kit story section (see stories/).
 *   - via(id)     — rendered inside another covered surface (its page/story).
 *   - allow(why)  — genuinely non-visual (provider/context/pure-logic/null
 *                   render) — no visual entry needed; the reason is reviewed.
 *   - pending(why)— tracked TODO: accounted for, not yet given a visual entry.
 *
 * The tsc gate guarantees every surface is at least `pending`; the parity test
 * (gen-gallery-coverage.mjs --check) lists pending surfaces so they stay visible.
 */
import type { GallerySurface } from './galleryCoverage.generated'

export type Coverage =
  | { kind: 'page'; pageId: string }
  | { kind: 'story'; storyId: string }
  | { kind: 'via'; surface: string }
  | { kind: 'allow'; reason: string }
  | { kind: 'pending'; reason: string }

export const page = (pageId: string): Coverage => ({ kind: 'page', pageId })
export const story = (storyId: string): Coverage => ({ kind: 'story', storyId })
export const via = (surface: string): Coverage => ({ kind: 'via', surface })
export const allow = (reason: string): Coverage => ({ kind: 'allow', reason })
export const pending = (reason: string): Coverage => ({ kind: 'pending', reason })

// Keep this object total over GallerySurface. The `// <<< scaffold-insert >>>`
// marker is where `gen:gallery-coverage --scaffold` appends missing surfaces as
// `pending(...)`; refine each into page/story/via/allow as coverage lands.
export const GALLERY_COVERAGE = {
  "components/ui/kit/accordion": pending('auto-scaffold — needs review'),
  "components/ui/kit/alert": pending('auto-scaffold — needs review'),
  "components/ui/kit/attachment": pending('auto-scaffold — needs review'),
  "components/ui/kit/avatar": pending('auto-scaffold — needs review'),
  "components/ui/kit/badge": pending('auto-scaffold — needs review'),
  "components/ui/kit/button": pending('auto-scaffold — needs review'),
  "components/ui/kit/card": pending('auto-scaffold — needs review'),
  "components/ui/kit/checkbox": pending('auto-scaffold — needs review'),
  "components/ui/kit/combobox": pending('auto-scaffold — needs review'),
  "components/ui/kit/confirm": pending('auto-scaffold — needs review'),
  "components/ui/kit/date-picker": pending('auto-scaffold — needs review'),
  "components/ui/kit/descriptions": pending('auto-scaffold — needs review'),
  "components/ui/kit/dialog": pending('auto-scaffold — needs review'),
  "components/ui/kit/dialog-host": pending('auto-scaffold — needs review'),
  "components/ui/kit/dropdown": pending('auto-scaffold — needs review'),
  "components/ui/kit/empty": pending('auto-scaffold — needs review'),
  "components/ui/kit/flex": pending('auto-scaffold — needs review'),
  "components/ui/kit/form": pending('auto-scaffold — needs review'),
  "components/ui/kit/image": pending('auto-scaffold — needs review'),
  "components/ui/kit/input": pending('auto-scaffold — needs review'),
  "components/ui/kit/input-number": pending('auto-scaffold — needs review'),
  "components/ui/kit/layout": pending('auto-scaffold — needs review'),
  "components/ui/kit/list": pending('auto-scaffold — needs review'),
  "components/ui/kit/menu": pending('auto-scaffold — needs review'),
  "components/ui/kit/multi-select": pending('auto-scaffold — needs review'),
  "components/ui/kit/pagination": pending('auto-scaffold — needs review'),
  "components/ui/kit/popover": pending('auto-scaffold — needs review'),
  "components/ui/kit/progress": pending('auto-scaffold — needs review'),
  "components/ui/kit/radio-group": pending('auto-scaffold — needs review'),
  "components/ui/kit/result": pending('auto-scaffold — needs review'),
  "components/ui/kit/scroll-area": pending('auto-scaffold — needs review'),
  "components/ui/kit/segmented": pending('auto-scaffold — needs review'),
  "components/ui/kit/select": pending('auto-scaffold — needs review'),
  "components/ui/kit/separator": pending('auto-scaffold — needs review'),
  "components/ui/kit/sheet": pending('auto-scaffold — needs review'),
  "components/ui/kit/sidebar": pending('auto-scaffold — needs review'),
  "components/ui/kit/skeleton": pending('auto-scaffold — needs review'),
  "components/ui/kit/space": pending('auto-scaffold — needs review'),
  "components/ui/kit/spinner": pending('auto-scaffold — needs review'),
  "components/ui/kit/statistic": pending('auto-scaffold — needs review'),
  "components/ui/kit/surface": pending('auto-scaffold — needs review'),
  "components/ui/kit/switch": pending('auto-scaffold — needs review'),
  "components/ui/kit/table": pending('auto-scaffold — needs review'),
  "components/ui/kit/tabs": pending('auto-scaffold — needs review'),
  "components/ui/kit/tag": pending('auto-scaffold — needs review'),
  "components/ui/kit/textarea": pending('auto-scaffold — needs review'),
  "components/ui/kit/theme": pending('auto-scaffold — needs review'),
  "components/ui/kit/toast": pending('auto-scaffold — needs review'),
  "components/ui/kit/tooltip": pending('auto-scaffold — needs review'),
  "components/ui/kit/tree": pending('auto-scaffold — needs review'),
  "components/ui/kit/typography": pending('auto-scaffold — needs review'),
  "components/ui/kit/upload": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/accordion": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/alert": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/alert-dialog": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/aspect-ratio": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/attachment": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/avatar": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/badge": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/breadcrumb": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/button": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/button-group": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/calendar": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/card": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/carousel": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/checkbox": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/collapsible": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/combobox": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/command": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/context-menu": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/dialog": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/drawer": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/dropdown-menu": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/empty": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/field": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/hover-card": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/input": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/input-group": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/input-otp": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/item": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/kbd": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/label": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/menubar": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/native-select": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/navigation-menu": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/pagination": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/popover": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/progress": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/radio-group": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/resizable": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/scroll-area": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/select": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/separator": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/sheet": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/sidebar": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/skeleton": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/slider": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/sonner": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/spinner": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/switch": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/table": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/tabs": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/textarea": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/toggle": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/toggle-group": pending('auto-scaffold — needs review'),
  "components/ui/shadcn/tooltip": pending('auto-scaffold — needs review'),
  "modules/app/SetupPage": pending('auto-scaffold — needs review'),
  "modules/assistant/chat-extension/components/AssistantMenuItem": pending('auto-scaffold — needs review'),
  "modules/assistant/chat-extension/components/AssistantSelector": pending('auto-scaffold — needs review'),
  "modules/assistant/chat-extension/components/AssistantStatusChip": pending('auto-scaffold — needs review'),
  "modules/assistant/chat-extension/extension": pending('auto-scaffold — needs review'),
  "modules/assistant/components/AssistantFormDrawer": pending('auto-scaffold — needs review'),
  "modules/assistant/pages/AssistantsSettings": pending('auto-scaffold — needs review'),
  "modules/assistant/pages/UserAssistantsSettings": pending('auto-scaffold — needs review'),
  "modules/auth-providers/AuthProvidersSettingsPage": pending('auto-scaffold — needs review'),
  "modules/auth-providers/components/AddProviderMenu": pending('auto-scaffold — needs review'),
  "modules/auth-providers/components/AuthProviderEditDrawer": pending('auto-scaffold — needs review'),
  "modules/auth-providers/components/AuthProvidersListSection": pending('auto-scaffold — needs review'),
  "modules/auth/AuthCallbackPage": pending('auto-scaffold — needs review'),
  "modules/auth/AuthGuard": pending('auto-scaffold — needs review'),
  "modules/auth/AuthPage": pending('auto-scaffold — needs review'),
  "modules/auth/LinkAccountPage": pending('auto-scaffold — needs review'),
  "modules/auth/LoginForm": pending('auto-scaffold — needs review'),
  "modules/auth/ProviderButtons": pending('auto-scaffold — needs review'),
  "modules/auth/RegisterForm": pending('auto-scaffold — needs review'),
  "modules/auth/SessionSettingsPage": pending('auto-scaffold — needs review'),
  "modules/chat/components/BranchNavigator": pending('auto-scaffold — needs review'),
  "modules/chat/components/ChatInput": pending('auto-scaffold — needs review'),
  "modules/chat/components/ChatMessage": pending('auto-scaffold — needs review'),
  "modules/chat/components/ContentRenderer": pending('auto-scaffold — needs review'),
  "modules/chat/components/ConversationCard": pending('auto-scaffold — needs review'),
  "modules/chat/components/ConversationList": pending('auto-scaffold — needs review'),
  "modules/chat/components/EditingMessageBanner": pending('auto-scaffold — needs review'),
  "modules/chat/components/MessageActions": pending('auto-scaffold — needs review'),
  "modules/chat/components/MessageList": pending('auto-scaffold — needs review'),
  "modules/chat/components/ModelSelector": pending('auto-scaffold — needs review'),
  "modules/chat/components/TextContent": pending('auto-scaffold — needs review'),
  "modules/chat/components/TitleEditor": pending('auto-scaffold — needs review'),
  "modules/chat/core/MessageContext": pending('auto-scaffold — needs review'),
  "modules/chat/core/components/ChatRightPanel": pending('auto-scaffold — needs review'),
  "modules/chat/core/extensions/registry": pending('auto-scaffold — needs review'),
  "modules/chat/core/extensions/slots": pending('auto-scaffold — needs review'),
  "modules/chat/core/extensions/utils": pending('auto-scaffold — needs review'),
  "modules/chat/core/utils/StreamdownErrorBoundary": pending('auto-scaffold — needs review'),
  "modules/chat/core/utils/useStreamdownComponents": pending('auto-scaffold — needs review'),
  "modules/chat/extensions/export/extension": pending('auto-scaffold — needs review'),
  "modules/chat/extensions/keyboard/extension": pending('auto-scaffold — needs review'),
  "modules/chat/extensions/syntax/extension": pending('auto-scaffold — needs review'),
  "modules/chat/extensions/text/components/TextContent": pending('auto-scaffold — needs review'),
  "modules/chat/extensions/text/components/TextInput": pending('auto-scaffold — needs review'),
  "modules/chat/extensions/text/components/ThinkingContent": pending('auto-scaffold — needs review'),
  "modules/chat/extensions/text/extension": pending('auto-scaffold — needs review'),
  "modules/chat/extensions/title/extension": pending('auto-scaffold — needs review'),
  "modules/chat/pages/ChatHistoryPage": pending('auto-scaffold — needs review'),
  "modules/chat/pages/ConversationPage": pending('auto-scaffold — needs review'),
  "modules/chat/pages/NewChatPage": pending('auto-scaffold — needs review'),
  "modules/chat/widgets/RecentConversationsWidget": pending('auto-scaffold — needs review'),
  "modules/citations/components/CitationCard": pending('auto-scaffold — needs review'),
  "modules/citations/components/ImportCitationsModal": pending('auto-scaffold — needs review'),
  "modules/citations/components/VerificationBadge": pending('auto-scaffold — needs review'),
  "modules/citations/pages/CitationsSettingsPage": pending('auto-scaffold — needs review'),
  "modules/citations/project-extension/components/ProjectBibliographyInlinePreview": pending('auto-scaffold — needs review'),
  "modules/citations/project-extension/components/ProjectBibliographyManagePanel": pending('auto-scaffold — needs review'),
  "modules/citations/project-extension/extension": pending('auto-scaffold — needs review'),
  "modules/code-sandbox/components/AvailableRootfsCard": pending('auto-scaffold — needs review'),
  "modules/code-sandbox/components/DownloadedRootfsCard": pending('auto-scaffold — needs review'),
  "modules/code-sandbox/components/RootfsVersionGroup": pending('auto-scaffold — needs review'),
  "modules/code-sandbox/components/SandboxResourceLimitsSection": pending('auto-scaffold — needs review'),
  "modules/code-sandbox/components/SandboxRootfsVersionsSection": pending('auto-scaffold — needs review'),
  "modules/code-sandbox/components/SandboxSettingsPage": pending('auto-scaffold — needs review'),
  "modules/code-sandbox/components/_rootfsShared": pending('auto-scaffold — needs review'),
  "modules/file-rag/components/sections/ChunkingSection": pending('auto-scaffold — needs review'),
  "modules/file-rag/components/sections/EmbeddingSection": pending('auto-scaffold — needs review'),
  "modules/file-rag/components/sections/EnableSection": pending('auto-scaffold — needs review'),
  "modules/file-rag/components/sections/FullTextSection": pending('auto-scaffold — needs review'),
  "modules/file-rag/components/sections/MaintenanceSection": pending('auto-scaffold — needs review'),
  "modules/file-rag/pages/FileRagAdminPage": pending('auto-scaffold — needs review'),
  "modules/file/chat-extension/components/FileAttachMenuItem": pending('auto-scaffold — needs review'),
  "modules/file/chat-extension/components/FilePreviewList": pending('auto-scaffold — needs review'),
  "modules/file/chat-extension/components/FileUploadArea": pending('auto-scaffold — needs review'),
  "modules/file/chat-extension/components/FileUploadButton": pending('auto-scaffold — needs review'),
  "modules/file/chat-extension/components/ImageContent": pending('auto-scaffold — needs review'),
  "modules/file/chat-extension/components/InlineFilePreview": pending('auto-scaffold — needs review'),
  "modules/file/chat-extension/components/MessageFilesView": pending('auto-scaffold — needs review'),
  "modules/file/chat-extension/extension": pending('auto-scaffold — needs review'),
  "modules/file/components/FileCard": pending('auto-scaffold — needs review'),
  "modules/file/components/FilePanel": pending('auto-scaffold — needs review'),
  "modules/file/components/FilePreviewDrawer": pending('auto-scaffold — needs review'),
  "modules/file/components/FileVersionBar": pending('auto-scaffold — needs review'),
  "modules/file/project-extension/components/ProjectFilesInlinePreview": pending('auto-scaffold — needs review'),
  "modules/file/project-extension/components/ProjectFilesManagePanel": pending('auto-scaffold — needs review'),
  "modules/file/project-extension/extension": pending('auto-scaffold — needs review'),
  "modules/file/viewers/image/body": pending('auto-scaffold — needs review'),
  "modules/file/viewers/image/header": pending('auto-scaffold — needs review'),
  "modules/file/viewers/markdown/body": pending('auto-scaffold — needs review'),
  "modules/file/viewers/markdown/header": pending('auto-scaffold — needs review'),
  "modules/file/viewers/pdf/body": pending('auto-scaffold — needs review'),
  "modules/file/viewers/pdf/header": pending('auto-scaffold — needs review'),
  "modules/file/viewers/shared/RawCodeView": pending('auto-scaffold — needs review'),
  "modules/file/viewers/shared/chrome": pending('auto-scaffold — needs review'),
  "modules/file/viewers/tabular/DelimitedTable": pending('auto-scaffold — needs review'),
  "modules/file/viewers/tabular/XlsxBody": pending('auto-scaffold — needs review'),
  "modules/file/viewers/tabular/body": pending('auto-scaffold — needs review'),
  "modules/file/viewers/tabular/header": pending('auto-scaffold — needs review'),
  "modules/file/viewers/text/body": pending('auto-scaffold — needs review'),
  "modules/file/viewers/text/header": pending('auto-scaffold — needs review'),
  "modules/file/viewers/web/body": pending('auto-scaffold — needs review'),
  "modules/file/viewers/web/header": pending('auto-scaffold — needs review'),
  "modules/hardware/HardwareMonitor": pending('auto-scaffold — needs review'),
  "modules/hardware/HardwareMonitorButton": pending('auto-scaffold — needs review'),
  "modules/hardware/HardwareSettings": pending('auto-scaffold — needs review'),
  "modules/hub/HubPage": pending('auto-scaffold — needs review'),
  "modules/hub/modules/assistants/components/AssistantDetailsDrawer": pending('auto-scaffold — needs review'),
  "modules/hub/modules/assistants/components/AssistantHubCard": pending('auto-scaffold — needs review'),
  "modules/hub/modules/assistants/components/AssistantsHubTab": pending('auto-scaffold — needs review'),
  "modules/hub/modules/installed/components/InstalledHubTab": pending('auto-scaffold — needs review'),
  "modules/hub/modules/llm-models/components/ModelDetailsDrawer": pending('auto-scaffold — needs review'),
  "modules/hub/modules/llm-models/components/ModelHubCard": pending('auto-scaffold — needs review'),
  "modules/hub/modules/llm-models/components/ModelsHubTab": pending('auto-scaffold — needs review'),
  "modules/hub/modules/llm-models/hooks/useHubModelDownloadGate": pending('auto-scaffold — needs review'),
  "modules/hub/modules/mcp/components/McpServerDetailsDrawer": pending('auto-scaffold — needs review'),
  "modules/hub/modules/mcp/components/McpServerHubCard": pending('auto-scaffold — needs review'),
  "modules/hub/modules/mcp/components/McpServersHubTab": pending('auto-scaffold — needs review'),
  "modules/hub/modules/skill/components/SkillDetailsDrawer": pending('auto-scaffold — needs review'),
  "modules/hub/modules/skill/components/SkillHubCard": pending('auto-scaffold — needs review'),
  "modules/hub/modules/skill/components/SkillsHubTab": pending('auto-scaffold — needs review'),
  "modules/hub/modules/workflow/components/WorkflowDetailsDrawer": pending('auto-scaffold — needs review'),
  "modules/hub/modules/workflow/components/WorkflowHubCard": pending('auto-scaffold — needs review'),
  "modules/hub/modules/workflow/components/WorkflowsHubTab": pending('auto-scaffold — needs review'),
  "modules/layouts/app-layout/AppLayout": pending('auto-scaffold — needs review'),
  "modules/layouts/app-layout/components/Drawer": pending('auto-scaffold — needs review'),
  "modules/layouts/app-layout/components/HeaderBarContainer": pending('auto-scaffold — needs review'),
  "modules/layouts/app-layout/components/LeftSidebar": pending('auto-scaffold — needs review'),
  "modules/layouts/app-layout/components/ResizeHandle": pending('auto-scaffold — needs review'),
  "modules/layouts/app-layout/components/SidebarHeaderSpacer": pending('auto-scaffold — needs review'),
  "modules/layouts/app-layout/components/SidebarToggleButton": pending('auto-scaffold — needs review'),
  "modules/layouts/blank/BlankLayout": pending('auto-scaffold — needs review'),
  "modules/literature/chat-extension/extension": pending('auto-scaffold — needs review'),
  "modules/literature/components/LiteratureScreeningPanel": pending('auto-scaffold — needs review'),
  "modules/literature/components/LiteratureToolResultCard": pending('auto-scaffold — needs review'),
  "modules/literature/components/settings/LitSearchConnectorsSection": pending('auto-scaffold — needs review'),
  "modules/literature/components/settings/LitSearchGlobalSection": pending('auto-scaffold — needs review'),
  "modules/literature/components/settings/LitSearchSettingsPage": pending('auto-scaffold — needs review'),
  "modules/literature/components/settings/LitSearchUserKeysPage": pending('auto-scaffold — needs review'),
  "modules/llm-local-runtime/components/AvailableVersionsCard": pending('auto-scaffold — needs review'),
  "modules/llm-local-runtime/components/InstalledVersionsCard": pending('auto-scaffold — needs review'),
  "modules/llm-local-runtime/components/LiveLogsPanel": pending('auto-scaffold — needs review'),
  "modules/llm-local-runtime/components/RuntimeConfigCard": pending('auto-scaffold — needs review'),
  "modules/llm-local-runtime/components/RuntimeVersionCard": pending('auto-scaffold — needs review'),
  "modules/llm-local-runtime/components/RuntimeVersionSettings": pending('auto-scaffold — needs review'),
  "modules/llm-local-runtime/components/VersionModelsBlock": pending('auto-scaffold — needs review'),
  "modules/llm-local-runtime/components/_engineVersionsShared": pending('auto-scaffold — needs review'),
  "modules/llm-local-runtime/components/drawers/RuntimeDownloadDrawer": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/GroupLlmProvidersAssignmentDrawer": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/LlmModelDownloadNotifications": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/LlmModelsSection": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/LlmProviderDrawer": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/LlmProviderSettings": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/LocalProviderSettings": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/ProviderGroupAssignmentCard": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/ProviderHeader": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/ProviderProxySettingsForm": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/RemoteProviderSettings": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/downloads/DownloadItem": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/downloads/DownloadProgress": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/downloads/DownloadsSection": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/llm-models/AddLocalLlmModelDownloadDrawer": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/llm-models/AddLocalLlmModelUploadDrawer": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/llm-models/AddRemoteLlmModelDrawer": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/llm-models/EditLlmModelDrawer": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/llm-models/shared/LlmModelCapabilitiesSection": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/llm-models/shared/LlmModelLlamaCppSettingsSection": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/llm-models/shared/LlmModelMistralRsSettingsSection": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/llm-models/shared/LlmModelParameterField": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/llm-models/shared/LlmModelParametersSection": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/llm-models/shared/LocalLlmModelCommonFields": pending('auto-scaffold — needs review'),
  "modules/llm-provider/components/widgets/DownloadIndicatorWidget": pending('auto-scaffold — needs review'),
  "modules/llm-provider/constants": pending('auto-scaffold — needs review'),
  "modules/llm-provider/icons/DeepSeek": pending('auto-scaffold — needs review'),
  "modules/llm-provider/icons/Mistral": pending('auto-scaffold — needs review'),
  "modules/llm-provider/widgets/LLMProviderGroupWidget": pending('auto-scaffold — needs review'),
  "modules/llm-repository/components/LlmRepositoryDrawer": pending('auto-scaffold — needs review'),
  "modules/llm-repository/components/LlmRepositorySettings": pending('auto-scaffold — needs review'),
  "modules/mcp/chat-extension/components/ElicitationFormContent": pending('auto-scaffold — needs review'),
  "modules/mcp/chat-extension/components/McpInitializer": pending('auto-scaffold — needs review'),
  "modules/mcp/chat-extension/components/McpMenuItem": pending('auto-scaffold — needs review'),
  "modules/mcp/chat-extension/components/McpStatusRow": pending('auto-scaffold — needs review'),
  "modules/mcp/chat-extension/components/ToolCallPendingApprovalCancelContent": pending('auto-scaffold — needs review'),
  "modules/mcp/chat-extension/components/ToolCallPendingApprovalContent": pending('auto-scaffold — needs review'),
  "modules/mcp/chat-extension/extension": pending('auto-scaffold — needs review'),
  "modules/mcp/components/McpConfigModal": pending('auto-scaffold — needs review'),
  "modules/mcp/components/common/KeyValueSecretEditor": pending('auto-scaffold — needs review'),
  "modules/mcp/components/common/McpServerCard": pending('auto-scaffold — needs review'),
  "modules/mcp/components/common/McpServerDrawer": pending('auto-scaffold — needs review'),
  "modules/mcp/components/common/McpToolCallsTab": pending('auto-scaffold — needs review'),
  "modules/mcp/components/common/connectionTestToast": pending('auto-scaffold — needs review'),
  "modules/mcp/components/system/GroupSystemMcpServersAssignmentDrawer": pending('auto-scaffold — needs review'),
  "modules/mcp/components/system/McpServerGroupsAssignmentCard": pending('auto-scaffold — needs review'),
  "modules/mcp/components/system/McpUserPolicyCard": pending('auto-scaffold — needs review'),
  "modules/mcp/components/system/SystemMcpServersPage": pending('auto-scaffold — needs review'),
  "modules/mcp/components/user/McpServersSettings": pending('auto-scaffold — needs review'),
  "modules/mcp/project-extension/components/ProjectMcpSettingsPanel": pending('auto-scaffold — needs review'),
  "modules/mcp/project-extension/extension": pending('auto-scaffold — needs review'),
  "modules/mcp/widgets/GroupSystemMcpServersWidget": pending('auto-scaffold — needs review'),
  "modules/memory/chat-extension/components/MemoryStatusPill": pending('auto-scaffold — needs review'),
  "modules/memory/chat-extension/extension": pending('auto-scaffold — needs review'),
  "modules/memory/components/CoreMemoryBlocksEditor": pending('auto-scaffold — needs review'),
  "modules/memory/components/sections/AuditLogSection": pending('auto-scaffold — needs review'),
  "modules/memory/components/sections/CoreMemorySection": pending('auto-scaffold — needs review'),
  "modules/memory/components/sections/ExtractionSection": pending('auto-scaffold — needs review'),
  "modules/memory/components/sections/FullTextSearchSection": pending('auto-scaffold — needs review'),
  "modules/memory/components/sections/MemorySection": pending('auto-scaffold — needs review'),
  "modules/memory/components/sections/MyMemoriesSection": pending('auto-scaffold — needs review'),
  "modules/memory/components/sections/PreferencesSection": pending('auto-scaffold — needs review'),
  "modules/memory/components/sections/RebuildStatusSection": pending('auto-scaffold — needs review'),
  "modules/memory/components/sections/RetentionLimitsSection": pending('auto-scaffold — needs review'),
  "modules/memory/components/sections/SemanticSearchSection": pending('auto-scaffold — needs review'),
  "modules/memory/pages/MemoryAdminPage": pending('auto-scaffold — needs review'),
  "modules/memory/pages/MemorySettingsPage": pending('auto-scaffold — needs review'),
  "modules/onboarding/OnboardingPage": pending('auto-scaffold — needs review'),
  "modules/onboarding/OnboardingRedirect": pending('auto-scaffold — needs review'),
  "modules/onboarding/guides/getting-started/components/ApiKeysStep": pending('auto-scaffold — needs review'),
  "modules/onboarding/guides/getting-started/components/FinishStep": pending('auto-scaffold — needs review'),
  "modules/onboarding/guides/getting-started/components/McpServersStep": pending('auto-scaffold — needs review'),
  "modules/onboarding/guides/getting-started/components/MemorySetupStep": pending('auto-scaffold — needs review'),
  "modules/onboarding/guides/getting-started/components/WelcomeStep": pending('auto-scaffold — needs review'),
  "modules/profile/pages/ProfileSettingsPage": pending('auto-scaffold — needs review'),
  "modules/projects/chat-extension/components/ProjectConversationsList": pending('auto-scaffold — needs review'),
  "modules/projects/chat-extension/components/ProjectInlineChatInput": pending('auto-scaffold — needs review'),
  "modules/projects/chat-extension/extension": pending('auto-scaffold — needs review'),
  "modules/projects/components/AddToProjectModal": pending('auto-scaffold — needs review'),
  "modules/projects/components/ProjectCard": pending('auto-scaffold — needs review'),
  "modules/projects/components/ProjectDefaultsForm": pending('auto-scaffold — needs review'),
  "modules/projects/components/ProjectFormDrawer": pending('auto-scaffold — needs review'),
  "modules/projects/components/ProjectKnowledgeSection": pending('auto-scaffold — needs review'),
  "modules/projects/core/extensions/registry": pending('auto-scaffold — needs review'),
  "modules/projects/core/extensions/slots": pending('auto-scaffold — needs review'),
  "modules/projects/pages/ProjectDetailPage": pending('auto-scaffold — needs review'),
  "modules/projects/pages/ProjectsListPage": pending('auto-scaffold — needs review'),
  "modules/router/components/RouterComponent": pending('auto-scaffold — needs review'),
  "modules/server-update/AboutSettings": pending('auto-scaffold — needs review'),
  "modules/server-update/ServerUpdateBanner": pending('auto-scaffold — needs review'),
  "modules/settings-general/GeneralSettings": pending('auto-scaffold — needs review'),
  "modules/settings-general/components/ThemeSettings": pending('auto-scaffold — needs review'),
  "modules/settings/SettingsLayout": pending('auto-scaffold — needs review'),
  "modules/settings/SettingsPage": pending('auto-scaffold — needs review'),
  "modules/settings/components/AddButton": pending('auto-scaffold — needs review'),
  "modules/settings/components/SettingsFormActions": pending('auto-scaffold — needs review'),
  "modules/settings/components/SettingsPageContainer": pending('auto-scaffold — needs review'),
  "modules/skill/chat-extension/SkillMenuItem": pending('auto-scaffold — needs review'),
  "modules/skill/chat-extension/extension": pending('auto-scaffold — needs review'),
  "modules/skill/components/ConversationSkillsPanel": pending('auto-scaffold — needs review'),
  "modules/skill/components/ImportSkillDialog": pending('auto-scaffold — needs review'),
  "modules/skill/components/SkillConversationDrawer": pending('auto-scaffold — needs review'),
  "modules/skill/components/SkillDetailDrawer": pending('auto-scaffold — needs review'),
  "modules/skill/components/SkillScopeBadge": pending('auto-scaffold — needs review'),
  "modules/skill/components/SkillsList": pending('auto-scaffold — needs review'),
  "modules/skill/components/admin/AdminSkillGroupAssignment": pending('auto-scaffold — needs review'),
  "modules/skill/components/admin/AdminSkillsPage": pending('auto-scaffold — needs review'),
  "modules/skill/widgets/GroupSystemSkillsAssignmentDrawer": pending('auto-scaffold — needs review'),
  "modules/skill/widgets/GroupSystemSkillsWidget": pending('auto-scaffold — needs review'),
  "modules/summarization/chat-extension/components/SummarizationStatusPill": pending('auto-scaffold — needs review'),
  "modules/summarization/chat-extension/components/SummaryBoundaryMarker": pending('auto-scaffold — needs review'),
  "modules/summarization/chat-extension/extension": pending('auto-scaffold — needs review'),
  "modules/summarization/components/sections/SummarizationSettingsSection": pending('auto-scaffold — needs review'),
  "modules/summarization/pages/SummarizationAdminPage": pending('auto-scaffold — needs review'),
  "modules/user-llm-providers/UserLlmProvidersPage": pending('auto-scaffold — needs review'),
  "modules/user-llm-providers/chat-extension/components/ModelSelector": pending('auto-scaffold — needs review'),
  "modules/user-llm-providers/chat-extension/components/ProviderApiKeyModal": pending('auto-scaffold — needs review'),
  "modules/user-llm-providers/chat-extension/extension": pending('auto-scaffold — needs review'),
  "modules/user-profile/UserProfileWidget": pending('auto-scaffold — needs review'),
  "modules/user/components/PermissionsField": pending('auto-scaffold — needs review'),
  "modules/user/components/group/EditUserGroupDrawer": pending('auto-scaffold — needs review'),
  "modules/user/components/group/GroupListItem": pending('auto-scaffold — needs review'),
  "modules/user/components/group/GroupMembersDrawer": pending('auto-scaffold — needs review'),
  "modules/user/components/group/UserGroupsSettings": pending('auto-scaffold — needs review'),
  "modules/user/components/user/AssignGroupDrawer": pending('auto-scaffold — needs review'),
  "modules/user/components/user/CreateUserDrawer": pending('auto-scaffold — needs review'),
  "modules/user/components/user/EditUserDrawer": pending('auto-scaffold — needs review'),
  "modules/user/components/user/ResetPasswordDrawer": pending('auto-scaffold — needs review'),
  "modules/user/components/user/UserGroupsDrawer": pending('auto-scaffold — needs review'),
  "modules/user/components/user/UserRegistrationSettings": pending('auto-scaffold — needs review'),
  "modules/user/components/user/UsersSettings": pending('auto-scaffold — needs review'),
  "modules/web-search/components/WebSearchGlobalSection": pending('auto-scaffold — needs review'),
  "modules/web-search/components/WebSearchProvidersSection": pending('auto-scaffold — needs review'),
  "modules/web-search/components/WebSearchSettingsPage": pending('auto-scaffold — needs review'),
  "modules/web-search/components/WebSearchUserKeysPage": pending('auto-scaffold — needs review'),
  "modules/workflow/chat-extension/components/WorkflowWorkspaceRunCard": pending('auto-scaffold — needs review'),
  "modules/workflow/chat-extension/extension": pending('auto-scaffold — needs review'),
  "modules/workflow/components/DryRunPreviewDialog": pending('auto-scaffold — needs review'),
  "modules/workflow/components/EditableArrayTable": pending('auto-scaffold — needs review'),
  "modules/workflow/components/ImportWorkflowDialog": pending('auto-scaffold — needs review'),
  "modules/workflow/components/StepArtifacts": pending('auto-scaffold — needs review'),
  "modules/workflow/components/StepLogExpander": pending('auto-scaffold — needs review'),
  "modules/workflow/components/StepOutputExpander": pending('auto-scaffold — needs review'),
  "modules/workflow/components/WorkflowDetailDrawer": pending('auto-scaffold — needs review'),
  "modules/workflow/components/WorkflowElicitForm": pending('auto-scaffold — needs review'),
  "modules/workflow/components/WorkflowRunDialog": pending('auto-scaffold — needs review'),
  "modules/workflow/components/WorkflowRunProgressView": pending('auto-scaffold — needs review'),
  "modules/workflow/components/WorkflowRunsList": pending('auto-scaffold — needs review'),
  "modules/workflow/components/WorkflowScopeBadge": pending('auto-scaffold — needs review'),
  "modules/workflow/components/WorkflowTestsPanel": pending('auto-scaffold — needs review'),
  "modules/workflow/components/WorkflowsList": pending('auto-scaffold — needs review'),
  "modules/workflow/components/admin/AdminWorkflowGroupAssignment": pending('auto-scaffold — needs review'),
  "modules/workflow/components/admin/AdminWorkflowsPage": pending('auto-scaffold — needs review'),
  "modules/workflow/widgets/GroupSystemWorkflowsAssignmentDrawer": pending('auto-scaffold — needs review'),
  "modules/workflow/widgets/GroupSystemWorkflowsWidget": pending('auto-scaffold — needs review'),
  // <<< scaffold-insert >>>
} satisfies Record<GallerySurface, Coverage>

// ── Rollup counts (used by COVERAGE.md + the coverage report) ────────────────
export function coverageSummary() {
  const counts: Record<Coverage['kind'], number> = {
    page: 0,
    story: 0,
    via: 0,
    allow: 0,
    pending: 0,
  }
  for (const v of Object.values(GALLERY_COVERAGE) as Coverage[]) counts[v.kind]++
  const total = Object.keys(GALLERY_COVERAGE).length
  const covered = total - counts.pending
  return { total, covered, ...counts }
}
