/**
 * Gallery coverage registry — the ENFORCED gate.
 *
 * `GALLERY_COVERAGE` maps EVERY generated `GallerySurface` (see
 * galleryCoverage.generated.ts) to how the gallery covers it. Because the object
 * is `satisfies Record<GallerySurface, Coverage>`, a surface with no entry is a
 * COMPILE error, and a stale key (deleted file) is also a compile error.
 *
 * Coverage kinds:
 *   - page(id)    — this surface IS a seeded gallery page (see ALL_PAGES).
 *   - story(id)   — covered by a kit story section (see stories/).
 *   - via(id)     — rendered inside another covered surface (its page/story).
 *   - allow(why)  — genuinely non-visual (provider/context/pure-logic/null
 *                   render) — no visual entry needed; the reason is reviewed.
 *   - pending(why)— tracked TODO: accounted for, not yet given a visual entry.
 *
 * The tsc gate guarantees every surface is at least `pending`; the parity test
 * (gen-gallery-coverage.mjs --check) lists pending surfaces so they stay visible.
 */
import type { GallerySurface } from './galleryCoverage.generated'

/**
 * A surface's KIND drives its REQUIRED STATE SET (enforced by the coverage gate,
 * `gen-gallery-coverage.mjs --check`). A surface whose declared `states` miss its
 * kind's required set fails the gate.
 *
 *   data-page / table → loaded + empty + error   (most bugs live in empty/error)
 *   form              → empty + filled + invalid
 *   overlay           → open
 *   static / flow / via / nonvisual / pending → none required
 *
 * Escape hatch: a genuinely stateless surface uses `static`; a non-visual one
 * uses `nonvisual`; both opt out of the required-state gate with a reason.
 */
export type SurfaceKind =
  | 'data-page'
  | 'table'
  | 'form'
  | 'overlay'
  | 'static'
  | 'flow'
  | 'via'
  | 'nonvisual'
  | 'pending'

/** Data-states rendered by swapping the mock cassette (see mockApi `MockMode`). */
export type GalleryState =
  | 'loaded'
  | 'empty'
  | 'error'
  | 'delayed'
  | 'open'
  | 'filled'
  | 'invalid'

export interface Coverage {
  kind: SurfaceKind
  /** Declared states for this surface (each a screenshot combo). */
  states?: readonly GalleryState[]
  /** Reason for via / nonvisual / pending / static opt-outs. */
  reason?: string
}

/** Required state set per kind — the gate. Empty = no required states. */
export const REQUIRED_STATES: Record<SurfaceKind, readonly GalleryState[]> = {
  'data-page': ['loaded', 'empty', 'error'],
  table: ['loaded', 'empty', 'error'],
  form: ['empty', 'filled', 'invalid'],
  overlay: ['open'],
  static: [],
  flow: [],
  via: [],
  nonvisual: [],
  pending: [],
}

// Keep this object total over GallerySurface (the tsc gate). The node gate
// (`gen-gallery-coverage.mjs --check`) additionally enforces REQUIRED_STATES.
export const GALLERY_COVERAGE = {
  "components/ui/kit/accordion": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/alert": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/attachment": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/avatar": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/badge": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/button": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/card": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/checkbox": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/combobox": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/confirm": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/date-picker": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/descriptions": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/dialog": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/dialog-host": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/dropdown": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/empty": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/error-state": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/flex": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/form": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/image": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/input": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/input-number": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/layout": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/list": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/menu": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/multi-select": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/pagination": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/popover": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/progress": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/radio-group": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/result": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/scroll-area": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/segmented": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/section-header": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/select": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/separator": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/sheet": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/sidebar": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/skeleton": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/space": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/spinner": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/statistic": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/surface": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/switch": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/table": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/tabs": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/tag": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/textarea": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/theme": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/toast": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/tooltip": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/tree": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/typography": { kind: 'via', reason: 'kit-stories' },
  "components/ui/kit/upload": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/accordion": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/alert": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/alert-dialog": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/aspect-ratio": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/attachment": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/avatar": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/badge": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/breadcrumb": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/button": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/button-group": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/calendar": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/card": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/carousel": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/checkbox": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/collapsible": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/combobox": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/command": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/context-menu": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/dialog": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/drawer": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/dropdown-menu": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/empty": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/field": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/hover-card": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/input": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/input-group": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/input-otp": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/item": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/kbd": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/label": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/menubar": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/native-select": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/navigation-menu": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/pagination": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/popover": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/progress": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/radio-group": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/resizable": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/scroll-area": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/select": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/separator": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/sheet": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/sidebar": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/skeleton": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/slider": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/sonner": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/spinner": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/switch": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/table": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/tabs": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/textarea": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/toggle": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/toggle-group": { kind: 'via', reason: 'kit-stories' },
  "components/ui/shadcn/tooltip": { kind: 'via', reason: 'kit-stories' },
  "modules/app/SetupPage": { kind: 'flow', reason: 'auth/setup flow (no data grid)' },
  "modules/assistant/chat-extension/components/AssistantMenuItem": { kind: 'via', reason: 'rendered within the assistant module page' },
  "modules/assistant/chat-extension/components/AssistantSelector": { kind: 'via', reason: 'rendered within the assistant module page' },
  "modules/assistant/chat-extension/components/AssistantStatusChip": { kind: 'via', reason: 'rendered within the assistant module page' },
  "modules/assistant/chat-extension/extension": { kind: 'via', reason: 'rendered within the assistant module page' },
  "modules/assistant/components/AssistantFormDrawer": { kind: 'overlay', states: ['open', 'filled', 'invalid'] },
  "modules/assistant/pages/AssistantsSettings": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/assistant/pages/UserAssistantsSettings": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/auth-providers/AuthProvidersSettingsPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/auth-providers/components/AddProviderMenu": { kind: 'static', reason: 'dialog/modal — prop/context-driven open; verified via the e2e interaction suite' },
  "modules/auth-providers/components/AuthProviderEditDrawer": { kind: 'static', reason: 'overlay open-state — needs a live open-trigger context; verified via the e2e interaction suite' },
  "modules/auth-providers/components/AuthProvidersListSection": { kind: 'via', reason: 'rendered within the auth-providers module page' },
  "modules/auth/AuthCallbackPage": { kind: 'flow', reason: 'auth/setup flow (no data grid)' },
  "modules/auth/AuthGuard": { kind: 'nonvisual', reason: 'context/provider/listener/types' },
  "modules/auth/AuthPage": { kind: 'flow', reason: 'auth/setup flow (no data grid)' },
  "modules/auth/LinkAccountPage": { kind: 'flow', reason: 'auth/setup flow (no data grid)' },
  "modules/auth/LoginForm": { kind: 'via', reason: 'rendered within the auth module page' },
  "modules/auth/ProviderButtons": { kind: 'via', reason: 'rendered within the auth module page' },
  "modules/auth/RegisterForm": { kind: 'via', reason: 'rendered within the auth module page' },
  "modules/auth/SessionSettingsPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/chat/components/BranchNavigator": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/components/ChatInput": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/components/ChatMessage": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/components/ContentRenderer": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/components/ConversationCard": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/components/ConversationList": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/components/EditingMessageBanner": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/components/MessageActions": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/components/MessageList": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/components/ModelSelector": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/components/TextContent": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/components/TitleEditor": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/core/MessageContext": { kind: 'nonvisual', reason: 'context/provider/listener/types' },
  "modules/chat/core/components/ChatRightPanel": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/core/extensions/registry": { kind: 'nonvisual', reason: 'context/provider/listener/types' },
  "modules/chat/core/extensions/slots": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/core/extensions/utils": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/core/utils/StreamdownErrorBoundary": { kind: 'nonvisual', reason: 'context/provider/listener/types' },
  "modules/chat/core/utils/useStreamdownComponents": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/extensions/export/extension": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/extensions/keyboard/extension": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/extensions/syntax/extension": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/extensions/text/components/TextContent": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/extensions/text/components/TextInput": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/extensions/text/components/ThinkingContent": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/extensions/text/extension": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/extensions/title/extension": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/pages/ChatHistoryPage": { kind: 'via', reason: 'rendered within the chat module page' },
  "modules/chat/pages/ConversationPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/chat/pages/NewChatPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/chat/widgets/RecentConversationsWidget": { kind: 'via', reason: 'slot-widget in chat' },
  "modules/citations/components/CitationCard": { kind: 'via', reason: 'rendered within the citations module page' },
  "modules/citations/components/ImportCitationsModal": { kind: 'static', reason: 'dialog/modal — prop/context-driven open; verified via the e2e interaction suite' },
  "modules/citations/components/VerificationBadge": { kind: 'via', reason: 'rendered within the citations module page' },
  "modules/citations/pages/CitationsSettingsPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/citations/project-extension/components/ProjectBibliographyInlinePreview": { kind: 'via', reason: 'rendered within the citations module page' },
  "modules/citations/project-extension/components/ProjectBibliographyManagePanel": { kind: 'via', reason: 'rendered within the citations module page' },
  "modules/citations/project-extension/extension": { kind: 'via', reason: 'rendered within the citations module page' },
  "modules/code-sandbox/components/AvailableRootfsCard": { kind: 'via', reason: 'rendered within the code-sandbox module page' },
  "modules/code-sandbox/components/DownloadedRootfsCard": { kind: 'via', reason: 'rendered within the code-sandbox module page' },
  "modules/code-sandbox/components/RootfsVersionGroup": { kind: 'via', reason: 'rendered within the code-sandbox module page' },
  "modules/code-sandbox/components/SandboxResourceLimitsSection": { kind: 'via', reason: 'rendered within the code-sandbox module page' },
  "modules/code-sandbox/components/SandboxRootfsVersionsSection": { kind: 'via', reason: 'rendered within the code-sandbox module page' },
  "modules/code-sandbox/components/SandboxSettingsPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/code-sandbox/components/_rootfsShared": { kind: 'via', reason: 'rendered within the code-sandbox module page' },
  "modules/file-rag/components/sections/ChunkingSection": { kind: 'via', reason: 'rendered within the file-rag module page' },
  "modules/file-rag/components/sections/EmbeddingSection": { kind: 'via', reason: 'rendered within the file-rag module page' },
  "modules/file-rag/components/sections/EnableSection": { kind: 'via', reason: 'rendered within the file-rag module page' },
  "modules/file-rag/components/sections/FullTextSection": { kind: 'via', reason: 'rendered within the file-rag module page' },
  "modules/file-rag/components/sections/MaintenanceSection": { kind: 'via', reason: 'rendered within the file-rag module page' },
  "modules/file-rag/pages/FileRagAdminPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/file/chat-extension/components/FileAttachMenuItem": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/chat-extension/components/FilePreviewList": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/chat-extension/components/FileUploadArea": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/chat-extension/components/FileUploadButton": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/chat-extension/components/ImageContent": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/chat-extension/components/InlineFilePreview": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/chat-extension/components/MessageFilesView": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/chat-extension/extension": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/components/FileCard": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/components/FilePanel": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/components/FilePreviewDrawer": { kind: 'static', reason: 'file-preview drawer — needs a selected file with preview pages; verified via the e2e interaction suite' },
  "modules/file/components/FileVersionBar": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/project-extension/components/ProjectFilesInlinePreview": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/project-extension/components/ProjectFilesManagePanel": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/project-extension/extension": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/viewers/image/body": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/viewers/image/header": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/viewers/markdown/body": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/viewers/markdown/header": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/viewers/pdf/body": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/viewers/pdf/header": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/viewers/shared/RawCodeView": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/viewers/shared/chrome": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/viewers/tabular/DelimitedTable": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/viewers/tabular/XlsxBody": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/viewers/tabular/body": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/viewers/tabular/header": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/viewers/text/body": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/viewers/text/header": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/viewers/web/body": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/file/viewers/web/header": { kind: 'via', reason: 'rendered within the file module page' },
  "modules/hardware/HardwareMonitor": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/hardware/HardwareMonitorButton": { kind: 'via', reason: 'rendered within the hardware module page' },
  "modules/hardware/HardwareSettings": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/hub/HubPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/hub/modules/assistants/components/AssistantDetailsDrawer": { kind: 'static', reason: 'hub detail drawer — open-state needs a hub-catalog item; verified via the e2e interaction suite' },
  "modules/hub/modules/assistants/components/AssistantHubCard": { kind: 'via', reason: 'rendered within the hub module page' },
  "modules/hub/modules/assistants/components/AssistantsHubTab": { kind: 'via', reason: 'rendered within the hub module page' },
  "modules/hub/modules/installed/components/InstalledHubTab": { kind: 'via', reason: 'rendered within the hub module page' },
  "modules/hub/modules/llm-models/components/ModelDetailsDrawer": { kind: 'static', reason: 'hub detail drawer — open-state needs a hub-catalog item; verified via the e2e interaction suite' },
  "modules/hub/modules/llm-models/components/ModelHubCard": { kind: 'via', reason: 'rendered within the hub module page' },
  "modules/hub/modules/llm-models/components/ModelsHubTab": { kind: 'via', reason: 'rendered within the hub module page' },
  "modules/hub/modules/llm-models/hooks/useHubModelDownloadGate": { kind: 'via', reason: 'rendered within the hub module page' },
  "modules/hub/modules/mcp/components/McpServerDetailsDrawer": { kind: 'static', reason: 'hub detail drawer — open-state needs a hub-catalog item; verified via the e2e interaction suite' },
  "modules/hub/modules/mcp/components/McpServerHubCard": { kind: 'via', reason: 'rendered within the hub module page' },
  "modules/hub/modules/mcp/components/McpServersHubTab": { kind: 'via', reason: 'rendered within the hub module page' },
  "modules/hub/modules/skill/components/SkillDetailsDrawer": { kind: 'static', reason: 'hub detail drawer — open-state needs a hub-catalog item; verified via the e2e interaction suite' },
  "modules/hub/modules/skill/components/SkillHubCard": { kind: 'via', reason: 'rendered within the hub module page' },
  "modules/hub/modules/skill/components/SkillsHubTab": { kind: 'via', reason: 'rendered within the hub module page' },
  "modules/hub/modules/workflow/components/WorkflowDetailsDrawer": { kind: 'static', reason: 'hub detail drawer — open-state needs a hub-catalog item; verified via the e2e interaction suite' },
  "modules/hub/modules/workflow/components/WorkflowHubCard": { kind: 'via', reason: 'rendered within the hub module page' },
  "modules/hub/modules/workflow/components/WorkflowsHubTab": { kind: 'via', reason: 'rendered within the hub module page' },
  "modules/layouts/app-layout/AppLayout": { kind: 'via', reason: 'rendered within the layouts module page' },
  "modules/layouts/app-layout/components/Drawer": { kind: 'static', reason: 'the Drawer primitive itself — exercised by every wired drawer open-state above' },
  "modules/layouts/app-layout/components/HeaderBarContainer": { kind: 'via', reason: 'rendered within the layouts module page' },
  "modules/layouts/app-layout/components/LeftSidebar": { kind: 'via', reason: 'rendered within the layouts module page' },
  "modules/layouts/app-layout/components/ResizeHandle": { kind: 'via', reason: 'rendered within the layouts module page' },
  "modules/layouts/app-layout/components/SidebarHeaderSpacer": { kind: 'via', reason: 'rendered within the layouts module page' },
  "modules/layouts/app-layout/components/SidebarToggleButton": { kind: 'via', reason: 'rendered within the layouts module page' },
  "modules/layouts/blank/BlankLayout": { kind: 'via', reason: 'rendered within the layouts module page' },
  "modules/literature/chat-extension/extension": { kind: 'via', reason: 'rendered within the literature module page' },
  "modules/literature/components/LiteratureScreeningPanel": { kind: 'via', reason: 'rendered within the literature module page' },
  "modules/literature/components/LiteratureToolResultCard": { kind: 'via', reason: 'rendered within the literature module page' },
  "modules/literature/components/settings/LitSearchConnectorsSection": { kind: 'via', reason: 'rendered within the literature module page' },
  "modules/literature/components/settings/LitSearchGlobalSection": { kind: 'via', reason: 'rendered within the literature module page' },
  "modules/literature/components/settings/LitSearchSettingsPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/literature/components/settings/LitSearchUserKeysPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/llm-local-runtime/components/AvailableVersionsCard": { kind: 'via', reason: 'rendered within the llm-local-runtime module page' },
  "modules/llm-local-runtime/components/InstalledVersionsCard": { kind: 'via', reason: 'rendered within the llm-local-runtime module page' },
  "modules/llm-local-runtime/components/LiveLogsPanel": { kind: 'via', reason: 'rendered within the llm-local-runtime module page' },
  "modules/llm-local-runtime/components/RuntimeConfigCard": { kind: 'via', reason: 'rendered within the llm-local-runtime module page' },
  "modules/llm-local-runtime/components/RuntimeVersionCard": { kind: 'via', reason: 'rendered within the llm-local-runtime module page' },
  "modules/llm-local-runtime/components/RuntimeVersionSettings": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/llm-local-runtime/components/VersionModelsBlock": { kind: 'via', reason: 'rendered within the llm-local-runtime module page' },
  "modules/llm-local-runtime/components/_engineVersionsShared": { kind: 'via', reason: 'rendered within the llm-local-runtime module page' },
  "modules/llm-local-runtime/components/drawers/RuntimeDownloadDrawer": { kind: 'static', reason: 'model add/edit drawer — needs provider+model context; verified via the e2e interaction suite' },
  "modules/llm-provider/components/GroupLlmProvidersAssignmentDrawer": { kind: 'overlay', states: ['open'] },
  "modules/llm-provider/components/LlmModelDownloadNotifications": { kind: 'nonvisual', reason: 'context/provider/listener/types' },
  "modules/llm-provider/components/LlmModelsSection": { kind: 'via', reason: 'rendered within the llm-provider module page' },
  "modules/llm-provider/components/LlmProviderDrawer": { kind: 'overlay', states: ['open', 'filled', 'invalid'] },
  "modules/llm-provider/components/LlmProviderSettings": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/llm-provider/components/LocalProviderSettings": { kind: 'via', reason: 'rendered within the llm-provider module page' },
  "modules/llm-provider/components/ProviderGroupAssignmentCard": { kind: 'via', reason: 'rendered within the llm-provider module page' },
  "modules/llm-provider/components/ProviderHeader": { kind: 'via', reason: 'rendered within the llm-provider module page' },
  "modules/llm-provider/components/ProviderProxySettingsForm": { kind: 'via', reason: 'rendered within the llm-provider module page' },
  "modules/llm-provider/components/RemoteProviderSettings": { kind: 'via', reason: 'rendered within the llm-provider module page' },
  "modules/llm-provider/components/downloads/DownloadItem": { kind: 'via', reason: 'rendered within the llm-provider module page' },
  "modules/llm-provider/components/downloads/DownloadProgress": { kind: 'via', reason: 'rendered within the llm-provider module page' },
  "modules/llm-provider/components/downloads/DownloadsSection": { kind: 'via', reason: 'rendered within the llm-provider module page' },
  "modules/llm-provider/components/llm-models/AddLocalLlmModelDownloadDrawer": { kind: 'static', reason: 'model add/edit drawer — needs provider+model context; verified via the e2e interaction suite' },
  "modules/llm-provider/components/llm-models/AddLocalLlmModelUploadDrawer": { kind: 'static', reason: 'model add/edit drawer — needs provider+model context; verified via the e2e interaction suite' },
  "modules/llm-provider/components/llm-models/AddRemoteLlmModelDrawer": { kind: 'static', reason: 'model add/edit drawer — needs provider+model context; verified via the e2e interaction suite' },
  "modules/llm-provider/components/llm-models/EditLlmModelDrawer": { kind: 'static', reason: 'model add/edit drawer — needs provider+model context; verified via the e2e interaction suite' },
  "modules/llm-provider/components/llm-models/shared/LlmModelCapabilitiesSection": { kind: 'via', reason: 'rendered within the llm-provider module page' },
  "modules/llm-provider/components/llm-models/shared/LlmModelLlamaCppSettingsSection": { kind: 'via', reason: 'rendered within the llm-provider module page' },
  "modules/llm-provider/components/llm-models/shared/LlmModelMistralRsSettingsSection": { kind: 'via', reason: 'rendered within the llm-provider module page' },
  "modules/llm-provider/components/llm-models/shared/LlmModelParameterField": { kind: 'via', reason: 'rendered within the llm-provider module page' },
  "modules/llm-provider/components/llm-models/shared/LlmModelParametersSection": { kind: 'via', reason: 'rendered within the llm-provider module page' },
  "modules/llm-provider/components/llm-models/shared/LocalLlmModelCommonFields": { kind: 'via', reason: 'rendered within the llm-provider module page' },
  "modules/llm-provider/components/widgets/DownloadIndicatorWidget": { kind: 'via', reason: 'slot-widget in llm-provider' },
  "modules/llm-provider/constants": { kind: 'nonvisual', reason: 'context/provider/listener/types' },
  "modules/llm-provider/icons/DeepSeek": { kind: 'via', reason: 'rendered within the llm-provider module page' },
  "modules/llm-provider/icons/Mistral": { kind: 'via', reason: 'rendered within the llm-provider module page' },
  "modules/llm-provider/widgets/LLMProviderGroupWidget": { kind: 'via', reason: 'slot-widget in llm-provider' },
  "modules/llm-repository/components/LlmRepositoryDrawer": { kind: 'overlay', states: ['open', 'filled', 'invalid'] },
  "modules/llm-repository/components/LlmRepositorySettings": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/mcp/chat-extension/components/ElicitationFormContent": { kind: 'via', reason: 'rendered within the mcp module page' },
  "modules/mcp/chat-extension/components/McpInitializer": { kind: 'via', reason: 'rendered within the mcp module page' },
  "modules/mcp/chat-extension/components/McpMenuItem": { kind: 'via', reason: 'rendered within the mcp module page' },
  "modules/mcp/chat-extension/components/McpStatusRow": { kind: 'via', reason: 'rendered within the mcp module page' },
  "modules/mcp/chat-extension/components/ToolCallPendingApprovalCancelContent": { kind: 'via', reason: 'rendered within the mcp module page' },
  "modules/mcp/chat-extension/components/ToolCallPendingApprovalContent": { kind: 'via', reason: 'rendered within the mcp module page' },
  "modules/mcp/chat-extension/extension": { kind: 'via', reason: 'rendered within the mcp module page' },
  "modules/mcp/components/McpConfigModal": { kind: 'static', reason: 'dialog/modal — prop/context-driven open; verified via the e2e interaction suite' },
  "modules/mcp/components/common/KeyValueSecretEditor": { kind: 'via', reason: 'rendered within the mcp module page' },
  "modules/mcp/components/common/McpServerCard": { kind: 'via', reason: 'rendered within the mcp module page' },
  "modules/mcp/components/common/McpServerDrawer": { kind: 'static', reason: 'overlay open-state — needs a live open-trigger context; verified via the e2e interaction suite' },
  "modules/mcp/components/common/McpToolCallsTab": { kind: 'via', reason: 'rendered within the mcp module page' },
  "modules/mcp/components/common/connectionTestToast": { kind: 'via', reason: 'rendered within the mcp module page' },
  "modules/mcp/components/system/GroupSystemMcpServersAssignmentDrawer": { kind: 'overlay', states: ['open'] },
  "modules/mcp/components/system/McpServerGroupsAssignmentCard": { kind: 'via', reason: 'rendered within the mcp module page' },
  "modules/mcp/components/system/McpUserPolicyCard": { kind: 'via', reason: 'rendered within the mcp module page' },
  "modules/mcp/components/system/SystemMcpServersPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/mcp/components/user/McpServersSettings": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/mcp/project-extension/components/ProjectMcpSettingsPanel": { kind: 'via', reason: 'rendered within the mcp module page' },
  "modules/mcp/project-extension/extension": { kind: 'via', reason: 'rendered within the mcp module page' },
  "modules/mcp/widgets/GroupSystemMcpServersWidget": { kind: 'via', reason: 'slot-widget in mcp' },
  "modules/memory/chat-extension/components/MemoryStatusPill": { kind: 'via', reason: 'rendered within the memory module page' },
  "modules/memory/chat-extension/extension": { kind: 'via', reason: 'rendered within the memory module page' },
  "modules/memory/components/CoreMemoryBlocksEditor": { kind: 'via', reason: 'rendered within the memory module page' },
  "modules/memory/components/sections/AuditLogSection": { kind: 'via', reason: 'rendered within the memory module page' },
  "modules/memory/components/sections/CoreMemorySection": { kind: 'via', reason: 'rendered within the memory module page' },
  "modules/memory/components/sections/ExtractionSection": { kind: 'via', reason: 'rendered within the memory module page' },
  "modules/memory/components/sections/FullTextSearchSection": { kind: 'via', reason: 'rendered within the memory module page' },
  "modules/memory/components/sections/MemorySection": { kind: 'via', reason: 'rendered within the memory module page' },
  "modules/memory/components/sections/MyMemoriesSection": { kind: 'via', reason: 'rendered within the memory module page' },
  "modules/memory/components/sections/PreferencesSection": { kind: 'via', reason: 'rendered within the memory module page' },
  "modules/memory/components/sections/RebuildStatusSection": { kind: 'via', reason: 'rendered within the memory module page' },
  "modules/memory/components/sections/RetentionLimitsSection": { kind: 'via', reason: 'rendered within the memory module page' },
  "modules/memory/components/sections/SemanticSearchSection": { kind: 'via', reason: 'rendered within the memory module page' },
  "modules/memory/pages/MemoryAdminPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/memory/pages/MemorySettingsPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/onboarding/OnboardingPage": { kind: 'via', reason: 'rendered within the onboarding module page' },
  "modules/onboarding/OnboardingRedirect": { kind: 'via', reason: 'rendered within the onboarding module page' },
  "modules/onboarding/guides/getting-started/components/ApiKeysStep": { kind: 'via', reason: 'rendered within the onboarding module page' },
  "modules/onboarding/guides/getting-started/components/FinishStep": { kind: 'via', reason: 'rendered within the onboarding module page' },
  "modules/onboarding/guides/getting-started/components/McpServersStep": { kind: 'via', reason: 'rendered within the onboarding module page' },
  "modules/onboarding/guides/getting-started/components/MemorySetupStep": { kind: 'via', reason: 'rendered within the onboarding module page' },
  "modules/onboarding/guides/getting-started/components/WelcomeStep": { kind: 'via', reason: 'rendered within the onboarding module page' },
  "modules/profile/pages/ProfileSettingsPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/projects/chat-extension/components/ProjectConversationsList": { kind: 'via', reason: 'rendered within the projects module page' },
  "modules/projects/chat-extension/components/ProjectInlineChatInput": { kind: 'via', reason: 'rendered within the projects module page' },
  "modules/projects/chat-extension/extension": { kind: 'via', reason: 'rendered within the projects module page' },
  "modules/projects/components/AddToProjectModal": { kind: 'static', reason: 'dialog/modal — prop/context-driven open; verified via the e2e interaction suite' },
  "modules/projects/components/ProjectCard": { kind: 'via', reason: 'rendered within the projects module page' },
  "modules/projects/components/ProjectDefaultsForm": { kind: 'via', reason: 'rendered within the projects module page' },
  "modules/projects/components/ProjectFormDrawer": { kind: 'static', reason: 'overlay open-state — needs a live open-trigger context; verified via the e2e interaction suite' },
  "modules/projects/components/ProjectKnowledgeSection": { kind: 'via', reason: 'rendered within the projects module page' },
  "modules/projects/core/extensions/registry": { kind: 'nonvisual', reason: 'context/provider/listener/types' },
  "modules/projects/core/extensions/slots": { kind: 'via', reason: 'rendered within the projects module page' },
  "modules/projects/pages/ProjectDetailPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/projects/pages/ProjectsListPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/router/components/RouterComponent": { kind: 'via', reason: 'rendered within the router module page' },
  "modules/server-update/AboutSettings": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/server-update/ServerUpdateBanner": { kind: 'via', reason: 'rendered within the server-update module page' },
  "modules/settings-general/GeneralSettings": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/settings-general/components/ThemeSettings": { kind: 'via', reason: 'rendered within the settings-general module page' },
  "modules/settings/SettingsLayout": { kind: 'via', reason: 'rendered within the settings module page' },
  "modules/settings/SettingsPage": { kind: 'via', reason: 'rendered within the settings module page' },
  "modules/settings/components/AddButton": { kind: 'via', reason: 'rendered within the settings module page' },
  "modules/settings/components/SettingsFormActions": { kind: 'via', reason: 'rendered within the settings module page' },
  "modules/settings/components/SettingsPageContainer": { kind: 'via', reason: 'rendered within the settings module page' },
  "modules/skill/chat-extension/SkillMenuItem": { kind: 'via', reason: 'rendered within the skill module page' },
  "modules/skill/chat-extension/extension": { kind: 'via', reason: 'rendered within the skill module page' },
  "modules/skill/components/ConversationSkillsPanel": { kind: 'via', reason: 'rendered within the skill module page' },
  "modules/skill/components/ImportSkillDialog": { kind: 'static', reason: 'dialog/modal — prop/context-driven open; verified via the e2e interaction suite' },
  "modules/skill/components/SkillConversationDrawer": { kind: 'static', reason: 'overlay open-state — needs a live open-trigger context; verified via the e2e interaction suite' },
  "modules/skill/components/SkillDetailDrawer": { kind: 'static', reason: 'overlay open-state — needs a live open-trigger context; verified via the e2e interaction suite' },
  "modules/skill/components/SkillScopeBadge": { kind: 'via', reason: 'rendered within the skill module page' },
  "modules/skill/components/SkillsList": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/skill/components/admin/AdminSkillGroupAssignment": { kind: 'via', reason: 'rendered within the skill module page' },
  "modules/skill/components/admin/AdminSkillsPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/skill/widgets/GroupSystemSkillsAssignmentDrawer": { kind: 'overlay', states: ['open'] },
  "modules/skill/widgets/GroupSystemSkillsWidget": { kind: 'via', reason: 'slot-widget in skill' },
  "modules/summarization/chat-extension/components/SummarizationStatusPill": { kind: 'via', reason: 'rendered within the summarization module page' },
  "modules/summarization/chat-extension/components/SummaryBoundaryMarker": { kind: 'via', reason: 'rendered within the summarization module page' },
  "modules/summarization/chat-extension/extension": { kind: 'via', reason: 'rendered within the summarization module page' },
  "modules/summarization/components/sections/SummarizationSettingsSection": { kind: 'via', reason: 'rendered within the summarization module page' },
  "modules/summarization/pages/SummarizationAdminPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/user-llm-providers/UserLlmProvidersPage": { kind: 'via', reason: 'rendered within the user-llm-providers module page' },
  "modules/user-llm-providers/chat-extension/components/ModelSelector": { kind: 'via', reason: 'rendered within the user-llm-providers module page' },
  "modules/user-llm-providers/chat-extension/components/ProviderApiKeyModal": { kind: 'static', reason: 'dialog/modal — prop/context-driven open; verified via the e2e interaction suite' },
  "modules/user-llm-providers/chat-extension/extension": { kind: 'via', reason: 'rendered within the user-llm-providers module page' },
  "modules/user-profile/UserProfileWidget": { kind: 'via', reason: 'rendered within the user-profile module page' },
  "modules/user/components/PermissionsField": { kind: 'via', reason: 'rendered within the user module page' },
  "modules/user/components/group/EditUserGroupDrawer": { kind: 'overlay', states: ['open'] },
  "modules/user/components/group/GroupListItem": { kind: 'via', reason: 'rendered within the user module page' },
  "modules/user/components/group/GroupMembersDrawer": { kind: 'overlay', states: ['open'] },
  "modules/user/components/group/UserGroupsSettings": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/user/components/user/AssignGroupDrawer": { kind: 'overlay', states: ['open'] },
  "modules/user/components/user/CreateUserDrawer": { kind: 'overlay', states: ['open', 'filled', 'invalid'] },
  "modules/user/components/user/EditUserDrawer": { kind: 'overlay', states: ['open', 'filled', 'invalid'] },
  "modules/user/components/user/ResetPasswordDrawer": { kind: 'overlay', states: ['open'] },
  "modules/user/components/user/UserGroupsDrawer": { kind: 'overlay', states: ['open'] },
  "modules/user/components/user/UserRegistrationSettings": { kind: 'via', reason: 'rendered within the user module page' },
  "modules/user/components/user/UsersSettings": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/web-search/components/WebSearchGlobalSection": { kind: 'via', reason: 'rendered within the web-search module page' },
  "modules/web-search/components/WebSearchProvidersSection": { kind: 'via', reason: 'rendered within the web-search module page' },
  "modules/web-search/components/WebSearchSettingsPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/web-search/components/WebSearchUserKeysPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/workflow/chat-extension/components/WorkflowWorkspaceRunCard": { kind: 'via', reason: 'rendered within the workflow module page' },
  "modules/workflow/chat-extension/extension": { kind: 'via', reason: 'rendered within the workflow module page' },
  "modules/workflow/components/DryRunPreviewDialog": { kind: 'static', reason: 'dialog/modal — prop/context-driven open; verified via the e2e interaction suite' },
  "modules/workflow/components/EditableArrayTable": { kind: 'via', reason: 'rendered within the workflow module page' },
  "modules/workflow/components/ImportWorkflowDialog": { kind: 'static', reason: 'dialog/modal — prop/context-driven open; verified via the e2e interaction suite' },
  "modules/workflow/components/StepArtifacts": { kind: 'via', reason: 'rendered within the workflow module page' },
  "modules/workflow/components/StepLogExpander": { kind: 'via', reason: 'rendered within the workflow module page' },
  "modules/workflow/components/StepOutputExpander": { kind: 'via', reason: 'rendered within the workflow module page' },
  "modules/workflow/components/WorkflowDetailDrawer": { kind: 'static', reason: 'overlay open-state — needs a live open-trigger context; verified via the e2e interaction suite' },
  "modules/workflow/components/WorkflowElicitForm": { kind: 'via', reason: 'rendered within the workflow module page' },
  "modules/workflow/components/WorkflowRunDialog": { kind: 'static', reason: 'dialog/modal — prop/context-driven open; verified via the e2e interaction suite' },
  "modules/workflow/components/WorkflowRunProgressView": { kind: 'via', reason: 'rendered within the workflow module page' },
  "modules/workflow/components/WorkflowRunsList": { kind: 'via', reason: 'rendered within the workflow module page' },
  "modules/workflow/components/WorkflowScopeBadge": { kind: 'via', reason: 'rendered within the workflow module page' },
  "modules/workflow/components/WorkflowTestsPanel": { kind: 'via', reason: 'rendered within the workflow module page' },
  "modules/workflow/components/WorkflowsList": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/workflow/components/admin/AdminWorkflowGroupAssignment": { kind: 'via', reason: 'rendered within the workflow module page' },
  "modules/workflow/components/admin/AdminWorkflowsPage": { kind: 'data-page', states: ['loaded', 'empty', 'error'] },
  "modules/workflow/widgets/GroupSystemWorkflowsAssignmentDrawer": { kind: 'overlay', states: ['open'] },
  "modules/workflow/widgets/GroupSystemWorkflowsWidget": { kind: 'via', reason: 'slot-widget in workflow' },
  // <<< scaffold-insert >>>
} satisfies Record<GallerySurface, Coverage>

// ── Rollup counts (used by COVERAGE.md + the coverage report) ────────────────
export function coverageSummary() {
  const counts = {} as Record<SurfaceKind, number>
  for (const v of Object.values(GALLERY_COVERAGE) as Coverage[]) {
    counts[v.kind] = (counts[v.kind] ?? 0) + 1
  }
  const total = Object.keys(GALLERY_COVERAGE).length
  const covered = total - (counts.pending ?? 0)
  return { total, covered, ...counts }
}
