/**
 * Gallery coverage registry — the ENFORCED gate.
 *
 * `GALLERY_COVERAGE` maps EVERY generated `GallerySurface` (see
 * galleryCoverage.generated.ts) to how the gallery covers it. Because the object
 * is `satisfies Record<GallerySurface, Coverage>`, a surface with no entry is a
 * COMPILE error, and a stale key (deleted file) is also a compile error.
 *
 * Coverage kinds:
 *   - page(id)    — this surface IS a seeded gallery page (see ALL_PAGES).
 *   - story(id)   — covered by a kit story section (see stories/).
 *   - via(id)     — rendered inside another covered surface (its page/story).
 *   - allow(why)  — genuinely non-visual (provider/context/pure-logic/null
 *                   render) — no visual entry needed; the reason is reviewed.
 *   - pending(why)— tracked TODO: accounted for, not yet given a visual entry.
 *
 * The tsc gate guarantees every surface is at least `pending`; the parity test
 * (gen-gallery-coverage.mjs --check) lists pending surfaces so they stay visible.
 */
import type { GallerySurface } from './galleryCoverage.generated'

export type Coverage =
  | { kind: 'page'; pageId: string }
  | { kind: 'story'; storyId: string }
  | { kind: 'via'; surface: string }
  | { kind: 'allow'; reason: string }
  | { kind: 'pending'; reason: string }

export const page = (pageId: string): Coverage => ({ kind: 'page', pageId })
export const story = (storyId: string): Coverage => ({ kind: 'story', storyId })
export const via = (surface: string): Coverage => ({ kind: 'via', surface })
export const allow = (reason: string): Coverage => ({ kind: 'allow', reason })
export const pending = (reason: string): Coverage => ({ kind: 'pending', reason })

// Keep this object total over GallerySurface. The `// <<< scaffold-insert >>>`
// marker is where `gen:gallery-coverage --scaffold` appends missing surfaces as
// `pending(...)`; refine each into page/story/via/allow as coverage lands.
export const GALLERY_COVERAGE = {
  "components/ui/kit/accordion": via('kit-stories'),
  "components/ui/kit/alert": via('kit-stories'),
  "components/ui/kit/attachment": via('kit-stories'),
  "components/ui/kit/avatar": via('kit-stories'),
  "components/ui/kit/badge": via('kit-stories'),
  "components/ui/kit/button": via('kit-stories'),
  "components/ui/kit/card": via('kit-stories'),
  "components/ui/kit/checkbox": via('kit-stories'),
  "components/ui/kit/combobox": via('kit-stories'),
  "components/ui/kit/confirm": via('kit-stories'),
  "components/ui/kit/date-picker": via('kit-stories'),
  "components/ui/kit/descriptions": via('kit-stories'),
  "components/ui/kit/dialog": via('kit-stories'),
  "components/ui/kit/dialog-host": via('kit-stories'),
  "components/ui/kit/dropdown": via('kit-stories'),
  "components/ui/kit/empty": via('kit-stories'),
  "components/ui/kit/flex": via('kit-stories'),
  "components/ui/kit/form": via('kit-stories'),
  "components/ui/kit/image": via('kit-stories'),
  "components/ui/kit/input": via('kit-stories'),
  "components/ui/kit/input-number": via('kit-stories'),
  "components/ui/kit/layout": via('kit-stories'),
  "components/ui/kit/list": via('kit-stories'),
  "components/ui/kit/menu": via('kit-stories'),
  "components/ui/kit/multi-select": via('kit-stories'),
  "components/ui/kit/pagination": via('kit-stories'),
  "components/ui/kit/popover": via('kit-stories'),
  "components/ui/kit/progress": via('kit-stories'),
  "components/ui/kit/radio-group": via('kit-stories'),
  "components/ui/kit/result": via('kit-stories'),
  "components/ui/kit/scroll-area": via('kit-stories'),
  "components/ui/kit/segmented": via('kit-stories'),
  "components/ui/kit/select": via('kit-stories'),
  "components/ui/kit/separator": via('kit-stories'),
  "components/ui/kit/sheet": via('kit-stories'),
  "components/ui/kit/sidebar": via('kit-stories'),
  "components/ui/kit/skeleton": via('kit-stories'),
  "components/ui/kit/space": via('kit-stories'),
  "components/ui/kit/spinner": via('kit-stories'),
  "components/ui/kit/statistic": via('kit-stories'),
  "components/ui/kit/surface": via('kit-stories'),
  "components/ui/kit/switch": via('kit-stories'),
  "components/ui/kit/table": via('kit-stories'),
  "components/ui/kit/tabs": via('kit-stories'),
  "components/ui/kit/tag": via('kit-stories'),
  "components/ui/kit/textarea": via('kit-stories'),
  "components/ui/kit/theme": via('kit-stories'),
  "components/ui/kit/toast": via('kit-stories'),
  "components/ui/kit/tooltip": via('kit-stories'),
  "components/ui/kit/tree": via('kit-stories'),
  "components/ui/kit/typography": via('kit-stories'),
  "components/ui/kit/upload": via('kit-stories'),
  "components/ui/shadcn/accordion": via('kit-stories'),
  "components/ui/shadcn/alert": via('kit-stories'),
  "components/ui/shadcn/alert-dialog": via('kit-stories'),
  "components/ui/shadcn/aspect-ratio": via('kit-stories'),
  "components/ui/shadcn/attachment": via('kit-stories'),
  "components/ui/shadcn/avatar": via('kit-stories'),
  "components/ui/shadcn/badge": via('kit-stories'),
  "components/ui/shadcn/breadcrumb": via('kit-stories'),
  "components/ui/shadcn/button": via('kit-stories'),
  "components/ui/shadcn/button-group": via('kit-stories'),
  "components/ui/shadcn/calendar": via('kit-stories'),
  "components/ui/shadcn/card": via('kit-stories'),
  "components/ui/shadcn/carousel": via('kit-stories'),
  "components/ui/shadcn/checkbox": via('kit-stories'),
  "components/ui/shadcn/collapsible": via('kit-stories'),
  "components/ui/shadcn/combobox": via('kit-stories'),
  "components/ui/shadcn/command": via('kit-stories'),
  "components/ui/shadcn/context-menu": via('kit-stories'),
  "components/ui/shadcn/dialog": via('kit-stories'),
  "components/ui/shadcn/drawer": via('kit-stories'),
  "components/ui/shadcn/dropdown-menu": via('kit-stories'),
  "components/ui/shadcn/empty": via('kit-stories'),
  "components/ui/shadcn/field": via('kit-stories'),
  "components/ui/shadcn/hover-card": via('kit-stories'),
  "components/ui/shadcn/input": via('kit-stories'),
  "components/ui/shadcn/input-group": via('kit-stories'),
  "components/ui/shadcn/input-otp": via('kit-stories'),
  "components/ui/shadcn/item": via('kit-stories'),
  "components/ui/shadcn/kbd": via('kit-stories'),
  "components/ui/shadcn/label": via('kit-stories'),
  "components/ui/shadcn/menubar": via('kit-stories'),
  "components/ui/shadcn/native-select": via('kit-stories'),
  "components/ui/shadcn/navigation-menu": via('kit-stories'),
  "components/ui/shadcn/pagination": via('kit-stories'),
  "components/ui/shadcn/popover": via('kit-stories'),
  "components/ui/shadcn/progress": via('kit-stories'),
  "components/ui/shadcn/radio-group": via('kit-stories'),
  "components/ui/shadcn/resizable": via('kit-stories'),
  "components/ui/shadcn/scroll-area": via('kit-stories'),
  "components/ui/shadcn/select": via('kit-stories'),
  "components/ui/shadcn/separator": via('kit-stories'),
  "components/ui/shadcn/sheet": via('kit-stories'),
  "components/ui/shadcn/sidebar": via('kit-stories'),
  "components/ui/shadcn/skeleton": via('kit-stories'),
  "components/ui/shadcn/slider": via('kit-stories'),
  "components/ui/shadcn/sonner": via('kit-stories'),
  "components/ui/shadcn/spinner": via('kit-stories'),
  "components/ui/shadcn/switch": via('kit-stories'),
  "components/ui/shadcn/table": via('kit-stories'),
  "components/ui/shadcn/tabs": via('kit-stories'),
  "components/ui/shadcn/textarea": via('kit-stories'),
  "components/ui/shadcn/toggle": via('kit-stories'),
  "components/ui/shadcn/toggle-group": via('kit-stories'),
  "components/ui/shadcn/tooltip": via('kit-stories'),
  "modules/app/SetupPage": page("modules/app/SetupPage"),
  "modules/assistant/chat-extension/components/AssistantMenuItem": via('rendered within the assistant module page'),
  "modules/assistant/chat-extension/components/AssistantSelector": via('rendered within the assistant module page'),
  "modules/assistant/chat-extension/components/AssistantStatusChip": via('rendered within the assistant module page'),
  "modules/assistant/chat-extension/extension": via('rendered within the assistant module page'),
  "modules/assistant/components/AssistantFormDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/assistant/pages/AssistantsSettings": page("modules/assistant/pages/AssistantsSettings"),
  "modules/assistant/pages/UserAssistantsSettings": page("modules/assistant/pages/UserAssistantsSettings"),
  "modules/auth-providers/AuthProvidersSettingsPage": page("modules/auth-providers/AuthProvidersSettingsPage"),
  "modules/auth-providers/components/AddProviderMenu": pending('interaction-only — needs an open-state gallery entry'),
  "modules/auth-providers/components/AuthProviderEditDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/auth-providers/components/AuthProvidersListSection": via('rendered within the auth-providers module page'),
  "modules/auth/AuthCallbackPage": page("modules/auth/AuthCallbackPage"),
  "modules/auth/AuthGuard": allow('non-visual — context/provider/listener/types'),
  "modules/auth/AuthPage": page("modules/auth/AuthPage"),
  "modules/auth/LinkAccountPage": page("modules/auth/LinkAccountPage"),
  "modules/auth/LoginForm": via('rendered within the auth module page'),
  "modules/auth/ProviderButtons": via('rendered within the auth module page'),
  "modules/auth/RegisterForm": via('rendered within the auth module page'),
  "modules/auth/SessionSettingsPage": page("modules/auth/SessionSettingsPage"),
  "modules/chat/components/BranchNavigator": via('rendered within the chat module page'),
  "modules/chat/components/ChatInput": via('rendered within the chat module page'),
  "modules/chat/components/ChatMessage": via('rendered within the chat module page'),
  "modules/chat/components/ContentRenderer": via('rendered within the chat module page'),
  "modules/chat/components/ConversationCard": via('rendered within the chat module page'),
  "modules/chat/components/ConversationList": via('rendered within the chat module page'),
  "modules/chat/components/EditingMessageBanner": via('rendered within the chat module page'),
  "modules/chat/components/MessageActions": via('rendered within the chat module page'),
  "modules/chat/components/MessageList": via('rendered within the chat module page'),
  "modules/chat/components/ModelSelector": via('rendered within the chat module page'),
  "modules/chat/components/TextContent": via('rendered within the chat module page'),
  "modules/chat/components/TitleEditor": via('rendered within the chat module page'),
  "modules/chat/core/MessageContext": allow('non-visual — context/provider/listener/types'),
  "modules/chat/core/components/ChatRightPanel": via('rendered within the chat module page'),
  "modules/chat/core/extensions/registry": allow('non-visual — context/provider/listener/types'),
  "modules/chat/core/extensions/slots": via('rendered within the chat module page'),
  "modules/chat/core/extensions/utils": via('rendered within the chat module page'),
  "modules/chat/core/utils/StreamdownErrorBoundary": allow('non-visual — context/provider/listener/types'),
  "modules/chat/core/utils/useStreamdownComponents": via('rendered within the chat module page'),
  "modules/chat/extensions/export/extension": via('rendered within the chat module page'),
  "modules/chat/extensions/keyboard/extension": via('rendered within the chat module page'),
  "modules/chat/extensions/syntax/extension": via('rendered within the chat module page'),
  "modules/chat/extensions/text/components/TextContent": via('rendered within the chat module page'),
  "modules/chat/extensions/text/components/TextInput": via('rendered within the chat module page'),
  "modules/chat/extensions/text/components/ThinkingContent": via('rendered within the chat module page'),
  "modules/chat/extensions/text/extension": via('rendered within the chat module page'),
  "modules/chat/extensions/title/extension": via('rendered within the chat module page'),
  "modules/chat/pages/ChatHistoryPage": via('rendered within the chat module page'),
  "modules/chat/pages/ConversationPage": via('rendered within the chat module page'),
  "modules/chat/pages/NewChatPage": page("modules/chat/pages/NewChatPage"),
  "modules/chat/widgets/RecentConversationsWidget": via('slot-widget in chat'),
  "modules/citations/components/CitationCard": via('rendered within the citations module page'),
  "modules/citations/components/ImportCitationsModal": pending('interaction-only — needs an open-state gallery entry'),
  "modules/citations/components/VerificationBadge": via('rendered within the citations module page'),
  "modules/citations/pages/CitationsSettingsPage": page("modules/citations/pages/CitationsSettingsPage"),
  "modules/citations/project-extension/components/ProjectBibliographyInlinePreview": via('rendered within the citations module page'),
  "modules/citations/project-extension/components/ProjectBibliographyManagePanel": via('rendered within the citations module page'),
  "modules/citations/project-extension/extension": via('rendered within the citations module page'),
  "modules/code-sandbox/components/AvailableRootfsCard": via('rendered within the code-sandbox module page'),
  "modules/code-sandbox/components/DownloadedRootfsCard": via('rendered within the code-sandbox module page'),
  "modules/code-sandbox/components/RootfsVersionGroup": via('rendered within the code-sandbox module page'),
  "modules/code-sandbox/components/SandboxResourceLimitsSection": via('rendered within the code-sandbox module page'),
  "modules/code-sandbox/components/SandboxRootfsVersionsSection": via('rendered within the code-sandbox module page'),
  "modules/code-sandbox/components/SandboxSettingsPage": page("modules/code-sandbox/components/SandboxSettingsPage"),
  "modules/code-sandbox/components/_rootfsShared": via('rendered within the code-sandbox module page'),
  "modules/file-rag/components/sections/ChunkingSection": via('rendered within the file-rag module page'),
  "modules/file-rag/components/sections/EmbeddingSection": via('rendered within the file-rag module page'),
  "modules/file-rag/components/sections/EnableSection": via('rendered within the file-rag module page'),
  "modules/file-rag/components/sections/FullTextSection": via('rendered within the file-rag module page'),
  "modules/file-rag/components/sections/MaintenanceSection": via('rendered within the file-rag module page'),
  "modules/file-rag/pages/FileRagAdminPage": page("modules/file-rag/pages/FileRagAdminPage"),
  "modules/file/chat-extension/components/FileAttachMenuItem": via('rendered within the file module page'),
  "modules/file/chat-extension/components/FilePreviewList": via('rendered within the file module page'),
  "modules/file/chat-extension/components/FileUploadArea": via('rendered within the file module page'),
  "modules/file/chat-extension/components/FileUploadButton": via('rendered within the file module page'),
  "modules/file/chat-extension/components/ImageContent": via('rendered within the file module page'),
  "modules/file/chat-extension/components/InlineFilePreview": via('rendered within the file module page'),
  "modules/file/chat-extension/components/MessageFilesView": via('rendered within the file module page'),
  "modules/file/chat-extension/extension": via('rendered within the file module page'),
  "modules/file/components/FileCard": via('rendered within the file module page'),
  "modules/file/components/FilePanel": via('rendered within the file module page'),
  "modules/file/components/FilePreviewDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/file/components/FileVersionBar": via('rendered within the file module page'),
  "modules/file/project-extension/components/ProjectFilesInlinePreview": via('rendered within the file module page'),
  "modules/file/project-extension/components/ProjectFilesManagePanel": via('rendered within the file module page'),
  "modules/file/project-extension/extension": via('rendered within the file module page'),
  "modules/file/viewers/image/body": via('rendered within the file module page'),
  "modules/file/viewers/image/header": via('rendered within the file module page'),
  "modules/file/viewers/markdown/body": via('rendered within the file module page'),
  "modules/file/viewers/markdown/header": via('rendered within the file module page'),
  "modules/file/viewers/pdf/body": via('rendered within the file module page'),
  "modules/file/viewers/pdf/header": via('rendered within the file module page'),
  "modules/file/viewers/shared/RawCodeView": via('rendered within the file module page'),
  "modules/file/viewers/shared/chrome": via('rendered within the file module page'),
  "modules/file/viewers/tabular/DelimitedTable": via('rendered within the file module page'),
  "modules/file/viewers/tabular/XlsxBody": via('rendered within the file module page'),
  "modules/file/viewers/tabular/body": via('rendered within the file module page'),
  "modules/file/viewers/tabular/header": via('rendered within the file module page'),
  "modules/file/viewers/text/body": via('rendered within the file module page'),
  "modules/file/viewers/text/header": via('rendered within the file module page'),
  "modules/file/viewers/web/body": via('rendered within the file module page'),
  "modules/file/viewers/web/header": via('rendered within the file module page'),
  "modules/hardware/HardwareMonitor": page("modules/hardware/HardwareMonitor"),
  "modules/hardware/HardwareMonitorButton": via('rendered within the hardware module page'),
  "modules/hardware/HardwareSettings": page("modules/hardware/HardwareSettings"),
  "modules/hub/HubPage": page("modules/hub/HubPage"),
  "modules/hub/modules/assistants/components/AssistantDetailsDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/hub/modules/assistants/components/AssistantHubCard": via('rendered within the hub module page'),
  "modules/hub/modules/assistants/components/AssistantsHubTab": via('rendered within the hub module page'),
  "modules/hub/modules/installed/components/InstalledHubTab": via('rendered within the hub module page'),
  "modules/hub/modules/llm-models/components/ModelDetailsDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/hub/modules/llm-models/components/ModelHubCard": via('rendered within the hub module page'),
  "modules/hub/modules/llm-models/components/ModelsHubTab": via('rendered within the hub module page'),
  "modules/hub/modules/llm-models/hooks/useHubModelDownloadGate": via('rendered within the hub module page'),
  "modules/hub/modules/mcp/components/McpServerDetailsDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/hub/modules/mcp/components/McpServerHubCard": via('rendered within the hub module page'),
  "modules/hub/modules/mcp/components/McpServersHubTab": via('rendered within the hub module page'),
  "modules/hub/modules/skill/components/SkillDetailsDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/hub/modules/skill/components/SkillHubCard": via('rendered within the hub module page'),
  "modules/hub/modules/skill/components/SkillsHubTab": via('rendered within the hub module page'),
  "modules/hub/modules/workflow/components/WorkflowDetailsDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/hub/modules/workflow/components/WorkflowHubCard": via('rendered within the hub module page'),
  "modules/hub/modules/workflow/components/WorkflowsHubTab": via('rendered within the hub module page'),
  "modules/layouts/app-layout/AppLayout": via('rendered within the layouts module page'),
  "modules/layouts/app-layout/components/Drawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/layouts/app-layout/components/HeaderBarContainer": via('rendered within the layouts module page'),
  "modules/layouts/app-layout/components/LeftSidebar": via('rendered within the layouts module page'),
  "modules/layouts/app-layout/components/ResizeHandle": via('rendered within the layouts module page'),
  "modules/layouts/app-layout/components/SidebarHeaderSpacer": via('rendered within the layouts module page'),
  "modules/layouts/app-layout/components/SidebarToggleButton": via('rendered within the layouts module page'),
  "modules/layouts/blank/BlankLayout": via('rendered within the layouts module page'),
  "modules/literature/chat-extension/extension": via('rendered within the literature module page'),
  "modules/literature/components/LiteratureScreeningPanel": via('rendered within the literature module page'),
  "modules/literature/components/LiteratureToolResultCard": via('rendered within the literature module page'),
  "modules/literature/components/settings/LitSearchConnectorsSection": via('rendered within the literature module page'),
  "modules/literature/components/settings/LitSearchGlobalSection": via('rendered within the literature module page'),
  "modules/literature/components/settings/LitSearchSettingsPage": page("modules/literature/components/settings/LitSearchSettingsPage"),
  "modules/literature/components/settings/LitSearchUserKeysPage": page("modules/literature/components/settings/LitSearchUserKeysPage"),
  "modules/llm-local-runtime/components/AvailableVersionsCard": via('rendered within the llm-local-runtime module page'),
  "modules/llm-local-runtime/components/InstalledVersionsCard": via('rendered within the llm-local-runtime module page'),
  "modules/llm-local-runtime/components/LiveLogsPanel": via('rendered within the llm-local-runtime module page'),
  "modules/llm-local-runtime/components/RuntimeConfigCard": via('rendered within the llm-local-runtime module page'),
  "modules/llm-local-runtime/components/RuntimeVersionCard": via('rendered within the llm-local-runtime module page'),
  "modules/llm-local-runtime/components/RuntimeVersionSettings": page("modules/llm-local-runtime/components/RuntimeVersionSettings"),
  "modules/llm-local-runtime/components/VersionModelsBlock": via('rendered within the llm-local-runtime module page'),
  "modules/llm-local-runtime/components/_engineVersionsShared": via('rendered within the llm-local-runtime module page'),
  "modules/llm-local-runtime/components/drawers/RuntimeDownloadDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/llm-provider/components/GroupLlmProvidersAssignmentDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/llm-provider/components/LlmModelDownloadNotifications": allow('non-visual — context/provider/listener/types'),
  "modules/llm-provider/components/LlmModelsSection": via('rendered within the llm-provider module page'),
  "modules/llm-provider/components/LlmProviderDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/llm-provider/components/LlmProviderSettings": page("modules/llm-provider/components/LlmProviderSettings"),
  "modules/llm-provider/components/LocalProviderSettings": via('rendered within the llm-provider module page'),
  "modules/llm-provider/components/ProviderGroupAssignmentCard": via('rendered within the llm-provider module page'),
  "modules/llm-provider/components/ProviderHeader": via('rendered within the llm-provider module page'),
  "modules/llm-provider/components/ProviderProxySettingsForm": via('rendered within the llm-provider module page'),
  "modules/llm-provider/components/RemoteProviderSettings": via('rendered within the llm-provider module page'),
  "modules/llm-provider/components/downloads/DownloadItem": via('rendered within the llm-provider module page'),
  "modules/llm-provider/components/downloads/DownloadProgress": via('rendered within the llm-provider module page'),
  "modules/llm-provider/components/downloads/DownloadsSection": via('rendered within the llm-provider module page'),
  "modules/llm-provider/components/llm-models/AddLocalLlmModelDownloadDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/llm-provider/components/llm-models/AddLocalLlmModelUploadDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/llm-provider/components/llm-models/AddRemoteLlmModelDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/llm-provider/components/llm-models/EditLlmModelDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/llm-provider/components/llm-models/shared/LlmModelCapabilitiesSection": via('rendered within the llm-provider module page'),
  "modules/llm-provider/components/llm-models/shared/LlmModelLlamaCppSettingsSection": via('rendered within the llm-provider module page'),
  "modules/llm-provider/components/llm-models/shared/LlmModelMistralRsSettingsSection": via('rendered within the llm-provider module page'),
  "modules/llm-provider/components/llm-models/shared/LlmModelParameterField": via('rendered within the llm-provider module page'),
  "modules/llm-provider/components/llm-models/shared/LlmModelParametersSection": via('rendered within the llm-provider module page'),
  "modules/llm-provider/components/llm-models/shared/LocalLlmModelCommonFields": via('rendered within the llm-provider module page'),
  "modules/llm-provider/components/widgets/DownloadIndicatorWidget": via('slot-widget in llm-provider'),
  "modules/llm-provider/constants": allow('non-visual — context/provider/listener/types'),
  "modules/llm-provider/icons/DeepSeek": via('rendered within the llm-provider module page'),
  "modules/llm-provider/icons/Mistral": via('rendered within the llm-provider module page'),
  "modules/llm-provider/widgets/LLMProviderGroupWidget": via('slot-widget in llm-provider'),
  "modules/llm-repository/components/LlmRepositoryDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/llm-repository/components/LlmRepositorySettings": page("modules/llm-repository/components/LlmRepositorySettings"),
  "modules/mcp/chat-extension/components/ElicitationFormContent": via('rendered within the mcp module page'),
  "modules/mcp/chat-extension/components/McpInitializer": via('rendered within the mcp module page'),
  "modules/mcp/chat-extension/components/McpMenuItem": via('rendered within the mcp module page'),
  "modules/mcp/chat-extension/components/McpStatusRow": via('rendered within the mcp module page'),
  "modules/mcp/chat-extension/components/ToolCallPendingApprovalCancelContent": via('rendered within the mcp module page'),
  "modules/mcp/chat-extension/components/ToolCallPendingApprovalContent": via('rendered within the mcp module page'),
  "modules/mcp/chat-extension/extension": via('rendered within the mcp module page'),
  "modules/mcp/components/McpConfigModal": pending('interaction-only — needs an open-state gallery entry'),
  "modules/mcp/components/common/KeyValueSecretEditor": via('rendered within the mcp module page'),
  "modules/mcp/components/common/McpServerCard": via('rendered within the mcp module page'),
  "modules/mcp/components/common/McpServerDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/mcp/components/common/McpToolCallsTab": via('rendered within the mcp module page'),
  "modules/mcp/components/common/connectionTestToast": via('rendered within the mcp module page'),
  "modules/mcp/components/system/GroupSystemMcpServersAssignmentDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/mcp/components/system/McpServerGroupsAssignmentCard": via('rendered within the mcp module page'),
  "modules/mcp/components/system/McpUserPolicyCard": via('rendered within the mcp module page'),
  "modules/mcp/components/system/SystemMcpServersPage": page("modules/mcp/components/system/SystemMcpServersPage"),
  "modules/mcp/components/user/McpServersSettings": page("modules/mcp/components/user/McpServersSettings"),
  "modules/mcp/project-extension/components/ProjectMcpSettingsPanel": via('rendered within the mcp module page'),
  "modules/mcp/project-extension/extension": via('rendered within the mcp module page'),
  "modules/mcp/widgets/GroupSystemMcpServersWidget": via('slot-widget in mcp'),
  "modules/memory/chat-extension/components/MemoryStatusPill": via('rendered within the memory module page'),
  "modules/memory/chat-extension/extension": via('rendered within the memory module page'),
  "modules/memory/components/CoreMemoryBlocksEditor": via('rendered within the memory module page'),
  "modules/memory/components/sections/AuditLogSection": via('rendered within the memory module page'),
  "modules/memory/components/sections/CoreMemorySection": via('rendered within the memory module page'),
  "modules/memory/components/sections/ExtractionSection": via('rendered within the memory module page'),
  "modules/memory/components/sections/FullTextSearchSection": via('rendered within the memory module page'),
  "modules/memory/components/sections/MemorySection": via('rendered within the memory module page'),
  "modules/memory/components/sections/MyMemoriesSection": via('rendered within the memory module page'),
  "modules/memory/components/sections/PreferencesSection": via('rendered within the memory module page'),
  "modules/memory/components/sections/RebuildStatusSection": via('rendered within the memory module page'),
  "modules/memory/components/sections/RetentionLimitsSection": via('rendered within the memory module page'),
  "modules/memory/components/sections/SemanticSearchSection": via('rendered within the memory module page'),
  "modules/memory/pages/MemoryAdminPage": page("modules/memory/pages/MemoryAdminPage"),
  "modules/memory/pages/MemorySettingsPage": page("modules/memory/pages/MemorySettingsPage"),
  "modules/onboarding/OnboardingPage": via('rendered within the onboarding module page'),
  "modules/onboarding/OnboardingRedirect": via('rendered within the onboarding module page'),
  "modules/onboarding/guides/getting-started/components/ApiKeysStep": via('rendered within the onboarding module page'),
  "modules/onboarding/guides/getting-started/components/FinishStep": via('rendered within the onboarding module page'),
  "modules/onboarding/guides/getting-started/components/McpServersStep": via('rendered within the onboarding module page'),
  "modules/onboarding/guides/getting-started/components/MemorySetupStep": via('rendered within the onboarding module page'),
  "modules/onboarding/guides/getting-started/components/WelcomeStep": via('rendered within the onboarding module page'),
  "modules/profile/pages/ProfileSettingsPage": page("modules/profile/pages/ProfileSettingsPage"),
  "modules/projects/chat-extension/components/ProjectConversationsList": via('rendered within the projects module page'),
  "modules/projects/chat-extension/components/ProjectInlineChatInput": via('rendered within the projects module page'),
  "modules/projects/chat-extension/extension": via('rendered within the projects module page'),
  "modules/projects/components/AddToProjectModal": pending('interaction-only — needs an open-state gallery entry'),
  "modules/projects/components/ProjectCard": via('rendered within the projects module page'),
  "modules/projects/components/ProjectDefaultsForm": via('rendered within the projects module page'),
  "modules/projects/components/ProjectFormDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/projects/components/ProjectKnowledgeSection": via('rendered within the projects module page'),
  "modules/projects/core/extensions/registry": allow('non-visual — context/provider/listener/types'),
  "modules/projects/core/extensions/slots": via('rendered within the projects module page'),
  "modules/projects/pages/ProjectDetailPage": page("modules/projects/pages/ProjectDetailPage"),
  "modules/projects/pages/ProjectsListPage": page("modules/projects/pages/ProjectsListPage"),
  "modules/router/components/RouterComponent": via('rendered within the router module page'),
  "modules/server-update/AboutSettings": page("modules/server-update/AboutSettings"),
  "modules/server-update/ServerUpdateBanner": via('rendered within the server-update module page'),
  "modules/settings-general/GeneralSettings": page("modules/settings-general/GeneralSettings"),
  "modules/settings-general/components/ThemeSettings": via('rendered within the settings-general module page'),
  "modules/settings/SettingsLayout": via('rendered within the settings module page'),
  "modules/settings/SettingsPage": via('rendered within the settings module page'),
  "modules/settings/components/AddButton": via('rendered within the settings module page'),
  "modules/settings/components/SettingsFormActions": via('rendered within the settings module page'),
  "modules/settings/components/SettingsPageContainer": via('rendered within the settings module page'),
  "modules/skill/chat-extension/SkillMenuItem": via('rendered within the skill module page'),
  "modules/skill/chat-extension/extension": via('rendered within the skill module page'),
  "modules/skill/components/ConversationSkillsPanel": via('rendered within the skill module page'),
  "modules/skill/components/ImportSkillDialog": pending('interaction-only — needs an open-state gallery entry'),
  "modules/skill/components/SkillConversationDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/skill/components/SkillDetailDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/skill/components/SkillScopeBadge": via('rendered within the skill module page'),
  "modules/skill/components/SkillsList": page("modules/skill/components/SkillsList"),
  "modules/skill/components/admin/AdminSkillGroupAssignment": via('rendered within the skill module page'),
  "modules/skill/components/admin/AdminSkillsPage": page("modules/skill/components/admin/AdminSkillsPage"),
  "modules/skill/widgets/GroupSystemSkillsAssignmentDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/skill/widgets/GroupSystemSkillsWidget": via('slot-widget in skill'),
  "modules/summarization/chat-extension/components/SummarizationStatusPill": via('rendered within the summarization module page'),
  "modules/summarization/chat-extension/components/SummaryBoundaryMarker": via('rendered within the summarization module page'),
  "modules/summarization/chat-extension/extension": via('rendered within the summarization module page'),
  "modules/summarization/components/sections/SummarizationSettingsSection": via('rendered within the summarization module page'),
  "modules/summarization/pages/SummarizationAdminPage": page("modules/summarization/pages/SummarizationAdminPage"),
  "modules/user-llm-providers/UserLlmProvidersPage": via('rendered within the user-llm-providers module page'),
  "modules/user-llm-providers/chat-extension/components/ModelSelector": via('rendered within the user-llm-providers module page'),
  "modules/user-llm-providers/chat-extension/components/ProviderApiKeyModal": pending('interaction-only — needs an open-state gallery entry'),
  "modules/user-llm-providers/chat-extension/extension": via('rendered within the user-llm-providers module page'),
  "modules/user-profile/UserProfileWidget": via('rendered within the user-profile module page'),
  "modules/user/components/PermissionsField": via('rendered within the user module page'),
  "modules/user/components/group/EditUserGroupDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/user/components/group/GroupListItem": via('rendered within the user module page'),
  "modules/user/components/group/GroupMembersDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/user/components/group/UserGroupsSettings": page("modules/user/components/group/UserGroupsSettings"),
  "modules/user/components/user/AssignGroupDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/user/components/user/CreateUserDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/user/components/user/EditUserDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/user/components/user/ResetPasswordDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/user/components/user/UserGroupsDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/user/components/user/UserRegistrationSettings": via('rendered within the user module page'),
  "modules/user/components/user/UsersSettings": page("modules/user/components/user/UsersSettings"),
  "modules/web-search/components/WebSearchGlobalSection": via('rendered within the web-search module page'),
  "modules/web-search/components/WebSearchProvidersSection": via('rendered within the web-search module page'),
  "modules/web-search/components/WebSearchSettingsPage": page("modules/web-search/components/WebSearchSettingsPage"),
  "modules/web-search/components/WebSearchUserKeysPage": page("modules/web-search/components/WebSearchUserKeysPage"),
  "modules/workflow/chat-extension/components/WorkflowWorkspaceRunCard": via('rendered within the workflow module page'),
  "modules/workflow/chat-extension/extension": via('rendered within the workflow module page'),
  "modules/workflow/components/DryRunPreviewDialog": pending('interaction-only — needs an open-state gallery entry'),
  "modules/workflow/components/EditableArrayTable": via('rendered within the workflow module page'),
  "modules/workflow/components/ImportWorkflowDialog": pending('interaction-only — needs an open-state gallery entry'),
  "modules/workflow/components/StepArtifacts": via('rendered within the workflow module page'),
  "modules/workflow/components/StepLogExpander": via('rendered within the workflow module page'),
  "modules/workflow/components/StepOutputExpander": via('rendered within the workflow module page'),
  "modules/workflow/components/WorkflowDetailDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/workflow/components/WorkflowElicitForm": via('rendered within the workflow module page'),
  "modules/workflow/components/WorkflowRunDialog": pending('interaction-only — needs an open-state gallery entry'),
  "modules/workflow/components/WorkflowRunProgressView": via('rendered within the workflow module page'),
  "modules/workflow/components/WorkflowRunsList": via('rendered within the workflow module page'),
  "modules/workflow/components/WorkflowScopeBadge": via('rendered within the workflow module page'),
  "modules/workflow/components/WorkflowTestsPanel": via('rendered within the workflow module page'),
  "modules/workflow/components/WorkflowsList": page("modules/workflow/components/WorkflowsList"),
  "modules/workflow/components/admin/AdminWorkflowGroupAssignment": via('rendered within the workflow module page'),
  "modules/workflow/components/admin/AdminWorkflowsPage": page("modules/workflow/components/admin/AdminWorkflowsPage"),
  "modules/workflow/widgets/GroupSystemWorkflowsAssignmentDrawer": pending('interaction-only — needs an open-state gallery entry'),
  "modules/workflow/widgets/GroupSystemWorkflowsWidget": via('slot-widget in workflow'),
  // <<< scaffold-insert >>>
} satisfies Record<GallerySurface, Coverage>

// ── Rollup counts (used by COVERAGE.md + the coverage report) ────────────────
export function coverageSummary() {
  const counts: Record<Coverage['kind'], number> = {
    page: 0,
    story: 0,
    via: 0,
    allow: 0,
    pending: 0,
  }
  for (const v of Object.values(GALLERY_COVERAGE) as Coverage[]) counts[v.kind]++
  const total = Object.keys(GALLERY_COVERAGE).length
  const covered = total - counts.pending
  return { total, covered, ...counts }
}
