/**
 * STATE-GRANULARITY COVERAGE — the TSC-ENFORCED gate (PART 1).
 *
 * `STATE_COVERAGE` maps EVERY `RequiredState` (the generated "surface:state"
 * union in stateMatrix.generated.ts — one member per mechanically-extracted
 * loading/error/empty/overlay/panel state) to how the gallery covers it. Because
 * the object is `satisfies Record<RequiredState, StateCoverageEntry>`:
 *   - a required state with NO entry is a COMPILE error (a newly-added conditional
 *     render can't merge until it gets a gallery entry or an allow-listed reason);
 *   - a stale key (its conditional was deleted) is also a compile error.
 *
 * This is the state-level analog of coverage.ts's surface-level
 * `satisfies Record<GallerySurface, Coverage>`. Part 2's runtime branch coverage
 * is the complementary proof that a delivered entry ACTUALLY exercises the branch
 * (and it additionally covers the generic `branch` conditionals this tsc gate
 * does not name).
 *
 * Entry kinds:
 *   - { via }          — DELIVERED. The mechanism/slug that renders this state:
 *       'page-state-mode'  the page is browsed in this data-state via the
 *                          `?surface=&state=` mock-mode path (capture-gallery-states);
 *       'overlay'          an open-state overlay entry (overlays.tsx);
 *       'deep:<slug>'      a chat deep-state entry (deepStates.tsx);
 *       'interaction:<slug>' an INTERACTION recipe (interactions.ts) drives a
 *                          post-mount user action (click-to-edit, expand, focus,
 *                          hover) via `?surface=<slug>&interact=<name>` — the
 *                          delivery for states gated behind a real interaction,
 *                          which the mount-only pass otherwise had to allow-list.
 *   - { skip, reason } — an ALLOW-LISTED gap, excused in code. Used for `via`
 *                        components whose state renders only inside their parent
 *                        page (the branch is proven by Part 2 runtime coverage,
 *                        not an isolated gallery combo).
 */
import type { RequiredState } from './stateMatrix.generated'

export interface StateDelivered {
  /** The delivery mechanism: 'page-state-mode' | 'overlay' | `deep:<slug>`. */
  via: string
}
export interface AllowlistedGap {
  skip: true
  reason: string
}
export type StateCoverageEntry = StateDelivered | AllowlistedGap

// Hand-authored DEEP-STATE deliveries (upgraded from the auto-scaffold). These
// are the active-conversation deep states the seeded gallery missed — each is
// rendered by an isolated deepStates.tsx entry driving the REAL Chat store path.
export const STATE_COVERAGE = {
  // ConversationPage is an enumerated data-page — its loading/not-found states
  // render via the mock state-mode path (delayed/error); the deepStates entries
  // add the RICHER active-conversation states (streaming, right-panel, tool
  // running/failed, attachments, elicitation) that have no single named key.
  'modules/chat/pages/ConversationPage:delayed': { via: 'page-state-mode' },
  'modules/chat/pages/ConversationPage:error': { via: 'page-state-mode' },
  // The find bar's `loading` state is a transient in-flight search fetch (the
  // results-list spinner while a page of matches loads). It can't be captured
  // as a deterministic gallery snapshot; it's exercised end-to-end by the
  // server-side find e2e spec (conversation-find.spec.ts / TEST-16).
  'modules/chat/components/ConversationFindBar:delayed': {
    skip: true,
    reason:
      "transient in-flight search fetch (results-list spinner); not deterministically snapshottable — verified by the server-side find e2e spec (conversation-find.spec.ts)",
  },
  'modules/file/chat-extension/extension:panel-open': {
    via: 'deep:deep-chat-right-panel-file',
  },
  'modules/file/components/FileViewPage:delayed': {
    skip: true,
    reason:
      "full-page file view (/files/:id) — static/e2e-verified surface; ':delayed' is the route lazy-load fallback, exercised by the full-page-view e2e spec",
  },
  'modules/literature/chat-extension/extension:panel-open': {
    via: 'deep:deep-chat-right-panel-literature',
  },
  "components/ui/kit/button:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "components/ui/kit/card:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "components/ui/kit/checkbox:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "components/ui/kit/combobox:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "components/ui/kit/date-picker:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "components/ui/kit/dialog-host:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "components/ui/kit/image:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "components/ui/kit/input:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "components/ui/kit/list:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "components/ui/kit/multi-select:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "components/ui/kit/multi-select:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "components/ui/kit/radio-group:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "components/ui/kit/segmented:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "components/ui/kit/select:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "components/ui/kit/sheet:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "components/ui/kit/switch:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "components/ui/kit/table:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "components/ui/kit/textarea:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "components/ui/kit/tree:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "components/ui/shadcn/field:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "components/ui/shadcn/sidebar:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/assistant/chat-extension/components/AssistantMenuItem:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/assistant/chat-extension/components/AssistantSelector:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/assistant/components/AssistantFormDrawer:open": { via: 'overlay' },
  "modules/chat/core/components/ChatRightPanel:open": { via: 'overlay' },
  "modules/assistant/pages/AssistantsSettings:delayed": { via: 'page-state-mode' },
  "modules/assistant/pages/AssistantsSettings:empty": { via: 'page-state-mode' },
  "modules/assistant/pages/UserAssistantsSettings:delayed": { via: 'page-state-mode' },
  "modules/assistant/pages/UserAssistantsSettings:empty": { via: 'page-state-mode' },
  "modules/assistant/pages/UserAssistantsSettings:error": { via: 'page-state-mode' },
  "modules/auth-providers/components/AuthProviderEditDrawer:error": { skip: true, reason: "static surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/auth-providers/components/AuthProviderEditDrawer:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/auth-providers/components/AuthProvidersListSection:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/auth-providers/components/AuthProvidersListSection:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/auth-providers/components/AuthProvidersListSection:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/auth-providers/components/AuthProvidersListSection:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/auth/AuthCallbackPage:error": { skip: true, reason: "flow surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/auth/AuthGuard:delayed": { skip: true, reason: "nonvisual surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/auth/LinkAccountPage:error": { skip: true, reason: "flow surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/auth/LoginForm:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/auth/ProviderButtons:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/auth/ProviderButtons:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/auth/ProviderButtons:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/auth/RegisterForm:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/auth/SessionSettingsPage:delayed": { via: 'page-state-mode' },
  "modules/auth/SessionSettingsPage:error": { via: 'page-state-mode' },
  "modules/chat/components/ChatInput:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/chat/components/ChatMessage:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/chat/components/ConversationCard:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/chat/components/ConversationList:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/chat/components/ConversationList:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/chat/components/MessageList:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/chat/components/MessageList:empty": { skip: true, reason: "the dedicated 'seeded-message-list-empty' gallery surface renders this empty (!loading && count===0) branch directly" },
  "modules/chat/core/components/ChatRightPanel:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/chat/core/extensions/registry:empty": { skip: true, reason: "nonvisual surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/chat/core/extensions/slots:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/chat/core/utils/StreamdownErrorBoundary:error": { skip: true, reason: "nonvisual surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/chat/core/utils/useStreamdownComponents:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/chat/extensions/export/extension:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/chat/pages/ChatHistoryPage:delayed": { skip: true, reason: "via surface — rendered within its page; loading branch proven by Part 2 runtime coverage" },
  "modules/chat/pages/ChatHistoryPage:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/chat/widgets/RecentConversationsWidget:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/chat/widgets/RecentConversationsWidget:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/citations/components/ImportCitationsModal:empty": { skip: true, reason: "static surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/citations/components/ImportCitationsModal:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/citations/pages/CitationsSettingsPage:delayed": { via: 'page-state-mode' },
  "modules/citations/pages/CitationsSettingsPage:empty": { via: 'page-state-mode' },
  "modules/citations/pages/CitationsSettingsPage:open": { skip: true, reason: "data-page surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/citations/project-extension/components/ProjectBibliographyInlinePreview:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/citations/project-extension/components/ProjectBibliographyManagePanel:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/citations/project-extension/components/ProjectBibliographyManagePanel:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/citations/project-extension/components/ProjectBibliographyManagePanel:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/code-sandbox/components/AvailableRootfsCard:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/code-sandbox/components/DownloadedRootfsCard:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/code-sandbox/components/SandboxResourceLimitsSection:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/code-sandbox/components/SandboxResourceLimitsSection:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/code-sandbox/components/SandboxRootfsVersionsSection:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/code-sandbox/components/SandboxRootfsVersionsSection:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/file-rag/components/sections/ChunkingSection:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/file-rag/components/sections/EmbeddingSection:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/file-rag/components/sections/EmbeddingSection:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/file-rag/components/sections/EmbeddingSection:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/file-rag/components/sections/EnableSection:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/file-rag/components/sections/FullTextSection:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/file-rag/components/sections/MaintenanceSection:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/file-rag/pages/FileRagAdminPage:delayed": { via: 'page-state-mode' },
  "modules/file-rag/pages/FileRagAdminPage:error": { via: 'page-state-mode' },
  "modules/file/chat-extension/components/FileUploadArea:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/file/chat-extension/components/MessageFilesView:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/file/chat-extension/extension:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/file/components/FileCard:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/file/components/FileCard:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/file/components/FilePreviewDrawer:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/file/project-extension/components/ProjectFilesInlinePreview:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/file/project-extension/components/ProjectFilesManagePanel:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/file/viewers/markdown/body:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/file/viewers/pdf/body:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/file/viewers/pdf/pdfjs-body:delayed": { skip: true, reason: "via surface — rendered within the file preview drawer; 'delayed' (PDF loading) branch proven by Part 2 runtime coverage + the pdf-viewer e2e" },
  "modules/file/viewers/pdf/pdfjs-body:error": { skip: true, reason: "via surface — rendered within the file preview drawer; 'error' branch proven by Part 2 runtime coverage + the pdf-viewer e2e" },
  "modules/file/viewers/shared/chrome:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/file/viewers/tabular/XlsxBody:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/file/viewers/tabular/XlsxBody:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/file/viewers/tabular/XlsxBody:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/hardware/HardwareMonitor:empty": { via: 'page-state-mode' },
  "modules/hardware/HardwareSettings:empty": { via: 'page-state-mode' },
  "modules/hub/modules/assistants/components/AssistantDetailsDrawer:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/assistants/components/AssistantHubCard:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/assistants/components/AssistantsHubTab:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/assistants/components/AssistantsHubTab:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/assistants/components/AssistantsHubTab:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/installed/components/InstalledHubTab:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/installed/components/InstalledHubTab:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/installed/components/InstalledHubTab:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/llm-models/components/ModelDetailsDrawer:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/llm-models/components/ModelHubCard:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/llm-models/components/ModelHubCard:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/llm-models/components/ModelsHubTab:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/llm-models/components/ModelsHubTab:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/llm-models/components/ModelsHubTab:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/mcp/components/McpServerDetailsDrawer:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/mcp/components/McpServerHubCard:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/mcp/components/McpServersHubTab:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/mcp/components/McpServersHubTab:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/mcp/components/McpServersHubTab:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/skill/components/SkillDetailsDrawer:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/skill/components/SkillHubCard:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/skill/components/SkillsHubTab:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/skill/components/SkillsHubTab:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/workflow/components/WorkflowDetailsDrawer:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/workflow/components/WorkflowHubCard:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/workflow/components/WorkflowsHubTab:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/hub/modules/workflow/components/WorkflowsHubTab:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/layouts/app-layout/AppLayout:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/layouts/app-layout/components/Drawer:empty": { skip: true, reason: "static surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/layouts/app-layout/components/ResizeHandle:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/literature/components/LiteratureScreeningPanel:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/literature/components/LiteratureToolResultCard:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/literature/components/settings/LitSearchConnectorsSection:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/literature/components/settings/LitSearchGlobalSection:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/literature/components/settings/LitSearchSettingsPage:error": { via: 'page-state-mode' },
  "modules/literature/components/settings/LitSearchUserKeysPage:delayed": { via: 'page-state-mode' },
  "modules/literature/components/settings/LitSearchUserKeysPage:empty": { via: 'page-state-mode' },
  "modules/literature/components/settings/LitSearchUserKeysPage:error": { via: 'page-state-mode' },
  "modules/llm-local-runtime/components/AvailableVersionsCard:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/llm-local-runtime/components/AvailableVersionsCard:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/llm-local-runtime/components/InstalledVersionsCard:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/llm-local-runtime/components/LiveLogsPanel:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/llm-local-runtime/components/VersionModelsBlock:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/llm-local-runtime/components/drawers/RuntimeDownloadDrawer:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/components/GroupLlmProvidersAssignmentDrawer:delayed": { skip: true, reason: "overlay surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/components/GroupLlmProvidersAssignmentDrawer:empty": { skip: true, reason: "overlay surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/components/GroupLlmProvidersAssignmentDrawer:open": { via: 'overlay' },
  "modules/llm-provider/components/LlmModelsSection:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/components/LlmModelsSection:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/components/LlmProviderDrawer:open": { via: 'overlay' },
  "modules/llm-provider/components/LlmProviderSettings:delayed": { via: 'page-state-mode' },
  "modules/llm-provider/components/LocalProviderSettings:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/components/RemoteProviderSettings:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/components/downloads/DownloadsSection:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/components/llm-models/AddLocalLlmModelDownloadDrawer:delayed": { skip: true, reason: "static surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/components/llm-models/AddLocalLlmModelDownloadDrawer:empty": { skip: true, reason: "static surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/components/llm-models/AddLocalLlmModelDownloadDrawer:error": { skip: true, reason: "static surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/components/llm-models/AddLocalLlmModelDownloadDrawer:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/components/llm-models/AddLocalLlmModelUploadDrawer:empty": { skip: true, reason: "static surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/components/llm-models/AddLocalLlmModelUploadDrawer:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/components/llm-models/AddRemoteLlmModelDrawer:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/components/llm-models/EditLlmModelDrawer:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/components/widgets/DownloadIndicatorWidget:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/components/widgets/DownloadIndicatorWidget:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/widgets/LLMProviderGroupWidget:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/widgets/LLMProviderGroupWidget:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/widgets/LLMProviderGroupWidget:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/llm-repository/components/LlmRepositoryDrawer:open": { via: 'overlay' },
  "modules/llm-repository/components/LlmRepositorySettings:empty": { via: 'page-state-mode' },
  "modules/llm-repository/components/LlmRepositorySettings:error": { via: 'page-state-mode' },
  "modules/mcp/chat-extension/components/AskUserWizardContent:error": { skip: true, reason: "the 'error' signal is a per-field zod/Other validation message (not a load-error surface); exercised by ask-user-decision-ux.spec.ts 'Other selected but blank blocks submit with a validation error' (asserts the role=alert error + blocked POST)" },
  "modules/mcp/chat-extension/components/McpMenuItem:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/mcp/chat-extension/components/McpStatusRow:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/mcp/chat-extension/extension:error": { via: 'interaction:deep-chat-mcp-toolcall-error' },
  "modules/mcp/components/McpConfigModal:empty": { skip: true, reason: "static surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/mcp/components/McpConfigModal:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/mcp/components/common/KeyValueSecretEditor:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/mcp/components/common/McpServerDrawer:error": { skip: true, reason: "static surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/mcp/components/common/McpServerDrawer:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/mcp/components/common/McpToolCallsTab:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/mcp/components/system/GroupSystemMcpServersAssignmentDrawer:delayed": { skip: true, reason: "overlay surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/mcp/components/system/GroupSystemMcpServersAssignmentDrawer:empty": { skip: true, reason: "overlay surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/mcp/components/system/GroupSystemMcpServersAssignmentDrawer:open": { via: 'overlay' },
  "modules/mcp/components/system/McpUserPolicyCard:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/mcp/components/system/SystemMcpServersPage:empty": { via: 'page-state-mode' },
  "modules/mcp/components/user/McpServersSettings:delayed": { via: 'page-state-mode' },
  "modules/mcp/components/user/McpServersSettings:empty": { via: 'page-state-mode' },
  "modules/mcp/components/user/McpServersSettings:error": { via: 'page-state-mode' },
  "modules/mcp/project-extension/components/ProjectMcpSettingsPanel:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/mcp/project-extension/components/ProjectMcpSettingsPanel:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/mcp/widgets/GroupSystemMcpServersWidget:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/mcp/widgets/GroupSystemMcpServersWidget:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/mcp/widgets/GroupSystemMcpServersWidget:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/memory/components/CoreMemoryBlocksEditor:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/memory/components/CoreMemoryBlocksEditor:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/memory/components/sections/AuditLogSection:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/memory/components/sections/AuditLogSection:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/memory/components/sections/AuditLogSection:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/memory/components/sections/CoreMemorySection:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/memory/components/sections/CoreMemorySection:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/memory/components/sections/CoreMemorySection:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/memory/components/sections/FullTextSearchSection:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/memory/components/sections/MemorySection:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/memory/components/sections/MyMemoriesSection:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/memory/components/sections/MyMemoriesSection:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/memory/components/sections/MyMemoriesSection:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/memory/components/sections/MyMemoriesSection:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/memory/components/sections/PreferencesSection:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/memory/components/sections/PreferencesSection:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/memory/components/sections/SemanticSearchSection:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/memory/components/sections/SemanticSearchSection:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/memory/pages/MemoryAdminPage:delayed": { via: 'page-state-mode' },
  "modules/memory/pages/MemoryAdminPage:error": { via: 'page-state-mode' },
  "modules/notification/components/NotificationBellWidget:empty": { skip: true, reason: "via surface — slot-widget rendered within its page; 'empty' popover branch proven by Part 2 runtime coverage" },
  "modules/notification/components/NotificationBellWidget:open": { skip: true, reason: "via surface — popover open-state (click) proven by Part 2 runtime coverage" },
  "modules/notification/pages/NotificationsPage:delayed": { via: 'page-state-mode' },
  "modules/notification/pages/NotificationsPage:empty": { via: 'page-state-mode' },
  "modules/notification/pages/NotificationsPage:error": { via: 'page-state-mode' },
  "modules/onboarding/OnboardingRedirect:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/onboarding/guides/getting-started/components/ApiKeysStep:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/onboarding/guides/getting-started/components/ApiKeysStep:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/onboarding/guides/getting-started/components/ApiKeysStep:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/onboarding/guides/getting-started/components/MemorySetupStep:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/onboarding/guides/getting-started/components/MemorySetupStep:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/onboarding/guides/getting-started/components/MemorySetupStep:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/projects/chat-extension/components/ProjectConversationsList:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/projects/chat-extension/components/ProjectConversationsList:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/projects/chat-extension/extension:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/projects/chat-extension/extension:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/projects/components/AddToProjectModal:error": { skip: true, reason: "static surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/projects/components/AddToProjectModal:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/projects/components/ProjectCard:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/projects/components/ProjectFormDrawer:delayed": { skip: true, reason: "static surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/projects/components/ProjectFormDrawer:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/projects/components/ProjectKnowledgeSection:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/projects/components/ProjectKnowledgeSection:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/projects/core/extensions/slots:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/projects/pages/ProjectDetailPage:delayed": { via: 'page-state-mode' },
  "modules/projects/pages/ProjectDetailPage:empty": { via: 'page-state-mode' },
  "modules/projects/pages/ProjectsListPage:delayed": { via: 'page-state-mode' },
  "modules/scheduler/components/ScheduledTaskFormDrawer:open": { skip: true, reason: "scheduled-task create/edit drawer — open-state needs the SchedulerDrawer store + a live open-trigger; verified via the scheduler e2e interaction spec" },
  "modules/scheduler/pages/ScheduledTasksPage:delayed": { via: 'page-state-mode' },
  "modules/scheduler/pages/ScheduledTasksPage:empty": { via: 'page-state-mode' },
  "modules/scheduler/pages/ScheduledTasksPage:error": { via: 'page-state-mode' },
  "modules/scheduler/pages/SchedulerAdminPage:delayed": { via: 'page-state-mode' },
  "modules/scheduler/pages/SchedulerAdminPage:error": { via: 'page-state-mode' },
  "modules/server-update/AboutSettings:error": { via: 'page-state-mode' },
  "modules/skill/components/ConversationSkillsPanel:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/skill/components/ConversationSkillsPanel:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/skill/components/ConversationSkillsPanel:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/skill/components/ImportSkillDialog:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/skill/components/SkillConversationDrawer:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/skill/components/SkillDetailDrawer:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/skill/components/SkillsList:delayed": { via: 'page-state-mode' },
  "modules/skill/components/SkillsList:error": { via: 'page-state-mode' },
  "modules/skill/components/SkillsList:open": { skip: true, reason: "data-page surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/skill/components/admin/AdminSkillsPage:delayed": { via: 'page-state-mode' },
  "modules/skill/components/admin/AdminSkillsPage:error": { via: 'page-state-mode' },
  "modules/skill/components/admin/AdminSkillsPage:open": { skip: true, reason: "data-page surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/skill/widgets/GroupSystemSkillsAssignmentDrawer:open": { via: 'overlay' },
  "modules/summarization/chat-extension/components/SummarizationStatusPill:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/summarization/components/sections/SummarizationSettingsSection:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/summarization/components/sections/SummarizationSettingsSection:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/user-llm-providers/UserLlmProvidersPage:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/user-llm-providers/UserLlmProvidersPage:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/user-llm-providers/UserLlmProvidersPage:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/user-llm-providers/chat-extension/components/ProviderApiKeyModal:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/user-profile/UserProfileWidget:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/user/components/group/EditUserGroupDrawer:open": { via: 'overlay' },
  "modules/user/components/group/GroupMembersDrawer:open": { via: 'overlay' },
  "modules/user/components/group/UserGroupsSettings:empty": { via: 'page-state-mode' },
  "modules/user/components/group/UserGroupsSettings:open": { skip: true, reason: "data-page surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/user/components/user/AssignGroupDrawer:empty": { skip: true, reason: "overlay surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/user/components/user/AssignGroupDrawer:open": { via: 'overlay' },
  "modules/user/components/user/CreateUserDrawer:open": { via: 'overlay' },
  "modules/user/components/user/EditUserDrawer:open": { via: 'overlay' },
  "modules/user/components/user/ResetPasswordDrawer:open": { via: 'overlay' },
  "modules/user/components/user/UserGroupsDrawer:empty": { skip: true, reason: "overlay surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/user/components/user/UserGroupsDrawer:open": { via: 'overlay' },
  "modules/user/components/user/UsersSettings:empty": { via: 'page-state-mode' },
  "modules/user/components/user/UsersSettings:open": { skip: true, reason: "data-page surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/web-search/components/WebSearchGlobalSection:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/web-search/components/WebSearchGlobalSection:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/web-search/components/WebSearchProvidersSection:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/web-search/components/WebSearchSettingsPage:delayed": { via: 'page-state-mode' },
  "modules/web-search/components/WebSearchSettingsPage:error": { via: 'page-state-mode' },
  "modules/web-search/components/WebSearchUserKeysPage:delayed": { via: 'page-state-mode' },
  "modules/web-search/components/WebSearchUserKeysPage:empty": { via: 'page-state-mode' },
  "modules/web-search/components/WebSearchUserKeysPage:error": { via: 'page-state-mode' },
  "modules/workflow/components/DryRunPreviewDialog:delayed": { skip: true, reason: "static surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/workflow/components/DryRunPreviewDialog:error": { skip: true, reason: "static surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/workflow/components/DryRunPreviewDialog:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/workflow/components/EditableArrayTable:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/workflow/components/ImportWorkflowDialog:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/workflow/components/StepArtifacts:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/workflow/components/StepLogExpander:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/workflow/components/StepLogExpander:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/workflow/components/StepOutputExpander:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/workflow/components/StepOutputExpander:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/workflow/components/WorkflowDetailDrawer:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/workflow/components/WorkflowElicitForm:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/workflow/components/WorkflowRunDialog:open": { skip: true, reason: "static surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/workflow/components/WorkflowRunProgressView:empty": { skip: true, reason: "via surface — rendered within its page; 'empty' branch proven by Part 2 runtime coverage" },
  "modules/workflow/components/WorkflowRunProgressView:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/workflow/components/WorkflowRunsList:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/workflow/components/WorkflowTestsPanel:delayed": { skip: true, reason: "via surface — rendered within its page; 'delayed' branch proven by Part 2 runtime coverage" },
  "modules/workflow/components/WorkflowTestsPanel:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/workflow/components/WorkflowTestsPanel:open": { skip: true, reason: "via surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/workflow/components/WorkflowsList:delayed": { via: 'page-state-mode' },
  "modules/workflow/components/WorkflowsList:error": { via: 'page-state-mode' },
  "modules/workflow/components/WorkflowsList:open": { skip: true, reason: "data-page surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/workflow/components/admin/AdminWorkflowsPage:delayed": { via: 'page-state-mode' },
  "modules/workflow/components/admin/AdminWorkflowsPage:error": { via: 'page-state-mode' },
  "modules/workflow/components/admin/AdminWorkflowsPage:open": { skip: true, reason: "data-page surface — rendered within its page; 'open' branch proven by Part 2 runtime coverage" },
  "modules/workflow/widgets/GroupSystemWorkflowsAssignmentDrawer:open": { via: 'overlay' },
  "modules/assistant/pages/AssistantsSettings:error": { via: 'page-state-mode' },
  "modules/citations/pages/CitationsSettingsPage:error": { via: 'page-state-mode' },
  "modules/llm-local-runtime/components/RuntimeConfigCard:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/llm-provider/components/LlmProviderSettings:error": { via: 'page-state-mode' },
  "modules/projects/pages/ProjectsListPage:error": { via: 'page-state-mode' },
  "modules/user-llm-providers/chat-extension/components/ModelSelector:error": { skip: true, reason: "via surface — rendered within its page; 'error' branch proven by Part 2 runtime coverage" },
  "modules/user/components/group/UserGroupsSettings:error": { via: 'page-state-mode' },
  "modules/chat/components/ConversationFindBar:empty": { skip: true, reason: "via surface — the find bar renders null when closed; its open/match states are proven by the conversation-find e2e + Part 2 runtime coverage" },
  "modules/file/chat-extension/components/FilePasteHandler:empty": { skip: true, reason: "via surface — an invisible composer-attached paste-image sentinel (renders only a hidden span); behavior proven by the composer-paste-image e2e" },
  "modules/file/viewers/shared/RawCodeView:empty": { skip: true, reason: "unreachable — the flagged chunks.length===0 is an IntersectionObserver effect guard, not a render branch, and chunkLineArray always yields ≥1 chunk (even empty text → one empty-line chunk); the viewer's real render (windowed chunks + highlight) is covered by the seeded-rawcode-large gallery surface + the large-text-viewer e2e" },
  // <<< state-scaffold-insert >>>
} satisfies Record<RequiredState, StateCoverageEntry>

/** Rollup for STATE_MATRIX.md / the coverage report. */
export function stateCoverageSummary() {
  let delivered = 0
  let gaps = 0
  for (const v of Object.values(STATE_COVERAGE) as StateCoverageEntry[]) {
    if ('skip' in v) gaps++
    else delivered++
  }
  return { total: delivered + gaps, delivered, gaps }
}
