// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  clearAllServerGroups: typeof import('./actions/clearAllServerGroups')['default']
  clearServerGroups: typeof import('./actions/clearServerGroups')['default']
  getServerGroupsData: typeof import('./actions/getServerGroupsData')['default']
  loadAllGroups: typeof import('./actions/loadAllGroups')['default']
  loadGroupsForServer: typeof import('./actions/loadGroupsForServer')['default']
}
