// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  closeEditLlmModelDrawer: typeof import('./actions/closeEditLlmModelDrawer')['default']
  openEditLlmModelDrawer: typeof import('./actions/openEditLlmModelDrawer')['default']
  setEditLlmModelDrawerLoading: typeof import('./actions/setEditLlmModelDrawerLoading')['default']
}
