/**
 * Generated API type definitions
 * Auto-generated from OpenAPI specification
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * This file is automatically generated from the OpenAPI specification generated from the server code.
 */

// =============================================================================
// TYPE DEFINITIONS
// =============================================================================

export interface AssignProviderToGroupRequest {
  group_id: string
  provider_id: string
}
export interface AssignUserToGroupRequest {
  group_id: string
  user_id: string
}
export interface AuthResponse {
  access_token: string
  expires_in: number
  refresh_token: string
  token_type: string
  user: User
}
export interface CPUInfo {
  architecture: string
  base_frequency?: any
  cores: number
  max_frequency?: any
  model: string
  threads?: any
}
export interface CPUUsage {
  frequency?: any
  temperature?: any
  usage_percentage: number
}
export interface CreateGroupRequest {
  description?: any
  name: string
  permissions: string[]
}
export interface CreateLlmModelRequest {
  capabilities?: any
  description?: any
  display_name: string
  enabled?: any
  engine_settings?: any
  engine_type: EngineType
  file_format: FileFormat
  name: string
  parameters?: any
  provider_id: string
  source?: any
}
export interface CreateLlmProviderRequest {
  api_key?: any
  base_url?: any
  enabled?: any
  name: string
  provider_type: string
  proxy_settings?: any
}
export interface CreateLlmRepositoryRequest {
  auth_config?: any
  auth_type: string
  enabled?: any
  name: string
  url: string
}
export interface CreateUserRequest {
  display_name?: any
  email: string
  password: string
  username: string
}
export type DeviceType = any
export interface DownloadFromRepositoryRequest {
  capabilities?: any
  description?: any
  display_name: string
  engine_settings?: any
  engine_type?: any
  file_format: FileFormat
  main_filename: string
  name: string
  parameters?: any
  provider_id: string
  repository_branch?: any
  repository_id: string
  repository_path: string
  source: SourceInfo
}
export interface DownloadInstance {
  completed_at?: any
  created_at: string
  error_message?: any
  id: string
  model_id?: any
  progress_data: JsonOption_for_DownloadProgressData
  provider_id: string
  repository_id: string
  request_data: DownloadRequestData
  started_at: string
  status: DownloadStatus
  updated_at: string
}
export type DownloadPhase = string
export interface DownloadProgressData {
  current: number
  eta_seconds: number
  message: string
  phase: DownloadPhase
  speed_bps: number
  total: number
}
export interface DownloadRequestData {
  capabilities?: any
  description?: any
  display_name?: any
  engine_settings?: any
  engine_type?: any
  file_format?: any
  files?: any
  main_filename?: any
  model_name: string
  parameters?: any
  quantization?: any
  repository_path?: any
  revision?: any
  source?: any
}
export type DownloadStatus = string
export type EngineType = string
export type FileFormat = string
export interface GPUComputeCapabilities {
  cuda_support: boolean
  cuda_version?: any
  metal_support: boolean
  opencl_support: boolean
  vulkan_support?: any
}
export interface GPUDevice {
  compute_capabilities: GPUComputeCapabilities
  device_id: string
  driver_version?: any
  memory?: any
  name: string
  vendor: string
}
export interface GPUUsage {
  device_id: string
  device_name: string
  memory_total?: any
  memory_usage_percentage?: any
  memory_used?: any
  power_usage?: any
  temperature?: any
  utilization_percentage?: any
}
export interface Group {
  created_at: string
  description?: any
  id: string
  is_active: boolean
  is_default: boolean
  is_system: boolean
  name: string
  permissions: string[]
  updated_at: string
}
export interface GroupListResponse {
  groups: Group[]
  page: number
  per_page: number
  total: number
  total_pages: number
}
export interface HardwareInfo {
  cpu: CPUInfo
  gpu_devices: GPUDevice[]
  memory: MemoryInfo
  operating_system: OperatingSystemInfo
}
export interface HardwareInfoResponse {
  hardware: HardwareInfo
}
export interface HardwareUsageUpdate {
  cpu: CPUUsage
  gpu_devices: GPUUsage[]
  memory: MemoryUsage
  timestamp: string
}
export interface HealthResponse {
  status: string
}
export type JsonOption_for_DownloadProgressData = any
export interface ListModelsQuery {
  page?: number
  perPage?: number
  providerId?: any
}
export interface LlamaCppSettings {
  batch_size?: any
  cache_type_k?: any
  cache_type_v?: any
  cont_batching?: any
  ctx_size?: any
  device_ids?: any
  device_type?: any
  flash_attn?: any
  keep?: any
  main_gpu?: any
  mlock?: any
  n_gpu_layers?: any
  no_kv_offload?: any
  no_mmap?: any
  numa?: any
  parallel?: any
  rope_freq_base?: any
  rope_freq_scale?: any
  rope_scaling?: any
  seed?: any
  split_mode?: any
  tensor_split?: any
  threads?: any
  threads_batch?: any
  ubatch_size?: any
}
export interface LlmModel {
  capabilities: ModelCapabilities
  created_at: string
  description?: any
  display_name: string
  enabled: boolean
  engine_settings?: any
  engine_type: EngineType
  file_format: FileFormat
  file_size_bytes?: any
  id: string
  is_active: boolean
  is_deprecated: boolean
  name: string
  parameters: ModelParameters
  pid?: any
  port?: any
  provider_id: string
  source?: any
  updated_at: string
  validation_issues?: any
  validation_status?: any
}
export interface LlmModelListResponse {
  models: LlmModel[]
  page: number
  per_page: number
  total: number
}
export interface LlmProvider {
  api_key?: any
  base_url?: any
  built_in: boolean
  created_at: string
  enabled: boolean
  id: string
  name: string
  provider_type: string
  proxy_settings: ProxySettings
  updated_at: string
}
export interface LlmProviderListResponse {
  page: number
  per_page: number
  providers: LlmProvider[]
  total: number
}
export interface LlmRepository {
  auth_config: RepositoryAuthConfig
  auth_type: string
  built_in: boolean
  created_at: string
  enabled: boolean
  id: string
  name: string
  updated_at: string
  url: string
}
export interface LlmRepositoryListResponse {
  page: number
  per_page: number
  repositories: LlmRepository[]
  total: number
}
export interface LoginRequest {
  password: string
  provider?: any
  username: string
}
export interface MeResponse {
  permissions: string[]
  user: User
}
export interface MemoryInfo {
  total_ram: number
  total_swap?: any
}
export interface MemoryUsage {
  available_ram: number
  available_swap?: any
  usage_percentage: number
  used_ram: number
  used_swap?: any
}
export type MistralRsCommand = any
export interface MistralRsSettings {
  arch?: any
  chat_template?: any
  command?: any
  cpu?: any
  device_ids?: any
  device_type?: any
  dtype?: any
  enable_search?: any
  enable_thinking?: any
  in_situ_quant?: any
  interactive_mode?: any
  jinja_explicit?: any
  log_file?: any
  max_edge?: any
  max_image_length?: any
  max_num_images?: any
  max_seq_len?: any
  max_seqs?: any
  model_id_name?: any
  no_kv_cache?: any
  no_paged_attn?: any
  num_device_layers?: any
  paged_attn?: any
  paged_attn_block_size?: any
  paged_attn_gpu_mem?: any
  paged_attn_gpu_mem_usage?: any
  paged_ctxt_len?: any
  prefix_cache_n?: any
  prompt_chunksize?: any
  quantized_filename?: any
  search_bert_model?: any
  seed?: any
  serve_ip?: any
  token_source?: any
  tokenizer_json?: any
  truncate_sequence?: any
  weight_file?: any
}
export interface ModelCapabilities {
  audio?: any
  chat?: any
  code_interpreter?: any
  image_generator?: any
  text_embedding?: any
  tools?: any
  vision?: any
}
export interface ModelEngineSettings {
  llamacpp?: any
  mistralrs?: any
}
export interface ModelParameters {
  frequency_penalty?: any
  max_tokens?: any
  min_p?: any
  presence_penalty?: any
  repeat_last_n?: any
  repeat_penalty?: any
  seed?: any
  stop?: any
  temperature?: any
  top_k?: any
  top_p?: any
}
export interface OperatingSystemInfo {
  architecture: string
  kernel_version?: any
  name: string
  version: string
}
export interface PaginationQuery {
  page?: number
  per_page?: number
}
export interface PermissionDetail {
  description: string
  name: string
  value: string
}
export interface PermissionError {
  details: PermissionErrorDetails
  error: string
  error_code: string
}
export interface PermissionErrorDetails {
  required_permissions: PermissionDetail[]
}
export interface ProxySettings {
  enabled?: boolean
  ignore_ssl_certificates?: boolean
  no_proxy?: string
  password?: string
  url?: string
  username?: string
}
export interface RefreshTokenRequest {
  refresh_token: string
}
export interface RegisterRequest {
  display_name?: any
  email: string
  password: string
  username: string
}
export interface RepositoryAuthConfig {
  api_key?: any
  auth_test_api_endpoint?: any
  password?: any
  token?: any
  username?: any
}
export interface ResetPasswordRequest {
  new_password: string
  user_id: string
}
export interface SSEHardwareUsageConnectedData {
  message: string
}
export type SSEHardwareUsageEvent = {
  connected: SSEHardwareUsageConnectedData
  update: HardwareUsageUpdate
}
export interface SetupAdminRequest {
  display_name?: any
  email: string
  password: string
  username: string
}
export interface SetupStatusResponse {
  app_name: string
  needs_setup: boolean
  version: string
}
export interface SourceInfo {
  id?: any
  type: string
}
export interface TestRepositoryConnectionRequest {
  auth_config?: any
  auth_type: string
  name: string
  url: string
}
export interface TestRepositoryConnectionResponse {
  message: string
  success: boolean
}
export interface TokenPair {
  access_token: string
  expires_in: number
  refresh_token: string
  token_type: string
}
export interface UpdateGroupRequest {
  description?: any
  is_active?: any
  name?: any
  permissions?: any
}
export interface UpdateLlmModelRequest {
  capabilities?: any
  description?: any
  display_name?: any
  enabled?: any
  engine_settings?: any
  engine_type?: any
  file_format?: any
  is_active?: any
  name?: any
  parameters?: any
}
export interface UpdateLlmProviderRequest {
  api_key?: any
  base_url?: any
  enabled?: any
  name?: any
  proxy_settings?: any
}
export interface UpdateLlmRepositoryRequest {
  auth_config?: any
  auth_type?: any
  enabled?: any
  name?: any
  url?: any
}
export interface UpdateUserRequest {
  display_name?: any
  email?: any
  is_active?: any
  username?: any
}
export interface User {
  avatar_url?: any
  created_at: string
  display_name?: any
  email: string
  email_verified: boolean
  id: string
  is_active: boolean
  last_login_at?: any
  updated_at: string
  username: string
}
export interface UserActiveStatusResponse {
  is_active: boolean
  user_id: string
}
export interface UserListResponse {
  page: number
  per_page: number
  total: number
  total_pages: number
  users: User[]
}
export enum Permission {
  GroupsAssignUsers = 'groups::assign-users',
  GroupsCreate = 'groups::create',
  GroupsDelete = 'groups::delete',
  GroupsEdit = 'groups::edit',
  GroupsRead = 'groups::read',
  LlmModelsCreate = 'llm_models::create',
  LlmModelsDelete = 'llm_models::delete',
  LlmModelsEdit = 'llm_models::edit',
  LlmModelsRead = 'llm_models::read',
  LlmProvidersAssignGroups = 'llm_providers::assign_groups',
  LlmProvidersCreate = 'llm_providers::create',
  LlmProvidersDelete = 'llm_providers::delete',
  LlmProvidersEdit = 'llm_providers::edit',
  LlmProvidersRead = 'llm_providers::read',
  LlmRepositoriesCreate = 'llm_repositories::create',
  LlmRepositoriesDelete = 'llm_repositories::delete',
  LlmRepositoriesEdit = 'llm_repositories::edit',
  LlmRepositoriesRead = 'llm_repositories::read',
  UsersCreate = 'users::create',
  UsersDelete = 'users::delete',
  UsersEdit = 'users::edit',
  UsersRead = 'users::read',
  UsersResetPassword = 'users::reset-password',
  UsersToggleStatus = 'users::toggle-status',
}


// =============================================================================
// API ENDPOINTS
// =============================================================================

// API endpoint definitions
export const ApiEndpoints = {
  'App.getSetupStatus': 'GET /api/app/setup/status',
  'App.setupAdmin': 'POST /api/app/setup/admin',
  'Auth.login': 'POST /api/auth/login',
  'Auth.logout': 'POST /api/auth/logout',
  'Auth.me': 'GET /api/auth/me',
  'Auth.refresh': 'POST /api/auth/refresh',
  'Auth.register': 'POST /api/auth/register',
  'Hardware.info': 'GET /api/hardware',
  'Hardware.stream': 'GET /api/hardware/usage-stream',
  'Health.check': 'GET /api/health',
  'LlmModel.create': 'POST /api/llm-models',
  'LlmModel.delete': 'DELETE /api/llm-models/{model_id}',
  'LlmModel.disable': 'POST /api/llm-models/{model_id}/disable',
  'LlmModel.download': 'POST /api/llm-models/download',
  'LlmModel.enable': 'POST /api/llm-models/{model_id}/enable',
  'LlmModel.get': 'GET /api/llm-models/{model_id}',
  'LlmModel.list': 'GET /api/llm-models',
  'LlmModel.update': 'POST /api/llm-models/{model_id}',
  'LlmModel.upload': 'POST /api/llm-models/upload',
  'LlmProvider.assignGroup': 'POST /api/llm-providers/assign-group',
  'LlmProvider.create': 'POST /api/llm-providers',
  'LlmProvider.delete': 'DELETE /api/llm-providers/{provider_id}',
  'LlmProvider.get': 'GET /api/llm-providers/{provider_id}',
  'LlmProvider.getGroups': 'GET /api/llm-providers/{provider_id}/groups',
  'LlmProvider.list': 'GET /api/llm-providers',
  'LlmProvider.removeGroup': 'DELETE /api/llm-providers/{provider_id}/{group_id}/remove-group',
  'LlmProvider.update': 'POST /api/llm-providers/{provider_id}',
  'LlmRepository.create': 'POST /api/llm-repositories',
  'LlmRepository.delete': 'DELETE /api/llm-repositories/{repository_id}',
  'LlmRepository.get': 'GET /api/llm-repositories/{repository_id}',
  'LlmRepository.list': 'GET /api/llm-repositories',
  'LlmRepository.test': 'POST /api/llm-repositories/test',
  'LlmRepository.update': 'POST /api/llm-repositories/{repository_id}',
  'User.create': 'POST /api/users',
  'User.delete': 'DELETE /api/users/{user_id}',
  'User.get': 'GET /api/users/{user_id}',
  'User.list': 'GET /api/users',
  'User.resetPassword': 'POST /api/users/reset-password',
  'User.toggleActive': 'POST /api/users/{user_id}/toggle-active',
  'User.update': 'POST /api/users/{user_id}',
  'UserGroup.assignUser': 'POST /api/groups/assign',
  'UserGroup.create': 'POST /api/groups',
  'UserGroup.delete': 'DELETE /api/groups/{group_id}',
  'UserGroup.get': 'GET /api/groups/{group_id}',
  'UserGroup.getMembers': 'GET /api/groups/{group_id}/members',
  'UserGroup.list': 'GET /api/groups',
  'UserGroup.removeUser': 'DELETE /api/groups/{user_id}/{group_id}/remove',
  'UserGroup.update': 'POST /api/groups/{group_id}',
} as const

// API endpoint parameters
export type ApiEndpointParameters = {
  'App.getSetupStatus': void
  'App.setupAdmin': SetupAdminRequest
  'Auth.login': LoginRequest
  'Auth.logout': void
  'Auth.me': void
  'Auth.refresh': RefreshTokenRequest
  'Auth.register': RegisterRequest
  'Hardware.info': void
  'Hardware.stream': void
  'Health.check': void
  'LlmModel.create': CreateLlmModelRequest
  'LlmModel.delete': { model_id: string }
  'LlmModel.disable': { model_id: string }
  'LlmModel.download': DownloadFromRepositoryRequest
  'LlmModel.enable': { model_id: string }
  'LlmModel.get': { model_id: string }
  'LlmModel.list': { page?: number; perPage?: number; providerId?: any }
  'LlmModel.update': { model_id: string } & UpdateLlmModelRequest
  'LlmModel.upload': void
  'LlmProvider.assignGroup': AssignProviderToGroupRequest
  'LlmProvider.create': CreateLlmProviderRequest
  'LlmProvider.delete': { provider_id: string }
  'LlmProvider.get': { provider_id: string }
  'LlmProvider.getGroups': { provider_id: string }
  'LlmProvider.list': { page?: number; per_page?: number }
  'LlmProvider.removeGroup': { provider_id: string; group_id: string }
  'LlmProvider.update': { provider_id: string } & UpdateLlmProviderRequest
  'LlmRepository.create': CreateLlmRepositoryRequest
  'LlmRepository.delete': { repository_id: string }
  'LlmRepository.get': { repository_id: string }
  'LlmRepository.list': { page?: number; per_page?: number }
  'LlmRepository.test': TestRepositoryConnectionRequest
  'LlmRepository.update': { repository_id: string } & UpdateLlmRepositoryRequest
  'User.create': CreateUserRequest
  'User.delete': { user_id: string }
  'User.get': { user_id: string }
  'User.list': { page?: number; per_page?: number }
  'User.resetPassword': ResetPasswordRequest
  'User.toggleActive': { user_id: string }
  'User.update': { user_id: string } & UpdateUserRequest
  'UserGroup.assignUser': AssignUserToGroupRequest
  'UserGroup.create': CreateGroupRequest
  'UserGroup.delete': { group_id: string }
  'UserGroup.get': { group_id: string }
  'UserGroup.getMembers': { group_id: string; page?: number; per_page?: number }
  'UserGroup.list': { page?: number; per_page?: number }
  'UserGroup.removeUser': { user_id: string; group_id: string }
  'UserGroup.update': { group_id: string } & UpdateGroupRequest
}

// API endpoint responses
export type ApiEndpointResponses = {
  'App.getSetupStatus': SetupStatusResponse
  'App.setupAdmin': AuthResponse
  'Auth.login': AuthResponse
  'Auth.logout': void
  'Auth.me': MeResponse
  'Auth.refresh': TokenPair
  'Auth.register': AuthResponse
  'Hardware.info': HardwareInfoResponse
  'Hardware.stream': SSEHardwareUsageEvent
  'Health.check': HealthResponse
  'LlmModel.create': LlmModel
  'LlmModel.delete': void
  'LlmModel.disable': LlmModel
  'LlmModel.download': DownloadInstance
  'LlmModel.enable': LlmModel
  'LlmModel.get': LlmModel
  'LlmModel.list': LlmModelListResponse
  'LlmModel.update': LlmModel
  'LlmModel.upload': LlmModel
  'LlmProvider.assignGroup': void
  'LlmProvider.create': LlmProvider
  'LlmProvider.delete': void
  'LlmProvider.get': LlmProvider
  'LlmProvider.getGroups': Group[]
  'LlmProvider.list': LlmProviderListResponse
  'LlmProvider.removeGroup': void
  'LlmProvider.update': LlmProvider
  'LlmRepository.create': LlmRepository
  'LlmRepository.delete': void
  'LlmRepository.get': LlmRepository
  'LlmRepository.list': LlmRepositoryListResponse
  'LlmRepository.test': TestRepositoryConnectionResponse
  'LlmRepository.update': LlmRepository
  'User.create': User
  'User.delete': void
  'User.get': User
  'User.list': UserListResponse
  'User.resetPassword': void
  'User.toggleActive': UserActiveStatusResponse
  'User.update': User
  'UserGroup.assignUser': void
  'UserGroup.create': Group
  'UserGroup.delete': void
  'UserGroup.get': Group
  'UserGroup.getMembers': UserListResponse
  'UserGroup.list': GroupListResponse
  'UserGroup.removeUser': void
  'UserGroup.update': Group
}

// Type helpers
export type ApiEndpoint = keyof typeof ApiEndpoints
export type ApiEndpointUrl = (typeof ApiEndpoints)[ApiEndpoint]

// Extract endpoint key from URL pattern
export function getEndpointKey(url: string): ApiEndpoint | undefined {
  const entries = Object.entries(ApiEndpoints) as [ApiEndpoint, string][]
  const found = entries.find(([_key, value]) => value === url)
  return found ? found[0] : undefined
}

// Get parameter type for endpoint
export type GetParameterType<K extends ApiEndpoint> = ApiEndpointParameters[K]

// Get response type for endpoint
export type GetResponseType<K extends ApiEndpoint> = ApiEndpointResponses[K]

// Create reverse mapping from URL to endpoint key
export type UrlToEndpoint<U extends ApiEndpointUrl> = {
  [K in keyof typeof ApiEndpoints]: (typeof ApiEndpoints)[K] extends U
    ? K
    : never
}[keyof typeof ApiEndpoints]

// Helper types to get parameter and response types by URL
export type ParameterByUrl<U extends ApiEndpointUrl> =
  ApiEndpointParameters[UrlToEndpoint<U>]
export type ResponseByUrl<U extends ApiEndpointUrl> =
  ApiEndpointResponses[UrlToEndpoint<U>]

// Type-safe validation - this will cause a TypeScript error if any endpoint is missing
type ValidateParametersComplete = {
  [K in keyof typeof ApiEndpoints]: K extends keyof ApiEndpointParameters
    ? true
    : false
}

type ValidateResponsesComplete = {
  [K in keyof typeof ApiEndpoints]: K extends keyof ApiEndpointResponses
    ? true
    : false
}

// Type-safe validation - these will cause a TypeScript error if any endpoint is missing
// from Parameters or Responses. They are used for compile-time validation only.
export type { ValidateParametersComplete, ValidateResponsesComplete }
