/**
 * Generated API type definitions
 * Auto-generated from OpenAPI specification
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * This file is automatically generated from the OpenAPI specification generated from the server code.
 */

// =============================================================================
// TYPE DEFINITIONS
// =============================================================================

export interface AssignUserToGroupRequest {
  group_id: string
  user_id: string
}
export interface AuthResponse {
  access_token: string
  expires_in: number
  refresh_token: string
  token_type: string
  user: User
}
export interface CPUInfo {
  architecture: string
  base_frequency?: any
  cores: number
  max_frequency?: any
  model: string
  threads?: any
}
export interface CPUUsage {
  frequency?: any
  temperature?: any
  usage_percentage: number
}
export interface CreateGroupRequest {
  description?: any
  name: string
  permissions: string[]
}
export interface CreateLlmRepositoryRequest {
  auth_config?: any
  auth_type: string
  enabled?: any
  name: string
  url: string
}
export interface CreateUserRequest {
  display_name?: any
  email: string
  password: string
  username: string
}
export interface GPUComputeCapabilities {
  cuda_support: boolean
  cuda_version?: any
  metal_support: boolean
  opencl_support: boolean
  vulkan_support?: any
}
export interface GPUDevice {
  compute_capabilities: GPUComputeCapabilities
  device_id: string
  driver_version?: any
  memory?: any
  name: string
  vendor: string
}
export interface GPUUsage {
  device_id: string
  device_name: string
  memory_total?: any
  memory_usage_percentage?: any
  memory_used?: any
  power_usage?: any
  temperature?: any
  utilization_percentage?: any
}
export interface Group {
  created_at: string
  description?: any
  id: string
  is_active: boolean
  is_default: boolean
  is_system: boolean
  name: string
  permissions: string[]
  updated_at: string
}
export interface GroupListResponse {
  groups: Group[]
  page: number
  per_page: number
  total: number
  total_pages: number
}
export interface HardwareInfo {
  cpu: CPUInfo
  gpu_devices: GPUDevice[]
  memory: MemoryInfo
  operating_system: OperatingSystemInfo
}
export interface HardwareInfoResponse {
  hardware: HardwareInfo
}
export interface HardwareUsageUpdate {
  cpu: CPUUsage
  gpu_devices: GPUUsage[]
  memory: MemoryUsage
  timestamp: string
}
export interface HealthResponse {
  status: string
}
export interface LlmRepository {
  auth_config: RepositoryAuthConfig
  auth_type: string
  built_in: boolean
  created_at: string
  enabled: boolean
  id: string
  name: string
  updated_at: string
  url: string
}
export interface LlmRepositoryListResponse {
  page: number
  per_page: number
  repositories: LlmRepository[]
  total: number
}
export interface LoginRequest {
  password: string
  provider?: any
  username: string
}
export interface MeResponse {
  permissions: string[]
  user: User
}
export interface MemoryInfo {
  total_ram: number
  total_swap?: any
}
export interface MemoryUsage {
  available_ram: number
  available_swap?: any
  usage_percentage: number
  used_ram: number
  used_swap?: any
}
export interface OperatingSystemInfo {
  architecture: string
  kernel_version?: any
  name: string
  version: string
}
export interface PaginationQuery {
  page?: number
  per_page?: number
}
export interface PermissionDetail {
  description: string
  name: string
  value: string
}
export interface PermissionError {
  details: PermissionErrorDetails
  error: string
  error_code: string
}
export interface PermissionErrorDetails {
  required_permissions: PermissionDetail[]
}
export interface RefreshTokenRequest {
  refresh_token: string
}
export interface RegisterRequest {
  display_name?: any
  email: string
  password: string
  username: string
}
export interface RepositoryAuthConfig {
  api_key?: any
  auth_test_api_endpoint?: any
  password?: any
  token?: any
  username?: any
}
export interface ResetPasswordRequest {
  new_password: string
  user_id: string
}
export interface SSEHardwareUsageConnectedData {
  message: string
}
export type SSEHardwareUsageEvent = {
  connected: SSEHardwareUsageConnectedData
  update: HardwareUsageUpdate
}
export interface SetupAdminRequest {
  display_name?: any
  email: string
  password: string
  username: string
}
export interface SetupStatusResponse {
  app_name: string
  needs_setup: boolean
  version: string
}
export interface TestRepositoryConnectionRequest {
  auth_config?: any
  auth_type: string
  name: string
  url: string
}
export interface TestRepositoryConnectionResponse {
  message: string
  success: boolean
}
export interface TokenPair {
  access_token: string
  expires_in: number
  refresh_token: string
  token_type: string
}
export interface UpdateGroupRequest {
  description?: any
  is_active?: any
  name?: any
  permissions?: any
}
export interface UpdateLlmRepositoryRequest {
  auth_config?: any
  auth_type?: any
  enabled?: any
  name?: any
  url?: any
}
export interface UpdateUserRequest {
  display_name?: any
  email?: any
  is_active?: any
  username?: any
}
export interface User {
  avatar_url?: any
  created_at: string
  display_name?: any
  email: string
  email_verified: boolean
  id: string
  is_active: boolean
  last_login_at?: any
  updated_at: string
  username: string
}
export interface UserActiveStatusResponse {
  is_active: boolean
  user_id: string
}
export interface UserListResponse {
  page: number
  per_page: number
  total: number
  total_pages: number
  users: User[]
}
export enum Permission {
  GroupsAssignUsers = 'groups::assign-users',
  GroupsCreate = 'groups::create',
  GroupsDelete = 'groups::delete',
  GroupsEdit = 'groups::edit',
  GroupsRead = 'groups::read',
  LlmRepositoriesCreate = 'llm_repositories::create',
  LlmRepositoriesDelete = 'llm_repositories::delete',
  LlmRepositoriesEdit = 'llm_repositories::edit',
  LlmRepositoriesRead = 'llm_repositories::read',
  UsersCreate = 'users::create',
  UsersDelete = 'users::delete',
  UsersEdit = 'users::edit',
  UsersRead = 'users::read',
  UsersResetPassword = 'users::reset-password',
  UsersToggleStatus = 'users::toggle-status',
}


// =============================================================================
// API ENDPOINTS
// =============================================================================

// API endpoint definitions
export const ApiEndpoints = {
  'App.getSetupStatus': 'GET /api/app/setup/status',
  'App.setupAdmin': 'POST /api/app/setup/admin',
  'Auth.login': 'POST /api/auth/login',
  'Auth.logout': 'POST /api/auth/logout',
  'Auth.me': 'GET /api/auth/me',
  'Auth.refresh': 'POST /api/auth/refresh',
  'Auth.register': 'POST /api/auth/register',
  'Hardware.info': 'GET /api/hardware',
  'Hardware.stream': 'GET /api/hardware/usage-stream',
  'Health.check': 'GET /api/health',
  'LlmRepository.create': 'POST /api/llm-repositories',
  'LlmRepository.delete': 'DELETE /api/llm-repositories/{repository_id}',
  'LlmRepository.get': 'GET /api/llm-repositories/{repository_id}',
  'LlmRepository.list': 'GET /api/llm-repositories',
  'LlmRepository.test': 'POST /api/llm-repositories/test',
  'LlmRepository.update': 'POST /api/llm-repositories/{repository_id}',
  'User.create': 'POST /api/users',
  'User.delete': 'DELETE /api/users/{user_id}',
  'User.get': 'GET /api/users/{user_id}',
  'User.list': 'GET /api/users',
  'User.resetPassword': 'POST /api/users/reset-password',
  'User.toggleActive': 'POST /api/users/{user_id}/toggle-active',
  'User.update': 'POST /api/users/{user_id}',
  'UserGroup.assignUser': 'POST /api/groups/assign',
  'UserGroup.create': 'POST /api/groups',
  'UserGroup.delete': 'DELETE /api/groups/{group_id}',
  'UserGroup.get': 'GET /api/groups/{group_id}',
  'UserGroup.getMembers': 'GET /api/groups/{group_id}/members',
  'UserGroup.list': 'GET /api/groups',
  'UserGroup.removeUser': 'DELETE /api/groups/{user_id}/{group_id}/remove',
  'UserGroup.update': 'POST /api/groups/{group_id}',
} as const

// API endpoint parameters
export type ApiEndpointParameters = {
  'App.getSetupStatus': void
  'App.setupAdmin': SetupAdminRequest
  'Auth.login': LoginRequest
  'Auth.logout': void
  'Auth.me': void
  'Auth.refresh': RefreshTokenRequest
  'Auth.register': RegisterRequest
  'Hardware.info': void
  'Hardware.stream': void
  'Health.check': void
  'LlmRepository.create': CreateLlmRepositoryRequest
  'LlmRepository.delete': { repository_id: string }
  'LlmRepository.get': { repository_id: string }
  'LlmRepository.list': { page?: number; per_page?: number }
  'LlmRepository.test': TestRepositoryConnectionRequest
  'LlmRepository.update': { repository_id: string } & UpdateLlmRepositoryRequest
  'User.create': CreateUserRequest
  'User.delete': { user_id: string }
  'User.get': { user_id: string }
  'User.list': { page?: number; per_page?: number }
  'User.resetPassword': ResetPasswordRequest
  'User.toggleActive': { user_id: string }
  'User.update': { user_id: string } & UpdateUserRequest
  'UserGroup.assignUser': AssignUserToGroupRequest
  'UserGroup.create': CreateGroupRequest
  'UserGroup.delete': { group_id: string }
  'UserGroup.get': { group_id: string }
  'UserGroup.getMembers': { group_id: string; page?: number; per_page?: number }
  'UserGroup.list': { page?: number; per_page?: number }
  'UserGroup.removeUser': { user_id: string; group_id: string }
  'UserGroup.update': { group_id: string } & UpdateGroupRequest
}

// API endpoint responses
export type ApiEndpointResponses = {
  'App.getSetupStatus': SetupStatusResponse
  'App.setupAdmin': AuthResponse
  'Auth.login': AuthResponse
  'Auth.logout': void
  'Auth.me': MeResponse
  'Auth.refresh': TokenPair
  'Auth.register': AuthResponse
  'Hardware.info': HardwareInfoResponse
  'Hardware.stream': SSEHardwareUsageEvent
  'Health.check': HealthResponse
  'LlmRepository.create': LlmRepository
  'LlmRepository.delete': void
  'LlmRepository.get': LlmRepository
  'LlmRepository.list': LlmRepositoryListResponse
  'LlmRepository.test': TestRepositoryConnectionResponse
  'LlmRepository.update': LlmRepository
  'User.create': User
  'User.delete': void
  'User.get': User
  'User.list': UserListResponse
  'User.resetPassword': void
  'User.toggleActive': UserActiveStatusResponse
  'User.update': User
  'UserGroup.assignUser': void
  'UserGroup.create': Group
  'UserGroup.delete': void
  'UserGroup.get': Group
  'UserGroup.getMembers': UserListResponse
  'UserGroup.list': GroupListResponse
  'UserGroup.removeUser': void
  'UserGroup.update': Group
}

// Type helpers
export type ApiEndpoint = keyof typeof ApiEndpoints
export type ApiEndpointUrl = (typeof ApiEndpoints)[ApiEndpoint]

// Extract endpoint key from URL pattern
export function getEndpointKey(url: string): ApiEndpoint | undefined {
  const entries = Object.entries(ApiEndpoints) as [ApiEndpoint, string][]
  const found = entries.find(([_key, value]) => value === url)
  return found ? found[0] : undefined
}

// Get parameter type for endpoint
export type GetParameterType<K extends ApiEndpoint> = ApiEndpointParameters[K]

// Get response type for endpoint
export type GetResponseType<K extends ApiEndpoint> = ApiEndpointResponses[K]

// Create reverse mapping from URL to endpoint key
export type UrlToEndpoint<U extends ApiEndpointUrl> = {
  [K in keyof typeof ApiEndpoints]: (typeof ApiEndpoints)[K] extends U
    ? K
    : never
}[keyof typeof ApiEndpoints]

// Helper types to get parameter and response types by URL
export type ParameterByUrl<U extends ApiEndpointUrl> =
  ApiEndpointParameters[UrlToEndpoint<U>]
export type ResponseByUrl<U extends ApiEndpointUrl> =
  ApiEndpointResponses[UrlToEndpoint<U>]

// Type-safe validation - this will cause a TypeScript error if any endpoint is missing
type ValidateParametersComplete = {
  [K in keyof typeof ApiEndpoints]: K extends keyof ApiEndpointParameters
    ? true
    : false
}

type ValidateResponsesComplete = {
  [K in keyof typeof ApiEndpoints]: K extends keyof ApiEndpointResponses
    ? true
    : false
}

// Type-safe validation - these will cause a TypeScript error if any endpoint is missing
// from Parameters or Responses. They are used for compile-time validation only.
export type { ValidateParametersComplete, ValidateResponsesComplete }
