/**
 * Generated API endpoint definitions
 * Auto-generated from OpenAPI specification
 * 
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY ⚠️
 * This file is automatically generated from the OpenAPI specification generated from the server code.
 */

// =============================================================================
// TYPE DEFINITIONS
// =============================================================================

export interface AssignProviderToGroupRequest {
  group_id: string
  provider_id: string
}

export interface AssignUserToGroupRequest {
  group_id: string
  user_id: string
}

export interface AuthResponse {
  access_token: string
  expires_in: number
  refresh_token: string
  token_type: string
  user: User
}

export interface CPUInfo {
  architecture: string
  base_frequency?: number
  cores: number
  max_frequency?: number
  model: string
  threads?: number
}

export interface CPUUsage {
  frequency?: number
  temperature?: number
  usage_percentage: number
}

export interface CreateGroupRequest {
  description?: string
  name: string
  permissions: string[]
}

export interface CreateLlmModelRequest {
  description?: string
  capabilities?: ModelCapabilities
  display_name: string
  enabled?: boolean
  engine_settings?: ModelEngineSettings
  engine_type: EngineType
  file_format: FileFormat
  name: string
  parameters?: ModelParameters
  provider_id: string
  source?: SourceInfo
}

export interface CreateLlmProviderRequest {
  api_key?: string
  base_url?: string
  enabled?: boolean
  name: string
  provider_type: string
  proxy_settings?: ProxySettings
}

export interface CreateLlmRepositoryRequest {
  auth_config?: RepositoryAuthConfig
  auth_type: string
  enabled?: boolean
  name: string
  url: string
}

export interface CreateUserRequest {
  display_name?: string
  email: string
  password: string
  username: string
}

export type DeviceType = 'cpu' | 'cuda' | 'metal' | 'rocm' | 'vulkan' | 'opencl' | 'auto'

export interface DownloadFromRepositoryRequest {
  description?: string
  capabilities?: ModelCapabilities
  clear_cache?: boolean
  display_name: string
  engine_settings?: ModelEngineSettings
  engine_type?: EngineType
  file_format: FileFormat
  main_filename: string
  name: string
  parameters?: ModelParameters
  provider_id: string
  repository_branch?: string
  repository_id: string
  repository_path: string
  source: SourceInfo
}

export interface DownloadInstance {
  completed_at?: string
  created_at: string
  error_message?: string
  id: string
  model_id?: string
  progress_data?: DownloadProgressData
  provider_id: string
  repository_id: string
  request_data: DownloadRequestData
  started_at: string
  status: DownloadStatus
  updated_at: string
}

export interface DownloadInstanceListResponse {
  downloads: DownloadInstance[]
  page: number
  per_page: number
  total: number
}

export interface DownloadPaginationQuery {
  page?: number
  per_page?: number
  status?: string
}

export type DownloadPhase = 'created' | 'connecting' | 'analyzing' | 'downloading' | 'receiving' | 'resolving' | 'checkingout' | 'committing' | 'complete' | 'error'

export interface DownloadProgressData {
  current: number
  eta_seconds: number
  message: string
  phase: DownloadPhase
  speed_bps: number
  total: number
}

export interface DownloadProgressUpdate {
  current?: number
  error_message?: string
  eta_seconds?: number
  id: string
  message?: string
  model_id?: string
  phase: DownloadPhase
  provider_id: string
  speed_bps?: number
  status: string
  total?: number
}

export interface DownloadRequestData {
  description?: string
  capabilities?: ModelCapabilities
  display_name?: string
  engine_settings?: ModelEngineSettings
  engine_type?: EngineType
  file_format?: string
  files?: string[]
  main_filename?: string
  model_name: string
  parameters?: ModelParameters
  quantization?: string
  repository_path?: string
  revision?: string
  source?: SourceInfo
}

export type DownloadStatus = 'pending' | 'downloading' | 'completed' | 'failed' | 'cancelled'

export type EngineType = 'mistralrs' | 'llamacpp' | 'none'

export type FileFormat = 'safetensors' | 'pytorch' | 'gguf'

export interface GPUComputeCapabilities {
  cuda_support: boolean
  cuda_version?: string
  metal_support: boolean
  opencl_support: boolean
  vulkan_support?: boolean
}

export interface GPUDevice {
  compute_capabilities: GPUComputeCapabilities
  device_id: string
  driver_version?: string
  memory?: number
  name: string
  vendor: string
}

export interface GPUUsage {
  device_id: string
  device_name: string
  memory_total?: number
  memory_usage_percentage?: number
  memory_used?: number
  power_usage?: number
  temperature?: number
  utilization_percentage?: number
}

export interface Group {
  description?: string
  created_at: string
  id: string
  is_active: boolean
  is_default: boolean
  is_system: boolean
  name: string
  permissions: string[]
  updated_at: string
}

export interface GroupListResponse {
  groups: Group[]
  page: number
  per_page: number
  total: number
  total_pages: number
}

export interface HardwareInfo {
  cpu: CPUInfo
  gpu_devices: GPUDevice[]
  memory: MemoryInfo
  operating_system: OperatingSystemInfo
}

export interface HardwareInfoResponse {
  hardware: HardwareInfo
}

export interface HardwareUsageUpdate {
  cpu: CPUUsage
  gpu_devices: GPUUsage[]
  memory: MemoryUsage
  timestamp: string
}

export interface HealthResponse {
  status: string
}

export interface ListModelsQuery {
  page?: number
  perPage?: number
  providerId?: string
}

export interface LlamaCppSettings {
  batch_size?: number
  cache_type_k?: string
  cache_type_v?: string
  cont_batching?: boolean
  ctx_size?: number
  device_ids?: number[]
  device_type?: DeviceType
  flash_attn?: boolean
  keep?: number
  main_gpu?: number
  mlock?: boolean
  n_gpu_layers?: number
  no_kv_offload?: boolean
  no_mmap?: boolean
  numa?: string
  parallel?: number
  rope_freq_base?: number
  rope_freq_scale?: number
  rope_scaling?: string
  seed?: number
  split_mode?: string
  tensor_split?: string
  threads?: number
  threads_batch?: number
  ubatch_size?: number
}

export interface LlmModel {
  description?: string
  capabilities: ModelCapabilities
  created_at: string
  display_name: string
  enabled: boolean
  engine_settings?: ModelEngineSettings
  engine_type: EngineType
  file_format: FileFormat
  file_size_bytes?: number
  id: string
  is_active: boolean
  is_deprecated: boolean
  name: string
  parameters: ModelParameters
  pid?: number
  port?: number
  provider_id: string
  source?: SourceInfo
  updated_at: string
  validation_issues?: string[]
  validation_status?: string
}

export interface LlmModelListResponse {
  models: LlmModel[]
  page: number
  per_page: number
  total: number
}

export interface LlmProvider {
  api_key?: string
  base_url?: string
  built_in: boolean
  created_at: string
  enabled: boolean
  id: string
  name: string
  provider_type: string
  proxy_settings: ProxySettings
  updated_at: string
}

export interface LlmProviderListResponse {
  page: number
  per_page: number
  providers: LlmProvider[]
  total: number
}

export interface LlmRepository {
  auth_config: RepositoryAuthConfig
  auth_type: string
  built_in: boolean
  created_at: string
  enabled: boolean
  id: string
  name: string
  updated_at: string
  url: string
}

export interface LlmRepositoryListResponse {
  page: number
  per_page: number
  repositories: LlmRepository[]
  total: number
}

export interface LoginRequest {
  password: string
  provider?: string
  username: string
}

export interface MeResponse {
  permissions: string[]
  user: User
}

export interface MemoryInfo {
  total_ram: number
  total_swap?: number
}

export interface MemoryUsage {
  available_ram: number
  available_swap?: number
  usage_percentage: number
  used_ram: number
  used_swap?: number
}

export type MistralRsCommand = 'plain' | 'gguf' | 'run' | 'vision-plain' | 'x-lora' | 'lora' | 'toml'

export interface MistralRsSettings {
  arch?: string
  chat_template?: string
  command?: MistralRsCommand
  cpu?: boolean
  device_ids?: number[]
  device_type?: DeviceType
  dtype?: string
  enable_search?: boolean
  enable_thinking?: boolean
  in_situ_quant?: string
  interactive_mode?: boolean
  jinja_explicit?: string
  log_file?: string
  max_edge?: number
  max_image_length?: number
  max_num_images?: number
  max_seq_len?: number
  max_seqs?: number
  model_id_name?: string
  no_kv_cache?: boolean
  no_paged_attn?: boolean
  num_device_layers?: string[]
  paged_attn?: boolean
  paged_attn_block_size?: number
  paged_attn_gpu_mem?: number
  paged_attn_gpu_mem_usage?: number
  paged_ctxt_len?: number
  prefix_cache_n?: number
  prompt_chunksize?: number
  quantized_filename?: string
  search_bert_model?: string
  seed?: number
  serve_ip?: string
  token_source?: string
  tokenizer_json?: string
  truncate_sequence?: boolean
  weight_file?: string
}

export interface ModelCapabilities {
  audio?: boolean
  chat?: boolean
  code_interpreter?: boolean
  image_generator?: boolean
  text_embedding?: boolean
  tools?: boolean
  vision?: boolean
}

export interface ModelEngineSettings {
  llamacpp?: LlamaCppSettings
  mistralrs?: MistralRsSettings
}

export interface ModelParameters {
  frequency_penalty?: number
  max_tokens?: number
  min_p?: number
  presence_penalty?: number
  repeat_last_n?: number
  repeat_penalty?: number
  seed?: number
  stop?: string[]
  temperature?: number
  top_k?: number
  top_p?: number
}

export interface OperatingSystemInfo {
  architecture: string
  kernel_version?: string
  name: string
  version: string
}

export interface PaginationQuery {
  page?: number
  per_page?: number
}

export interface PermissionDetail {
  description: string
  name: string
  value: string
}

export interface PermissionError {
  details: PermissionErrorDetails
  error: string
  error_code: string
}

export interface PermissionErrorDetails {
  required_permissions: PermissionDetail[]
}

export interface ProxySettings {
  enabled?: boolean
  ignore_ssl_certificates?: boolean
  no_proxy?: string
  password?: string
  url?: string
  username?: string
}

export interface RefreshTokenRequest {
  refresh_token: string
}

export interface RegisterRequest {
  display_name?: string
  email: string
  password: string
  username: string
}

export interface RepositoryAuthConfig {
  api_key?: string
  auth_test_api_endpoint?: string
  password?: string
  token?: string
  username?: string
}

export interface ResetPasswordRequest {
  new_password: string
  user_id: string
}

export interface SSEDownloadProgressConnectedData {
  message?: string
}

export type SSEDownloadProgressEvent = {
  connected: SSEDownloadProgressConnectedData
  update: DownloadProgressUpdate[]
  complete: string
  error: string
}

export interface SSEHardwareUsageConnectedData {
  message: string
}

export type SSEHardwareUsageEvent = {
  connected: SSEHardwareUsageConnectedData
  update: HardwareUsageUpdate
}

export interface SetupAdminRequest {
  display_name?: string
  email: string
  password: string
  username: string
}

export interface SetupStatusResponse {
  app_name: string
  needs_setup: boolean
  version: string
}

export interface SourceInfo {
  type: string
  id?: string
}

export interface TestRepositoryConnectionRequest {
  auth_config?: RepositoryAuthConfig
  auth_type: string
  name: string
  url: string
}

export interface TestRepositoryConnectionResponse {
  message: string
  success: boolean
}

export interface TokenPair {
  access_token: string
  expires_in: number
  refresh_token: string
  token_type: string
}

export interface UpdateGroupRequest {
  description?: string
  is_active?: boolean
  name?: string
  permissions?: string[]
}

export interface UpdateLlmModelRequest {
  description?: string
  capabilities?: ModelCapabilities
  display_name?: string
  enabled?: boolean
  engine_settings?: ModelEngineSettings
  engine_type?: EngineType
  file_format?: FileFormat
  is_active?: boolean
  name?: string
  parameters?: ModelParameters
}

export interface UpdateLlmProviderRequest {
  api_key?: string
  base_url?: string
  enabled?: boolean
  name?: string
  proxy_settings?: ProxySettings
}

export interface UpdateLlmRepositoryRequest {
  auth_config?: RepositoryAuthConfig
  auth_type?: string
  enabled?: boolean
  name?: string
  url?: string
}

export interface UpdateUserRequest {
  display_name?: string
  email?: string
  is_active?: boolean
  username?: string
}

export interface User {
  avatar_url?: string
  created_at: string
  display_name?: string
  email: string
  email_verified: boolean
  id: string
  is_active: boolean
  last_login_at?: string
  updated_at: string
  username: string
}

export interface UserActiveStatusResponse {
  is_active: boolean
  user_id: string
}

export interface UserListResponse {
  page: number
  per_page: number
  total: number
  total_pages: number
  users: User[]
}

// =============================================================================
// API ENDPOINTS
// =============================================================================

// API endpoint definitions
export const ApiEndpoints = {
  'App.getSetupStatus': 'GET /api/app/setup/status',
  'App.setupAdmin': 'POST /api/app/setup/admin',
  'Auth.login': 'POST /api/auth/login',
  'Auth.logout': 'POST /api/auth/logout',
  'Auth.me': 'GET /api/auth/me',
  'Auth.refresh': 'POST /api/auth/refresh',
  'Auth.register': 'POST /api/auth/register',
  'Hardware.info': 'GET /api/hardware',
  'Hardware.stream': 'GET /api/hardware/usage-stream',
  'Health.check': 'GET /api/health',
  'LlmModel.cancelDownload': 'POST /api/llm-models/downloads/{download_id}/cancel',
  'LlmModel.create': 'POST /api/llm-models',
  'LlmModel.delete': 'DELETE /api/llm-models/{model_id}',
  'LlmModel.deleteDownload': 'DELETE /api/llm-models/downloads/{download_id}',
  'LlmModel.disable': 'POST /api/llm-models/{model_id}/disable',
  'LlmModel.download': 'POST /api/llm-models/download',
  'LlmModel.enable': 'POST /api/llm-models/{model_id}/enable',
  'LlmModel.get': 'GET /api/llm-models/{model_id}',
  'LlmModel.getDownload': 'GET /api/llm-models/downloads/{download_id}',
  'LlmModel.list': 'GET /api/llm-models',
  'LlmModel.listDownloads': 'GET /api/llm-models/downloads',
  'LlmModel.subscribeDownloadProgress': 'GET /api/llm-models/downloads/subscribe',
  'LlmModel.update': 'POST /api/llm-models/{model_id}',
  'LlmModel.upload': 'POST /api/llm-models/upload',
  'LlmProvider.assignGroup': 'POST /api/llm-providers/assign-group',
  'LlmProvider.create': 'POST /api/llm-providers',
  'LlmProvider.delete': 'DELETE /api/llm-providers/{provider_id}',
  'LlmProvider.get': 'GET /api/llm-providers/{provider_id}',
  'LlmProvider.getGroups': 'GET /api/llm-providers/{provider_id}/groups',
  'LlmProvider.list': 'GET /api/llm-providers',
  'LlmProvider.removeGroup': 'DELETE /api/llm-providers/{provider_id}/{group_id}/remove-group',
  'LlmProvider.update': 'POST /api/llm-providers/{provider_id}',
  'LlmRepository.create': 'POST /api/llm-repositories',
  'LlmRepository.delete': 'DELETE /api/llm-repositories/{repository_id}',
  'LlmRepository.get': 'GET /api/llm-repositories/{repository_id}',
  'LlmRepository.list': 'GET /api/llm-repositories',
  'LlmRepository.test': 'POST /api/llm-repositories/test',
  'LlmRepository.update': 'POST /api/llm-repositories/{repository_id}',
  'User.create': 'POST /api/users',
  'User.delete': 'DELETE /api/users/{user_id}',
  'User.get': 'GET /api/users/{user_id}',
  'User.list': 'GET /api/users',
  'User.resetPassword': 'POST /api/users/reset-password',
  'User.toggleActive': 'POST /api/users/{user_id}/toggle-active',
  'User.update': 'POST /api/users/{user_id}',
  'UserGroup.assignUser': 'POST /api/groups/assign',
  'UserGroup.create': 'POST /api/groups',
  'UserGroup.delete': 'DELETE /api/groups/{group_id}',
  'UserGroup.get': 'GET /api/groups/{group_id}',
  'UserGroup.getMembers': 'GET /api/groups/{group_id}/members',
  'UserGroup.list': 'GET /api/groups',
  'UserGroup.removeUser': 'DELETE /api/groups/{user_id}/{group_id}/remove',
  'UserGroup.update': 'POST /api/groups/{group_id}'
} as const

// API endpoint parameters
export type ApiEndpointParameters = {
  'App.getSetupStatus': void
  'App.setupAdmin': SetupAdminRequest
  'Auth.login': LoginRequest
  'Auth.logout': void
  'Auth.me': void
  'Auth.refresh': RefreshTokenRequest
  'Auth.register': RegisterRequest
  'Hardware.info': void
  'Hardware.stream': void
  'Health.check': void
  'LlmModel.cancelDownload': { download_id: string }
  'LlmModel.create': CreateLlmModelRequest
  'LlmModel.delete': { model_id: string }
  'LlmModel.deleteDownload': { download_id: string }
  'LlmModel.disable': { model_id: string }
  'LlmModel.download': DownloadFromRepositoryRequest
  'LlmModel.enable': { model_id: string }
  'LlmModel.get': { model_id: string }
  'LlmModel.getDownload': { download_id: string }
  'LlmModel.list': { page?: number; perPage?: number; providerId?: string }
  'LlmModel.listDownloads': { page?: number; per_page?: number; status?: string }
  'LlmModel.subscribeDownloadProgress': void
  'LlmModel.update': { model_id: string } & UpdateLlmModelRequest
  'LlmModel.upload': FormData
  'LlmProvider.assignGroup': AssignProviderToGroupRequest
  'LlmProvider.create': CreateLlmProviderRequest
  'LlmProvider.delete': { provider_id: string }
  'LlmProvider.get': { provider_id: string }
  'LlmProvider.getGroups': { provider_id: string }
  'LlmProvider.list': PaginationQuery
  'LlmProvider.removeGroup': { provider_id: string; group_id: string }
  'LlmProvider.update': { provider_id: string } & UpdateLlmProviderRequest
  'LlmRepository.create': CreateLlmRepositoryRequest
  'LlmRepository.delete': { repository_id: string }
  'LlmRepository.get': { repository_id: string }
  'LlmRepository.list': PaginationQuery
  'LlmRepository.test': TestRepositoryConnectionRequest
  'LlmRepository.update': { repository_id: string } & UpdateLlmRepositoryRequest
  'User.create': CreateUserRequest
  'User.delete': { user_id: string }
  'User.get': { user_id: string }
  'User.list': PaginationQuery
  'User.resetPassword': ResetPasswordRequest
  'User.toggleActive': { user_id: string }
  'User.update': { user_id: string } & UpdateUserRequest
  'UserGroup.assignUser': AssignUserToGroupRequest
  'UserGroup.create': CreateGroupRequest
  'UserGroup.delete': { group_id: string }
  'UserGroup.get': { group_id: string }
  'UserGroup.getMembers': { group_id: string } & PaginationQuery
  'UserGroup.list': PaginationQuery
  'UserGroup.removeUser': { user_id: string; group_id: string }
  'UserGroup.update': { group_id: string } & UpdateGroupRequest
}

// API endpoint responses
export type ApiEndpointResponses = {
  'App.getSetupStatus': SetupStatusResponse
  'App.setupAdmin': AuthResponse
  'Auth.login': AuthResponse
  'Auth.logout': void
  'Auth.me': MeResponse
  'Auth.refresh': TokenPair
  'Auth.register': AuthResponse
  'Hardware.info': HardwareInfoResponse
  'Hardware.stream': SSEHardwareUsageEvent
  'Health.check': HealthResponse
  'LlmModel.cancelDownload': void
  'LlmModel.create': LlmModel
  'LlmModel.delete': void
  'LlmModel.deleteDownload': void
  'LlmModel.disable': LlmModel
  'LlmModel.download': DownloadInstance
  'LlmModel.enable': LlmModel
  'LlmModel.get': LlmModel
  'LlmModel.getDownload': DownloadInstance
  'LlmModel.list': LlmModelListResponse
  'LlmModel.listDownloads': DownloadInstanceListResponse
  'LlmModel.subscribeDownloadProgress': SSEDownloadProgressEvent
  'LlmModel.update': LlmModel
  'LlmModel.upload': LlmModel
  'LlmProvider.assignGroup': void
  'LlmProvider.create': LlmProvider
  'LlmProvider.delete': void
  'LlmProvider.get': LlmProvider
  'LlmProvider.getGroups': Group[]
  'LlmProvider.list': LlmProviderListResponse
  'LlmProvider.removeGroup': void
  'LlmProvider.update': LlmProvider
  'LlmRepository.create': LlmRepository
  'LlmRepository.delete': void
  'LlmRepository.get': LlmRepository
  'LlmRepository.list': LlmRepositoryListResponse
  'LlmRepository.test': TestRepositoryConnectionResponse
  'LlmRepository.update': LlmRepository
  'User.create': User
  'User.delete': void
  'User.get': User
  'User.list': UserListResponse
  'User.resetPassword': void
  'User.toggleActive': UserActiveStatusResponse
  'User.update': User
  'UserGroup.assignUser': void
  'UserGroup.create': Group
  'UserGroup.delete': void
  'UserGroup.get': Group
  'UserGroup.getMembers': UserListResponse
  'UserGroup.list': GroupListResponse
  'UserGroup.removeUser': void
  'UserGroup.update': Group
}

// Type helpers
export type ApiEndpoint = keyof typeof ApiEndpoints
export type ApiEndpointUrl = (typeof ApiEndpoints)[ApiEndpoint]

// Extract endpoint key from URL pattern
export function getEndpointKey(url: string): ApiEndpoint | undefined {
  const entries = Object.entries(ApiEndpoints) as [ApiEndpoint, string][]
  const found = entries.find(([_key, value]) => value === url)
  return found ? found[0] : undefined
}

// Get parameter type for endpoint
export type GetParameterType<K extends ApiEndpoint> = ApiEndpointParameters[K]

// Get response type for endpoint  
export type GetResponseType<K extends ApiEndpoint> = ApiEndpointResponses[K]

// Create reverse mapping from URL to endpoint key
export type UrlToEndpoint<U extends ApiEndpointUrl> = {
  [K in keyof typeof ApiEndpoints]: (typeof ApiEndpoints)[K] extends U
    ? K
    : never
}[keyof typeof ApiEndpoints]

// Helper types to get parameter and response types by URL
export type ParameterByUrl<U extends ApiEndpointUrl> =
  ApiEndpointParameters[UrlToEndpoint<U>]
export type ResponseByUrl<U extends ApiEndpointUrl> =
  ApiEndpointResponses[UrlToEndpoint<U>]

// Type-safe validation - this will cause a TypeScript error if any endpoint is missing
type ValidateParametersComplete = {
  [K in keyof typeof ApiEndpoints]: K extends keyof ApiEndpointParameters
    ? true
    : false
}

type ValidateResponsesComplete = {
  [K in keyof typeof ApiEndpoints]: K extends keyof ApiEndpointResponses
    ? true
    : false
}

// Type-safe validation - these will cause a TypeScript error if any endpoint is missing
// from Parameters or Responses. They are used for compile-time validation only.
export type { ValidateParametersComplete, ValidateResponsesComplete }
