// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  clearError: typeof import('./actions/clearError')['default']
  deleteVersion: typeof import('./actions/deleteVersion')['default']
  getDefaultVersion: typeof import('./actions/getDefaultVersion')['default']
  loadVersions: typeof import('./actions/loadVersions')['default']
  setDefaultVersion: typeof import('./actions/setDefaultVersion')['default']
  syncCache: typeof import('./actions/syncCache')['default']
}
