// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  bulkDelete: typeof import('./actions/bulkDelete')['default']
  clearRecentError: typeof import('./actions/clearRecentError')['default']
  deleteConversation: typeof import('./actions/deleteConversation')['default']
  deselectAll: typeof import('./actions/deselectAll')['default']
  loadConversations: typeof import('./actions/loadConversations')['default']
  loadMoreRecent: typeof import('./actions/loadMoreRecent')['default']
  loadNextPage: typeof import('./actions/loadNextPage')['default']
  loadRecentConversations: typeof import('./actions/loadRecentConversations')['default']
  refillRecentIfEmptied: typeof import('./actions/refillRecentIfEmptied')['default']
  refreshConversations: typeof import('./actions/refreshConversations')['default']
  selectAll: typeof import('./actions/selectAll')['default']
  setSearchQuery: typeof import('./actions/setSearchQuery')['default']
  setSort: typeof import('./actions/setSort')['default']
  syncRecentFront: typeof import('./actions/syncRecentFront')['default']
  toggleSelection: typeof import('./actions/toggleSelection')['default']
  updateConversationTitle: typeof import('./actions/updateConversationTitle')['default']
}
