// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  closeAddLocalLlmModelUploadDrawer: typeof import('./actions/closeAddLocalLlmModelUploadDrawer')['default']
  openAddLocalLlmModelUploadDrawer: typeof import('./actions/openAddLocalLlmModelUploadDrawer')['default']
  setAddLocalLlmModelUploadDrawerLoading: typeof import('./actions/setAddLocalLlmModelUploadDrawerLoading')['default']
}
