// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  checkSetupStatus: typeof import('./actions/checkSetupStatus')['default']
  clearSetupError: typeof import('./actions/clearSetupError')['default']
  setupAdmin: typeof import('./actions/setupAdmin')['default']
}
