//! Integration tests for MCP content data types (McpContentData, etc.)

use ziee::{McpContentData, ResourceLink, RichFile};

#[test]
fn test_tool_use_conversion() {
    let tool_use = McpContentData::ToolUse {
        id: "toolu_01".to_string(),
        name: "get_weather".to_string(),
        server_id: "550e8400-e29b-41d4-a716-446655440000".to_string(),
        input: serde_json::json!({"location": "SF"}),
    };

    // Convert to MessageContentData
    let msg_content = tool_use.to_message_content();
    // Verify it's a ToolUse variant (MessageContentData variants are generated by macro)
    assert_eq!(msg_content.content_type(), "tool_use");

    // Convert back
    let recovered = McpContentData::from_message_content(&msg_content).unwrap();
    match recovered {
        McpContentData::ToolUse { id, name, server_id, .. } => {
            assert_eq!(id, "toolu_01");
            assert_eq!(name, "get_weather");
            assert_eq!(server_id, "550e8400-e29b-41d4-a716-446655440000");
        }
        _ => panic!("Expected ToolUse"),
    }
}

#[test]
fn test_tool_result_conversion() {
    let tool_result = McpContentData::ToolResult {
        tool_use_id: "toolu_01".to_string(),
        name: Some("get_weather".to_string()),
        content: "Sunny, 72°F".to_string(),
        is_error: Some(false),
        attachment: None,
        images: None,
        server_id: None,
        hidden_content: None,
        structured_content: None,
        resource_links: None,
    };

    // Convert to MessageContentData
    let msg_content = tool_result.to_message_content();

    // Convert back
    let recovered = McpContentData::from_message_content(&msg_content).unwrap();
    match recovered {
        McpContentData::ToolResult {
            tool_use_id,
            name,
            content,
            is_error,
            ..
        } => {
            assert_eq!(tool_use_id, "toolu_01");
            assert_eq!(name, Some("get_weather".to_string()));
            assert_eq!(content, "Sunny, 72°F");
            assert_eq!(is_error, Some(false));
        }
        _ => panic!("Expected ToolResult"),
    }
}

#[test]
fn test_to_content_block() {
    let tool_use = McpContentData::ToolUse {
        id: "toolu_01".to_string(),
        name: "get_weather".to_string(),
        server_id: "550e8400-e29b-41d4-a716-446655440000".to_string(),
        input: serde_json::json!({"location": "SF"}),
    };

    let block = tool_use.to_content_block().unwrap();
    match block {
        ai_providers::ContentBlock::ToolUse { name, .. } => {
            // Should reconstruct server_id__name format
            assert_eq!(name, "550e8400-e29b-41d4-a716-446655440000__get_weather");
        }
        _ => panic!("Expected ToolUse"),
    }
}

#[test]
fn test_from_content_block() {
    // AI providers return server_id__tool_name format
    let block = ai_providers::ContentBlock::ToolUse {
        id: "toolu_01".to_string(),
        name: "550e8400-e29b-41d4-a716-446655440000__get_weather".to_string(),
        input: serde_json::json!({"location": "SF"}),
    };

    let mcp_content = McpContentData::from_content_block(&block).unwrap();
    match mcp_content {
        McpContentData::ToolUse { id, name, server_id, .. } => {
            assert_eq!(id, "toolu_01");
            assert_eq!(name, "get_weather");
            assert_eq!(server_id, "550e8400-e29b-41d4-a716-446655440000");
        }
        _ => panic!("Expected ToolUse"),
    }
}

#[test]
fn test_tool_result_no_sources_section_appended_to_llm() {
    let tool_result = McpContentData::ToolResult {
        tool_use_id: "toolu_04".to_string(),
        name: Some("search".to_string()),
        content: "Simple result".to_string(),
        is_error: Some(false),
        attachment: None,
        images: None,
        server_id: None,
        hidden_content: None,
        structured_content: None,
        resource_links: None,
    };

    let block = tool_result.to_content_block().unwrap();
    match block {
        ai_providers::ContentBlock::ToolResult { content, .. } => {
            let text = content
                .iter()
                .filter_map(|b| match b {
                    ai_providers::ContentBlock::Text { text } => Some(text.as_str()),
                    _ => None,
                })
                .collect::<Vec<_>>()
                .join("");
            assert!(
                !text.contains("Sources:"),
                "Should not contain Sources section"
            );
        }
        _ => panic!("Expected ToolResult"),
    }
}

#[test]
fn test_tool_result_with_attachment_roundtrip() {
    // McpContentData is persisted as JSON in the DB, so test JSON roundtrip
    let tool_result = McpContentData::ToolResult {
        tool_use_id: "toolu_05".to_string(),
        name: Some("generate_chart".to_string()),
        content: "Chart generated".to_string(),
        is_error: Some(false),
        attachment: Some(RichFile {
            filename: "chart.png".to_string(),
            mime_type: "image/png".to_string(),
            data: "base64encodeddata".to_string(),
        }),
        images: None,
        server_id: None,
        hidden_content: None,
        structured_content: None,
        resource_links: None,
    };

    let json = serde_json::to_value(&tool_result).expect("Should serialize");
    let recovered: McpContentData = serde_json::from_value(json).expect("Should deserialize");
    match recovered {
        McpContentData::ToolResult { attachment, .. } => {
            let file = attachment.expect("Attachment should be preserved");
            assert_eq!(file.filename, "chart.png");
            assert_eq!(file.mime_type, "image/png");
            assert_eq!(file.data, "base64encodeddata");
        }
        _ => panic!("Expected ToolResult"),
    }
}

#[test]
fn test_resource_link_file_id_roundtrip() {
    // The UI inline preview reads `resource_links[i].file_id` to render via the
    // authenticated /api/files/{id}/... path. It must survive the JSON
    // round-trip (DB persistence) and serialize into the browser-facing JSON.
    let file_id = uuid::Uuid::new_v4();
    let tool_result = McpContentData::ToolResult {
        tool_use_id: "toolu_06".to_string(),
        name: Some("write_file".to_string()),
        content: "Saved".to_string(),
        is_error: Some(false),
        attachment: None,
        images: None,
        server_id: None,
        hidden_content: None,
        structured_content: None,
        resource_links: Some(vec![ResourceLink {
            uri: "/api/code-sandbox/file/download?filename=plot.R".to_string(),
            name: Some("plot.R".to_string()),
            mime_type: Some("text/plain".to_string()),
            size: Some(42),
            is_saved: Some(false),
            file_id: Some(file_id),
            version_id: None,
            version: None,
        }]),
    };

    let json = serde_json::to_value(&tool_result).expect("Should serialize");
    assert_eq!(
        json["resource_links"][0]["file_id"],
        serde_json::json!(file_id.to_string()),
        "file_id must serialize into the resource_link JSON sent to the browser"
    );

    let recovered: McpContentData = serde_json::from_value(json).expect("Should deserialize");
    match recovered {
        McpContentData::ToolResult { resource_links, .. } => {
            let links = resource_links.expect("resource_links should be preserved");
            assert_eq!(links.len(), 1);
            assert_eq!(links[0].file_id, Some(file_id));
            assert_eq!(links[0].name.as_deref(), Some("plot.R"));
        }
        _ => panic!("Expected ToolResult"),
    }
}

#[test]
fn test_resource_link_file_id_omitted_when_absent() {
    // External MCP links have no backing File — file_id must be skipped in JSON
    // (it's `#[serde(skip_serializing_if = "Option::is_none")]`).
    let link = ResourceLink {
        uri: "https://example.com/report.pdf".to_string(),
        name: Some("report.pdf".to_string()),
        mime_type: None,
        size: None,
        is_saved: None,
        file_id: None,
        version_id: None,
        version: None,
    };
    let json = serde_json::to_value(&link).expect("Should serialize");
    assert!(
        json.get("file_id").is_none(),
        "file_id should be omitted when None, got: {json}"
    );
}

#[test]
fn test_resource_link_version_pinning_roundtrip() {
    // A versioned backing File (e.g. a sandbox version-back) pins version_id +
    // version on the resource_link so the UI renders the exact version produced.
    let version_id = uuid::Uuid::new_v4();
    let link = ResourceLink {
        uri: "/api/files/abc".to_string(),
        name: Some("report.md".to_string()),
        mime_type: Some("text/markdown".to_string()),
        size: Some(10),
        is_saved: Some(true),
        file_id: Some(uuid::Uuid::new_v4()),
        version_id: Some(version_id),
        version: Some(3),
    };
    let json = serde_json::to_value(&link).expect("serialize");
    assert_eq!(json["version_id"], serde_json::json!(version_id.to_string()));
    assert_eq!(json["version"], serde_json::json!(3));

    let back: ResourceLink = serde_json::from_value(json).expect("deserialize");
    assert_eq!(back.version_id, Some(version_id));
    assert_eq!(back.version, Some(3));
}

#[test]
fn test_resource_link_version_omitted_when_none() {
    // A non-versioned / legacy link omits the version fields entirely so old
    // blocks (and external MCP links) deserialize unchanged.
    let link = ResourceLink {
        uri: "/api/files/abc".to_string(),
        name: None,
        mime_type: None,
        size: None,
        is_saved: None,
        file_id: None,
        version_id: None,
        version: None,
    };
    let json = serde_json::to_value(&link).expect("serialize");
    assert!(json.get("version_id").is_none(), "version_id omitted when None: {json}");
    assert!(json.get("version").is_none(), "version omitted when None: {json}");
}

/// An ERROR tool_result block — the shape `execute_tool` produces on its
/// `Ok(Err(e))` (transport/tool error) and `Err(_)` (timeout) branches
/// (`mcp/chat_extension/helpers.rs:586,611`): `is_error: Some(true)` with a
/// "Tool execution failed: …" content. Every existing tool_result test uses
/// `is_error: Some(false)`, so the error variant's two production round-trips
/// were untested:
///   1. PERSISTENCE — what `message_contents` stores and re-reads
///      (`to_message_content` → `from_message_content`). The error flag and the
///      diagnostic text MUST survive verbatim (a regression that dropped/forced
///      `is_error` would silently turn a failed tool call into a "successful"
///      one the model trusts).
///   2. LLM SURFACING — `to_content_block` must hand the model an
///      `ai_providers::ContentBlock::ToolResult { is_error: Some(true) }` so the
///      assistant sees the failure (and can retry), and `from_content_block`
///      must read it back unchanged.
#[test]
fn test_error_tool_result_block_roundtrips_and_surfaces_to_llm() {
    let err_block = McpContentData::ToolResult {
        tool_use_id: "toolu_err_01".to_string(),
        name: Some("flaky_search".to_string()),
        server_id: None,
        content: "Tool execution failed: upstream returned 503".to_string(),
        is_error: Some(true),
        attachment: None,
        images: None,
        resource_links: None,
        hidden_content: None,
        structured_content: None,
    };

    // (1) Persistence round-trip: the error flag + content survive verbatim.
    let stored = err_block.to_message_content();
    let recovered = McpContentData::from_message_content(&stored)
        .expect("error tool_result must deserialize from a persisted message_content");
    match recovered {
        McpContentData::ToolResult { content, is_error, name, .. } => {
            assert_eq!(
                is_error,
                Some(true),
                "is_error=true must survive the persistence round-trip (not be dropped/coerced)"
            );
            assert_eq!(content, "Tool execution failed: upstream returned 503");
            assert_eq!(name.as_deref(), Some("flaky_search"));
        }
        other => panic!("expected ToolResult, got {other:?}"),
    }

    // (2) LLM-surfacing round-trip: the model receives is_error=Some(true) with
    // the diagnostic text, and reading the block back preserves the flag.
    let block = err_block
        .to_content_block()
        .expect("error tool_result must convert to an ai-providers content block");
    match &block {
        ai_providers::ContentBlock::ToolResult { is_error, content, .. } => {
            assert_eq!(
                *is_error,
                Some(true),
                "the LLM-facing ToolResult must carry is_error=true so the model sees the failure"
            );
            let text = content
                .iter()
                .filter_map(|b| match b {
                    ai_providers::ContentBlock::Text { text } => Some(text.as_str()),
                    _ => None,
                })
                .collect::<Vec<_>>()
                .join("");
            assert!(
                text.contains("Tool execution failed"),
                "the error diagnostic must reach the model, got: {text}"
            );
        }
        _ => panic!("expected ContentBlock::ToolResult"),
    }

    let back = McpContentData::from_content_block(&block)
        .expect("error content block must convert back to McpContentData");
    match back {
        McpContentData::ToolResult { is_error, .. } => {
            assert_eq!(is_error, Some(true), "is_error=true must survive the content-block round-trip");
        }
        other => panic!("expected ToolResult, got {other:?}"),
    }
}
