// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  attachConversation: typeof import('./actions/attachConversation')['default']
  clearProjectsError: typeof import('./actions/clearProjectsError')['default']
  createProject: typeof import('./actions/createProject')['default']
  deleteProject: typeof import('./actions/deleteProject')['default']
  detachConversation: typeof import('./actions/detachConversation')['default']
  duplicateProject: typeof import('./actions/duplicateProject')['default']
  loadProjects: typeof import('./actions/loadProjects')['default']
  updateProject: typeof import('./actions/updateProject')['default']
}
