// Procedural macros for Ziee Chat
//
// This crate provides various procedural macros used throughout the application.

use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, ItemEnum, ItemStruct};

// Embed the generated extensions code at compile time
// This is generated by build.rs and included here
const EXTENSIONS_CODE: &str = include_str!(concat!(env!("OUT_DIR"), "/chat_extensions.rs"));

/// Macro to include the auto-generated extension registration code
/// This expands to the entire generated module content
#[proc_macro]
pub fn include_chat_extensions(_item: TokenStream) -> TokenStream {
    EXTENSIONS_CODE.parse().unwrap()
}

/// Attribute macro to compose all discovered chat extension request fields
///
/// This macro automatically discovers all extension.rs files in modules/chat/**/
/// parses their SendMessageRequestFields, and adds the fields directly to the target struct.
///
/// Usage:
/// ```
/// #[compose_chat_extensions]
/// pub struct SendMessageRequest {
///     pub content: String,
///     pub parent_id: Option<Uuid>,
/// }
/// ```
///
/// Extensions are discovered by the build script and fields are added directly.
#[proc_macro_attribute]
pub fn compose_chat_extensions(_attr: TokenStream, item: TokenStream) -> TokenStream {
    compose_fields(item, "REQUEST_FIELDS")
}

/// Attribute macro to compose all discovered chat extension response fields
///
/// This macro automatically discovers all extension.rs files in modules/chat/**/
/// parses their ChatStreamChunkFields, and adds the fields directly to the target struct.
///
/// Usage:
/// ```
/// #[compose_chat_stream_chunk_extensions]
/// pub struct ChatStreamChunk {
///     pub content: Vec<ContentBlockDelta>,
///     pub message_id: Option<Uuid>,
/// }
/// ```
///
/// Extensions are discovered by the build script and fields are added directly.
#[proc_macro_attribute]
pub fn compose_chat_stream_chunk_extensions(_attr: TokenStream, item: TokenStream) -> TokenStream {
    compose_fields(item, "RESPONSE_FIELDS")
}

/// Attribute macro to compose ContentBlockDelta enum variants from extensions
///
/// This macro automatically discovers all extension.rs files in modules/chat/**/
/// parses their ContentBlockDeltaVariants, and adds the variants to the target enum.
///
/// Usage:
/// ```
/// #[compose_content_block_delta_variants]
/// pub enum ContentBlockDelta {
///     TextDelta { index: usize, delta: String },
///     ThinkingDelta { index: usize, delta: String },
/// }
/// ```
///
/// Extensions are discovered by the build script and variants are added directly.
#[proc_macro_attribute]
pub fn compose_content_block_delta_variants(_attr: TokenStream, item: TokenStream) -> TokenStream {
    compose_enum_variants(item, "DELTA_VARIANTS")
}

/// Attribute macro to compose MessageContentData enum variants from extensions
///
/// This macro automatically discovers all extension.rs files in modules/chat/**/
/// parses their MessageContentDataVariants, and adds the variants to the target enum.
///
/// Usage:
/// ```
/// #[compose_message_content_variants]
/// pub enum MessageContentData {
///     Text { text: String },
///     Thinking { thinking: String, metadata: Option<ThinkingMetadata> },
/// }
/// ```
///
/// Extensions are discovered by the build script and variants are added directly.
#[proc_macro_attribute]
pub fn compose_message_content_variants(_attr: TokenStream, item: TokenStream) -> TokenStream {
    compose_enum_variants(item, "CONTENT_VARIANTS")
}

/// Attribute macro to compose SSEChatStreamEvent enum variants from extensions
///
/// This macro automatically discovers all extension.rs files in modules/chat/**/
/// parses their SSEChatStreamEventVariants, and adds the variants to the target enum.
///
/// Usage:
/// ```
/// #[compose_chat_stream_events]
/// pub enum SSEChatStreamEvent {
///     Content(ChatStreamChunk),
///     Complete(SSEChatStreamCompleteData),
///     Error(SSEChatStreamErrorData),
/// }
/// ```
///
/// Extensions are discovered by the build script and variants are added directly.
#[proc_macro_attribute]
pub fn compose_chat_stream_events(_attr: TokenStream, item: TokenStream) -> TokenStream {
    compose_enum_variants(item, "STREAM_EVENT_VARIANTS")
}

/// Helper function to compose enum variants from generated code
fn compose_enum_variants(item: TokenStream, const_name: &str) -> TokenStream {
    let mut item_enum = parse_macro_input!(item as ItemEnum);

    // Parse extension enum variant definitions from the embedded code
    let extension_variants: Vec<syn::Variant> = EXTENSIONS_CODE
        .lines()
        .skip_while(|line| !line.contains(const_name))  // Skip until we find the right const
        .skip(1)  // Skip the const declaration line
        .take_while(|line| !line.contains("];"))  // Take until end of array
        .filter_map(|line| {
            let trimmed = line.trim();
            // Look for lines that end with "," (variant definitions)
            if trimmed.ends_with(',') && !trimmed.starts_with("//") {
                // Remove trailing comma and wrap in enum for parsing
                let variant_str = trimmed.trim_end_matches(',');
                let wrapped = format!("enum Dummy {{ {} }}", variant_str);

                // Parse as enum and extract the variant
                if let Ok(parsed_enum) = syn::parse_str::<syn::ItemEnum>(&wrapped) {
                    return parsed_enum.variants.into_iter().next();
                }
                None
            } else {
                None
            }
        })
        .collect();

    // Add extension variants to the enum
    for variant in extension_variants {
        item_enum.variants.push(variant);
    }

    quote! {
        #item_enum
    }
    .into()
}

/// Helper function to compose fields from generated code
fn compose_fields(item: TokenStream, const_name: &str) -> TokenStream {
    let mut item_struct = parse_macro_input!(item as ItemStruct);

    // Parse extension field definitions from the embedded code
    let extension_fields: Vec<syn::Field> = EXTENSIONS_CODE
        .lines()
        .skip_while(|line| !line.contains(const_name))  // Skip until we find the right const
        .skip(1)  // Skip the const declaration line
        .take_while(|line| !line.contains("];"))  // Take until end of array
        .filter_map(|line| {
            let trimmed = line.trim();
            // Look for lines that end with "," (field definitions)
            if trimmed.ends_with(',') && !trimmed.starts_with("//") {
                // Remove trailing comma and wrap in struct for parsing
                let field_str = trimmed.trim_end_matches(',');
                let wrapped = format!("struct Dummy {{ {} }}", field_str);

                // Parse as struct and extract the field
                if let Ok(parsed_struct) = syn::parse_str::<syn::ItemStruct>(&wrapped) {
                    if let syn::Fields::Named(fields_named) = parsed_struct.fields {
                        return fields_named.named.into_iter().next();
                    }
                }
                None
            } else {
                None
            }
        })
        .collect();

    // Add extension fields directly to the struct
    if let syn::Fields::Named(ref mut fields) = item_struct.fields {
        for field in extension_fields {
            fields.named.push(field);
        }
    }

    quote! {
        #item_struct
    }
    .into()
}

// Note: register_chat_extension and register_repositories macros removed
// - Extension registration now uses linkme distributed slices
// - Repository registration now uses linkme distributed slices
