// Procedural macros for Ziee Chat
//
// This crate provides various procedural macros used throughout the application.

use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, ItemStruct};

// Embed the generated extensions code at compile time
// This is generated by build.rs and included here
const EXTENSIONS_CODE: &str = include_str!(concat!(env!("OUT_DIR"), "/chat_extensions.rs"));

/// Macro to include the auto-generated extension registration code
/// This expands to the entire generated module content
#[proc_macro]
pub fn include_chat_extensions(_item: TokenStream) -> TokenStream {
    EXTENSIONS_CODE.parse().unwrap()
}

/// Attribute macro to compose all discovered chat extensions into a request struct
///
/// This macro automatically discovers all extension.rs files in modules/chat/**/
/// parses their RequestFields, and adds the fields directly to the target struct.
///
/// Usage:
/// ```
/// #[compose_chat_extensions]
/// pub struct SendMessageRequest {
///     pub content: String,
///     pub parent_id: Option<Uuid>,
/// }
/// ```
///
/// Extensions are discovered by the build script and fields are added directly.
#[proc_macro_attribute]
pub fn compose_chat_extensions(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let mut item_struct = parse_macro_input!(item as ItemStruct);

    // Parse extension field definitions from the embedded code
    // The code contains: pub const EXTENSION_FIELDS: &[&str] = ["field1", "field2", ...];
    let extension_fields: Vec<syn::Field> = EXTENSIONS_CODE
        .lines()
        .filter_map(|line| {
            let trimmed = line.trim();
            // Look for lines that end with "," (field definitions)
            if trimmed.ends_with(',') && !trimmed.starts_with("//") && !trimmed.starts_with("pub const") && !trimmed.starts_with(']') {
                // Remove trailing comma and wrap in struct for parsing
                let field_str = trimmed.trim_end_matches(',');
                let wrapped = format!("struct Dummy {{ {} }}", field_str);

                // Parse as struct and extract the field
                if let Ok(parsed_struct) = syn::parse_str::<syn::ItemStruct>(&wrapped) {
                    if let syn::Fields::Named(fields_named) = parsed_struct.fields {
                        return fields_named.named.into_iter().next();
                    }
                }
                None
            } else {
                None
            }
        })
        .collect();

    // Add extension fields directly to the struct
    if let syn::Fields::Named(ref mut fields) = item_struct.fields {
        for field in extension_fields {
            fields.named.push(field);
        }
    }

    quote! {
        #item_struct
    }
    .into()
}

/// Marker attribute for chat extensions (documentation purposes)
///
/// Usage in extension modules:
/// ```
/// // In modules/chat/assistant/extension.rs
/// pub struct RequestFields {
///     pub assistant_id: Option<Uuid>,
/// }
/// ```
#[proc_macro_attribute]
pub fn register_chat_extension(_attr: TokenStream, item: TokenStream) -> TokenStream {
    // This is primarily a marker for documentation
    // The actual discovery happens via build script scanning for extension.rs files
    item
}
