// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  cleanupSse: typeof import('./actions/cleanupSse')['default']
  deleteArtifact: typeof import('./actions/deleteArtifact')['default']
  installVersion: typeof import('./actions/installVersion')['default']
  loadStatus: typeof import('./actions/loadStatus')['default']
  setPin: typeof import('./actions/setPin')['default']
  subscribeToInstallProgress: typeof import('./actions/subscribeToInstallProgress')['default']
}
