// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  create: typeof import('./actions/create')['default']
  emitMemoryAllCleared: typeof import('./actions/emitMemoryAllCleared')['default']
  emitMemoryCreated: typeof import('./actions/emitMemoryCreated')['default']
  emitMemoryDeleted: typeof import('./actions/emitMemoryDeleted')['default']
  emitMemoryUpdated: typeof import('./actions/emitMemoryUpdated')['default']
  load: typeof import('./actions/load')['default']
  remove: typeof import('./actions/remove')['default']
  removeAll: typeof import('./actions/removeAll')['default']
  reset: typeof import('./actions/reset')['default']
  setKindFilter: typeof import('./actions/setKindFilter')['default']
  setSearchQuery: typeof import('./actions/setSearchQuery')['default']
  setSourceFilter: typeof import('./actions/setSourceFilter')['default']
  update: typeof import('./actions/update')['default']
}
