// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  applyMcpServerChanges: typeof import('./actions/applyMcpServerChanges')['default']
  loadMcpServers: typeof import('./actions/loadMcpServers')['default']
  reset: typeof import('./actions/reset')['default']
  toggleMcpServer: typeof import('./actions/toggleMcpServer')['default']
  toggleSystemServer: typeof import('./actions/toggleSystemServer')['default']
}
