// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  markFileSeen: typeof import('./actions/markFileSeen')['default']
  resetViewState: typeof import('./actions/resetViewState')['default']
  setFileCollapsed: typeof import('./actions/setFileCollapsed')['default']
  setFileHeight: typeof import('./actions/setFileHeight')['default']
  setMessageCollapsed: typeof import('./actions/setMessageCollapsed')['default']
}
