// Auto-generated chat extension registration
// DO NOT EDIT - Generated by build.rs
//
// Extensions are automatically discovered by scanning extension.rs files
// and registered in order based on their METADATA.order value

use sqlx::PgPool;

use crate::modules::chat::core::extension::ExtensionRegistry;

/// Auto-register all discovered extensions in order
pub fn auto_register_extensions(pool: PgPool) -> ExtensionRegistry {
    let mut registry = ExtensionRegistry::new();

    // assistant (order: 10)
    registry.register(crate::modules::chat::extensions::assistant::extension::create(pool.clone()));
    // title (order: 80)
    registry.register(crate::modules::chat::extensions::title::extension::create(pool.clone()));

    registry
}
