// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  clearTemplateAssistantsStoreError: typeof import('./actions/clearTemplateAssistantsStoreError')['default']
  createTemplateAssistant: typeof import('./actions/createTemplateAssistant')['default']
  deleteTemplateAssistant: typeof import('./actions/deleteTemplateAssistant')['default']
  getTemplateDefaultAssistant: typeof import('./actions/getTemplateDefaultAssistant')['default']
  loadTemplateAssistants: typeof import('./actions/loadTemplateAssistants')['default']
  updateTemplateAssistant: typeof import('./actions/updateTemplateAssistant')['default']
}
