// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  batchRemove: typeof import('./actions/batchRemove')['default']
  clearSearch: typeof import('./actions/clearSearch')['default']
  deselectAll: typeof import('./actions/deselectAll')['default']
  dismissUploadingFile: typeof import('./actions/dismissUploadingFile')['default']
  load: typeof import('./actions/load')['default']
  loadDocuments: typeof import('./actions/loadDocuments')['default']
  loadDocumentsPage: typeof import('./actions/loadDocumentsPage')['default']
  loadRetrievalInfo: typeof import('./actions/loadRetrievalInfo')['default']
  loadUsage: typeof import('./actions/loadUsage')['default']
  refreshKb: typeof import('./actions/refreshKb')['default']
  refreshLoadedDocuments: typeof import('./actions/refreshLoadedDocuments')['default']
  reindexDocument: typeof import('./actions/reindexDocument')['default']
  removeDocument: typeof import('./actions/removeDocument')['default']
  reset: typeof import('./actions/reset')['default']
  retryAllFailed: typeof import('./actions/retryAllFailed')['default']
  searchKb: typeof import('./actions/searchKb')['default']
  toggleSelection: typeof import('./actions/toggleSelection')['default']
  uploadAndAttach: typeof import('./actions/uploadAndAttach')['default']
}
