// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  loadStatus: typeof import('./actions/loadStatus')['default']
  rotateMagicLink: typeof import('./actions/rotateMagicLink')['default']
  saveAuthToken: typeof import('./actions/saveAuthToken')['default']
  saveAutoStart: typeof import('./actions/saveAutoStart')['default']
  saveDomain: typeof import('./actions/saveDomain')['default']
  setAdminPassword: typeof import('./actions/setAdminPassword')['default']
  setPasswordAuthEnabled: typeof import('./actions/setPasswordAuthEnabled')['default']
  startMagicLinkRotation: typeof import('./actions/startMagicLinkRotation')['default']
  startTunnel: typeof import('./actions/startTunnel')['default']
  stopMagicLinkRotation: typeof import('./actions/stopMagicLinkRotation')['default']
  stopTunnel: typeof import('./actions/stopTunnel')['default']
}
