// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  closeAddRemoteLlmModelDrawer: typeof import('./actions/closeAddRemoteLlmModelDrawer')['default']
  openAddRemoteLlmModelDrawer: typeof import('./actions/openAddRemoteLlmModelDrawer')['default']
  setAddRemoteLlmModelDrawerLoading: typeof import('./actions/setAddRemoteLlmModelDrawerLoading')['default']
}
