// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  load: typeof import('./actions/load')['default']
  loadProviders: typeof import('./actions/loadProviders')['default']
  loadSettings: typeof import('./actions/loadSettings')['default']
  updateProvider: typeof import('./actions/updateProvider')['default']
  updateSettings: typeof import('./actions/updateSettings')['default']
}
