// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  closeViewDownloadDrawer: typeof import('./actions/closeViewDownloadDrawer')['default']
  openViewDownloadDrawer: typeof import('./actions/openViewDownloadDrawer')['default']
  setViewDownloadDrawerLoading: typeof import('./actions/setViewDownloadDrawerLoading')['default']
}
