// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  cancelUpload: typeof import('./actions/cancelUpload')['default']
  clearUploadError: typeof import('./actions/clearUploadError')['default']
  clearUploadState: typeof import('./actions/clearUploadState')['default']
  uploadLocalModel: typeof import('./actions/uploadLocalModel')['default']
}
