// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  closeCreateUserDrawer: typeof import('./actions/closeCreateUserDrawer')['default']
  openCreateUserDrawer: typeof import('./actions/openCreateUserDrawer')['default']
}
