// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  appendVersion: typeof import('./actions/appendVersion')['default']
  loadVersionText: typeof import('./actions/loadVersionText')['default']
  loadVersions: typeof import('./actions/loadVersions')['default']
  restoreVersion: typeof import('./actions/restoreVersion')['default']
}
