// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  create: typeof import('./actions/create')['default']
  load: typeof import('./actions/load')['default']
  remove: typeof import('./actions/remove')['default']
  update: typeof import('./actions/update')['default']
}
