// Routes for the project↔file relationship, mounted at
// `/api/projects/{id}/files*`.
//
// Returned from `FileProjectExtension::register_routes` so the project
// module merges them into its router via the PROJECT_EXTENSIONS slice
// without importing this file directly. URL stability: paths preserved
// exactly so `ApiClient.Project.{listFiles,attachFile,uploadAndAttachFile,detachFile}`
// in the autogenerated OpenAPI client keeps working unchanged.

use aide::axum::{
    ApiRouter,
    routing::{delete_with, get_with, post_with},
};
use axum::extract::DefaultBodyLimit;

use super::handlers::*;
use crate::core::app_state::file_upload_body_limit_bytes;

pub fn project_files_router() -> ApiRouter {
    ApiRouter::new()
        .api_route(
            "/projects/{id}/files",
            get_with(list_project_files, list_project_files_docs),
        )
        .api_route(
            "/projects/{id}/files",
            post_with(attach_file, attach_file_docs),
        )
        // Body limit derived from the same configurable per-file cap as
        // /files/upload (both share the `upload_file_inner` validator).
        .api_route(
            "/projects/{id}/files/upload",
            post_with(upload_and_attach_file, upload_and_attach_file_docs)
                .layer(DefaultBodyLimit::max(file_upload_body_limit_bytes())),
        )
        .api_route(
            "/projects/{id}/files/{file_id}",
            delete_with(detach_file, detach_file_docs),
        )
}

