// Routes for the project↔file relationship, mounted at
// `/api/projects/{id}/files*`.
//
// Returned from `FileProjectExtension::register_routes` so the project
// module merges them into its router via the PROJECT_EXTENSIONS slice
// without importing this file directly. URL stability: paths preserved
// exactly so `ApiClient.Project.{listFiles,attachFile,uploadAndAttachFile,detachFile}`
// in the autogenerated OpenAPI client keeps working unchanged.

use aide::axum::{
    ApiRouter,
    routing::{delete_with, get_with, post_with},
};
use axum::extract::DefaultBodyLimit;

use super::handlers::*;

/// Per-route body limit for project-file uploads. Matches the file
/// module's standalone /files/upload cap (200 MB) — both routes share
/// the same `upload_file_inner` validator chain (50 MB per individual file).
const PROJECT_FILE_UPLOAD_BODY_LIMIT: usize = 200 * 1024 * 1024;

pub fn project_files_router() -> ApiRouter {
    ApiRouter::new()
        .api_route(
            "/projects/{id}/files",
            get_with(list_project_files, list_project_files_docs),
        )
        .api_route(
            "/projects/{id}/files",
            post_with(attach_file, attach_file_docs),
        )
        .api_route(
            "/projects/{id}/files/upload",
            post_with(upload_and_attach_file, upload_and_attach_file_docs)
                .layer(DefaultBodyLimit::max(PROJECT_FILE_UPLOAD_BODY_LIMIT)),
        )
        .api_route(
            "/projects/{id}/files/{file_id}",
            delete_with(detach_file, detach_file_docs),
        )
}
