// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  clearHardwareError: typeof import('./actions/clearHardwareError')['default']
  disconnectHardwareUsage: typeof import('./actions/disconnectHardwareUsage')['default']
  loadHardwareInfo: typeof import('./actions/loadHardwareInfo')['default']
  subscribeToHardwareUsage: typeof import('./actions/subscribeToHardwareUsage')['default']
}
