// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  deleteSystemSkill: typeof import('./actions/deleteSystemSkill')['default']
  importSystemSkill: typeof import('./actions/importSystemSkill')['default']
  installSystemFromHub: typeof import('./actions/installSystemFromHub')['default']
  loadGroups: typeof import('./actions/loadGroups')['default']
  loadSystemSkills: typeof import('./actions/loadSystemSkills')['default']
  setGroups: typeof import('./actions/setGroups')['default']
  updateSystemSkill: typeof import('./actions/updateSystemSkill')['default']
}
