//! pgvector runtime install — writes the build-time-embedded
//! `vector.{so|dylib|dll}` + `vector.control` + `vector--*.sql` files
//! into the embedded Postgres installation directory before the server
//! brings the DB up. Idempotent: skips writes when the destination
//! files already exist and have the same length as the embedded blob.
//!
//! Pairs with `build_helper/pgvector.rs`. If the build failed to
//! produce real artifacts, `build_pgvector` wrote zero-byte stubs and
//! [`is_available`] returns `false` — callers should leave the embedded
//! PG without pgvector and the memory module will self-disable at boot.

use std::fs;
use std::io;
use std::path::Path;
use std::sync::atomic::{AtomicBool, Ordering};

// Generated by build.rs. Defines:
//   pub const VECTOR_LIB_FILENAME: &str = "vector.so";
//   pub const VECTOR_LIB: &[u8] = include_bytes!(...);
//   pub const VECTOR_CONTROL: &[u8] = include_bytes!(...);
//   pub const VECTOR_SQL_FILES: &[(&str, &[u8])] = &[...];
include!(concat!(env!("OUT_DIR"), "/pgvector_assets.rs"));

/// Result of the boot-time install + probe sequence.
static PGVECTOR_AVAILABLE: AtomicBool = AtomicBool::new(false);

/// True when [`install_into`] succeeded and a `CREATE EXTENSION vector`
/// smoke test passed. Callers (e.g. memory module init) consult this
/// before touching `vector(N)` tables.
#[allow(dead_code)]
pub fn is_available() -> bool {
    PGVECTOR_AVAILABLE.load(Ordering::Acquire)
}

/// Mark pgvector available — called from `core/database/mod.rs` after
/// `CREATE EXTENSION vector` succeeded against the running instance.
pub fn mark_available() {
    PGVECTOR_AVAILABLE.store(true, Ordering::Release);
}

/// True if the build-time embed contains real artifacts (not the
/// zero-byte stubs `build_helper/pgvector.rs::write_stubs` writes when
/// the make-driven build fails).
pub fn has_real_artifacts() -> bool {
    !VECTOR_LIB.is_empty() && !VECTOR_CONTROL.is_empty()
}

/// Copy the embedded artifacts into the embedded-PG install dir.
///
/// `install_dir` is the directory in which postgresql_embedded
/// extracted Postgres binaries (the path passed as
/// `Settings::installation_dir`). After this returns Ok, the next
/// `postgresql.start()` will load the extension at the configured
/// `dynamic_library_path` (the default `$libdir`).
///
/// Idempotent: returns Ok(()) immediately if the destination files
/// already match the embedded blob lengths. Returns
/// `Err(io::Error(NotFound, ...))` when the embed is stubbed out.
pub fn install_into(install_dir: &Path) -> io::Result<()> {
    if !has_real_artifacts() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            "pgvector artifacts are zero-byte stubs (build_helper/pgvector.rs::build_pgvector failed at compile time); memory features will be disabled",
        ));
    }

    let lib_dir = install_dir.join("lib");
    let ext_dir = install_dir.join("share").join("extension");
    fs::create_dir_all(&lib_dir)?;
    fs::create_dir_all(&ext_dir)?;

    let lib_dest = lib_dir.join(VECTOR_LIB_FILENAME);
    if !file_matches(&lib_dest, VECTOR_LIB)? {
        fs::write(&lib_dest, VECTOR_LIB)?;
    }

    let control_dest = ext_dir.join("vector.control");
    if !file_matches(&control_dest, VECTOR_CONTROL)? {
        fs::write(&control_dest, VECTOR_CONTROL)?;
    }

    for (name, bytes) in VECTOR_SQL_FILES.iter() {
        // Skip the stub sentinel — `build_helper::write_stubs` emits
        // `vector--stub.sql` when the build is stubbed out.
        if *name == "vector--stub.sql" {
            continue;
        }
        let dest = ext_dir.join(name);
        if !file_matches(&dest, bytes)? {
            fs::write(&dest, bytes)?;
        }
    }

    Ok(())
}

/// Cheap "same file?" check: matches if the file exists and its length
/// equals the embedded blob's length. Cheaper than hashing and good
/// enough — the embedded blobs are deterministic per server build, so
/// any size match is also a content match.
fn file_matches(path: &Path, embedded: &[u8]) -> io::Result<bool> {
    match fs::metadata(path) {
        Ok(m) => Ok(m.len() == embedded.len() as u64),
        Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(false),
        Err(e) => Err(e),
    }
}
