//! pgvector runtime install — writes the build-time-embedded
//! `vector.{so|dylib|dll}` + `vector.control` + `vector--*.sql` files
//! into the embedded Postgres installation directory before the server
//! brings the DB up. Idempotent: skips writes when the destination
//! files already exist and have the same length as the embedded blob.
//!
//! Pairs with `build_helper/pgvector.rs`. If the build failed to
//! produce real artifacts, `build_pgvector` wrote zero-byte stubs and
//! [`is_available`] returns `false` — callers should leave the embedded
//! PG without pgvector and the memory module will self-disable at boot.

use std::fs;
use std::io;
use std::path::Path;
use std::sync::atomic::{AtomicBool, Ordering};

// Generated by build.rs. Defines:
//   pub const VECTOR_LIB_FILENAME: &str = "vector.so";
//   pub const VECTOR_LIB: &[u8] = include_bytes!(...);
//   pub const VECTOR_CONTROL: &[u8] = include_bytes!(...);
//   pub const VECTOR_SQL_FILES: &[(&str, &[u8])] = &[...];
include!(concat!(env!("OUT_DIR"), "/pgvector_assets.rs"));

/// Result of the boot-time install + probe sequence.
static PGVECTOR_AVAILABLE: AtomicBool = AtomicBool::new(false);

/// True when [`install_into`] succeeded and a `CREATE EXTENSION vector`
/// smoke test passed. Callers (e.g. memory module init) consult this
/// before touching `vector(N)` tables.
#[allow(dead_code)]
pub fn is_available() -> bool {
    PGVECTOR_AVAILABLE.load(Ordering::Acquire)
}

/// Mark pgvector available — called from `core/database/mod.rs` after
/// `CREATE EXTENSION vector` succeeded against the running instance.
pub fn mark_available() {
    PGVECTOR_AVAILABLE.store(true, Ordering::Release);
}

/// True if the build-time embed contains real artifacts (not the
/// zero-byte stubs `build_helper/pgvector.rs::write_stubs` writes when
/// the make-driven build fails).
pub fn has_real_artifacts() -> bool {
    !VECTOR_LIB.is_empty() && !VECTOR_CONTROL.is_empty()
}

/// Copy the embedded artifacts into the embedded-PG install dir.
///
/// `install_dir` is the directory in which postgresql_embedded
/// extracted Postgres binaries (the path passed as
/// `Settings::installation_dir`). After this returns Ok, the next
/// `postgresql.start()` will load the extension at the configured
/// `dynamic_library_path` (the default `$libdir`).
///
/// Idempotent: returns Ok(()) immediately if the destination files
/// already match the embedded blob lengths. Returns
/// `Err(io::Error(NotFound, ...))` when the embed is stubbed out.
pub fn install_into(install_dir: &Path) -> io::Result<()> {
    if !has_real_artifacts() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            "pgvector artifacts are zero-byte stubs (build_helper/pgvector.rs::build_pgvector failed at compile time); memory features will be disabled",
        ));
    }

    let lib_dir = install_dir.join("lib");
    let ext_dir = install_dir.join("share").join("extension");
    fs::create_dir_all(&lib_dir)?;
    fs::create_dir_all(&ext_dir)?;

    let lib_dest = lib_dir.join(VECTOR_LIB_FILENAME);
    if !file_matches(&lib_dest, VECTOR_LIB)? {
        fs::write(&lib_dest, VECTOR_LIB)?;
    }

    let control_dest = ext_dir.join("vector.control");
    if !file_matches(&control_dest, VECTOR_CONTROL)? {
        fs::write(&control_dest, VECTOR_CONTROL)?;
    }

    for (name, bytes) in VECTOR_SQL_FILES.iter() {
        // Skip the stub sentinel — `build_helper::write_stubs` emits
        // `vector--stub.sql` when the build is stubbed out.
        if *name == "vector--stub.sql" {
            continue;
        }
        let dest = ext_dir.join(name);
        if !file_matches(&dest, bytes)? {
            fs::write(&dest, bytes)?;
        }
    }

    Ok(())
}

/// Cheap "same file?" check: matches if the file exists and its length
/// equals the embedded blob's length. Cheaper than hashing and good
/// enough — the embedded blobs are deterministic per server build, so
/// any size match is also a content match.
fn file_matches(path: &Path, embedded: &[u8]) -> io::Result<bool> {
    match fs::metadata(path) {
        Ok(m) => Ok(m.len() == embedded.len() as u64),
        Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(false),
        Err(e) => Err(e),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `file_matches` is the core of the idempotency guard: file absent →
    /// false; present + same length → true; present + different length →
    /// false (triggers a rewrite).
    #[test]
    fn file_matches_reflects_length_equality() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("blob.bin");

        // Absent → false (must be written).
        assert!(!file_matches(&path, b"hello").unwrap());

        // Present, same length → true (skip write).
        fs::write(&path, b"world").unwrap(); // 5 bytes, same len as "hello"
        assert!(file_matches(&path, b"hello").unwrap());

        // Present, different length → false (rewrite needed).
        assert!(!file_matches(&path, b"hi").unwrap());
    }

    /// `mark_available` flips the boot flag that `is_available` reads. The
    /// flag is monotonic within a process, so after marking it must read true.
    #[test]
    fn mark_available_is_observed_by_is_available() {
        mark_available();
        assert!(is_available());
    }

    /// A stubbed build (zero-byte embedded artifacts) must make `install_into`
    /// fail with NotFound and a message pointing at the disabled memory
    /// features — never silently "succeed" with empty files.
    #[test]
    fn install_into_rejects_stub_artifacts() {
        if has_real_artifacts() {
            // This build embedded real artifacts, so we can't exercise the
            // stub branch here; the idempotency test below covers the real path.
            return;
        }
        let dir = tempfile::tempdir().unwrap();
        let err = install_into(dir.path()).unwrap_err();
        assert_eq!(err.kind(), io::ErrorKind::NotFound);
        assert!(err.to_string().contains("stub"));
    }

    /// Full install → re-install is idempotent, and the skip-when-length-matches
    /// logic is real: a same-length tampered file is left alone (skipped) while
    /// a different-length file is overwritten back to the embedded blob.
    #[test]
    fn install_into_is_idempotent_and_length_gated() {
        if !has_real_artifacts() {
            // Stub build — nothing real to install; the stub-rejection test
            // covers this build shape.
            return;
        }
        let dir = tempfile::tempdir().unwrap();

        // First install writes the real artifacts.
        install_into(dir.path()).unwrap();
        let lib_dest = dir.path().join("lib").join(VECTOR_LIB_FILENAME);
        let control_dest = dir
            .path()
            .join("share")
            .join("extension")
            .join("vector.control");
        assert_eq!(fs::read(&lib_dest).unwrap(), VECTOR_LIB);
        assert_eq!(fs::read(&control_dest).unwrap(), VECTOR_CONTROL);

        // A second call is a no-op (all destinations already match) and must
        // still succeed.
        install_into(dir.path()).unwrap();
        assert_eq!(fs::read(&lib_dest).unwrap(), VECTOR_LIB);

        // Tamper with the SAME length → install must SKIP it (length matches),
        // leaving the tampered bytes in place.
        let same_len_garbage = vec![0xABu8; VECTOR_LIB.len()];
        fs::write(&lib_dest, &same_len_garbage).unwrap();
        install_into(dir.path()).unwrap();
        assert_eq!(
            fs::read(&lib_dest).unwrap(),
            same_len_garbage,
            "same-length file should be skipped, not rewritten"
        );

        // Tamper with a DIFFERENT length → install must REWRITE it back.
        fs::write(&lib_dest, b"short").unwrap();
        install_into(dir.path()).unwrap();
        assert_eq!(
            fs::read(&lib_dest).unwrap(),
            VECTOR_LIB,
            "different-length file should be overwritten with the embedded blob"
        );
    }
}
