// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  getThemePreference: typeof import('./actions/getThemePreference')['default']
  setAccentPreset: typeof import('./actions/setAccentPreset')['default']
  setThemePreference: typeof import('./actions/setThemePreference')['default']
}
