// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  clearAllGroupServers: typeof import('./actions/clearAllGroupServers')['default']
  clearGroupServers: typeof import('./actions/clearGroupServers')['default']
  getGroupServersData: typeof import('./actions/getGroupServersData')['default']
  loadAllServers: typeof import('./actions/loadAllServers')['default']
  loadServersForGroup: typeof import('./actions/loadServersForGroup')['default']
}
