// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  clearProjectDetailError: typeof import('./actions/clearProjectDetailError')['default']
  loadConversations: typeof import('./actions/loadConversations')['default']
  loadMoreConversations: typeof import('./actions/loadMoreConversations')['default']
  loadProject: typeof import('./actions/loadProject')['default']
}
