// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  loadMounts: typeof import('./actions/loadMounts')['default']
  saveMounts: typeof import('./actions/saveMounts')['default']
}
