// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  getForConversation: typeof import('./actions/getForConversation')['default']
  load: typeof import('./actions/load')['default']
  pin: typeof import('./actions/pin')['default']
  unpin: typeof import('./actions/unpin')['default']
}
