// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  completeGuide: typeof import('./actions/completeGuide')['default']
  completeStep: typeof import('./actions/completeStep')['default']
  loadProgress: typeof import('./actions/loadProgress')['default']
  reset: typeof import('./actions/reset')['default']
  setNextError: typeof import('./actions/setNextError')['default']
  setNextLoading: typeof import('./actions/setNextLoading')['default']
  setReady: typeof import('./actions/setReady')['default']
}
