// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  clearError: typeof import('./actions/clearError')['default']
  loadInstance: typeof import('./actions/loadInstance')['default']
  loadUsage: typeof import('./actions/loadUsage')['default']
  restartModel: typeof import('./actions/restartModel')['default']
  startModel: typeof import('./actions/startModel')['default']
  stopModel: typeof import('./actions/stopModel')['default']
  swapVersion: typeof import('./actions/swapVersion')['default']
}
