use crate::core::app_builder;
use crate::core::config::Config;
use crate::module_api::ModuleContext;
use sqlx::PgPool;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Arc;

/// Generate OpenAPI specification and TypeScript types in the output directory
pub async fn generate_openapi_spec(output_dir: &str, config_file: Option<String>) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    println!("Generating OpenAPI specification...");

    // Load configuration
    let config = Config::load_from(config_file)?;

    // Initialize database properly (this starts embedded PostgreSQL if use_embedded: true)
    let pool = crate::core::database::initialize_database(&config).await?;

    // Initialize modules using shared builder functions
    let module_context = ModuleContext::new(pool.clone());
    let mut modules = app_builder::create_modules();

    // Initialize all modules
    app_builder::initialize_modules(&mut modules, &module_context)?;

    // Build API router using shared builder function
    // build_api_router expects PgPool, so we need to extract it from Arc
    let (api_router, mut api_doc) = app_builder::build_api_router(
        &modules,
        &config.server.api_prefix,
        (*pool).clone(),
    );

    // Finish the API and extract the OpenAPI spec
    let _router = api_router.finish_api(&mut api_doc);

    // Serialize to JSON
    let json = serde_json::to_string_pretty(&api_doc)?;

    // Ensure output directory exists
    let output_path = Path::new(output_dir);
    if !output_path.exists() {
        fs::create_dir_all(output_path)?;
    }

    // Write openapi.json
    let openapi_json_path = output_path.join("openapi.json");
    fs::write(&openapi_json_path, &json)?;
    println!("✓ OpenAPI specification written to: {}", openapi_json_path.display());

    // Generate TypeScript types
    generate_typescript_types(output_path, &json)?;

    println!("\n✓ OpenAPI generation complete!");
    println!("  - OpenAPI spec: {}", openapi_json_path.display());
    println!("  - TypeScript types: {}", output_path.join("types.ts").display());

    Ok(())
}

/// Generate TypeScript types from OpenAPI specification
fn generate_typescript_types(output_dir: &Path, openapi_json: &str) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    println!("Generating TypeScript types...");

    // Check if the TypeScript generator script exists
    let project_root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).parent().unwrap().to_path_buf();
    let ts_generator = project_root.join("openapi").join("generate-endpoints.ts");

    if ts_generator.exists() {
        // Run the TypeScript generator using Node.js
        println!("Running TypeScript generator: {}", ts_generator.display());

        let status = Command::new("node")
            .arg("--loader")
            .arg("tsx")
            .arg(&ts_generator)
            .current_dir(output_dir)
            .status();

        match status {
            Ok(exit_status) if exit_status.success() => {
                println!("✓ TypeScript types generated successfully");
            }
            Ok(exit_status) => {
                eprintln!("Warning: TypeScript generator exited with status: {}", exit_status);
                eprintln!("Falling back to basic type generation...");
                generate_basic_typescript_types(output_dir, openapi_json)?;
            }
            Err(e) => {
                eprintln!("Warning: Failed to run TypeScript generator: {}", e);
                eprintln!("Falling back to basic type generation...");
                generate_basic_typescript_types(output_dir, openapi_json)?;
            }
        }
    } else {
        println!("TypeScript generator not found, using basic type generation...");
        generate_basic_typescript_types(output_dir, openapi_json)?;
    }

    Ok(())
}

/// Generate basic TypeScript types as a fallback
fn generate_basic_typescript_types(output_dir: &Path, openapi_json: &str) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    // Parse the OpenAPI spec
    let spec: serde_json::Value = serde_json::from_str(openapi_json)?;

    let mut types_content = String::from(
        r#"/**
 * Generated API type definitions
 * Auto-generated from OpenAPI specification
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * This file is automatically generated from the OpenAPI specification generated from the server code.
 */

"#,
    );

    // Extract schemas and generate TypeScript interfaces
    types_content.push_str("// =============================================================================\n");
    types_content.push_str("// TYPE DEFINITIONS\n");
    types_content.push_str("// =============================================================================\n\n");

    if let Some(components) = spec.get("components") {
        if let Some(schemas) = components.get("schemas").and_then(|s| s.as_object()) {
            for (name, schema) in schemas {
                types_content.push_str(&generate_schema_interface(name, schema));
                types_content.push_str("\n");
            }
        }
    }

    // Extract and generate Permission enum
    let permissions = extract_permissions(&spec);
    if !permissions.is_empty() {
        types_content.push_str(&generate_permission_enum(&permissions));
        types_content.push_str("\n");
    }

    // Extract endpoints and generate parameter/response types
    let mut endpoints_map = std::collections::BTreeMap::new();
    let mut parameters_map = std::collections::BTreeMap::new();
    let mut responses_map = std::collections::BTreeMap::new();

    if let Some(paths) = spec.get("paths").and_then(|p| p.as_object()) {
        for (path, methods) in paths {
            if let Some(methods_obj) = methods.as_object() {
                for (method, operation) in methods_obj {
                    if let Some(operation_id) = operation.get("operationId").and_then(|id| id.as_str()) {
                        // Add to endpoints map
                        endpoints_map.insert(
                            operation_id.to_string(),
                            format!("{} {}", method.to_uppercase(), path)
                        );

                        // Generate parameter type
                        let param_type = generate_parameter_type(operation, path);
                        parameters_map.insert(operation_id.to_string(), param_type);

                        // Generate response type
                        let response_type = generate_response_type(operation);
                        responses_map.insert(operation_id.to_string(), response_type);
                    }
                }
            }
        }
    }

    // Generate endpoints section
    types_content.push_str("\n// =============================================================================\n");
    types_content.push_str("// API ENDPOINTS\n");
    types_content.push_str("// =============================================================================\n\n");
    types_content.push_str("// API endpoint definitions\n");
    types_content.push_str("export const ApiEndpoints = {\n");
    for (key, value) in &endpoints_map {
        types_content.push_str(&format!("  '{}': '{}',\n", key, value));
    }
    types_content.push_str("} as const\n\n");

    // Generate parameters section
    types_content.push_str("// API endpoint parameters\n");
    types_content.push_str("export type ApiEndpointParameters = {\n");
    for (key, value) in &parameters_map {
        types_content.push_str(&format!("  '{}': {}\n", key, value));
    }
    types_content.push_str("}\n\n");

    // Generate responses section
    types_content.push_str("// API endpoint responses\n");
    types_content.push_str("export type ApiEndpointResponses = {\n");
    for (key, value) in &responses_map {
        types_content.push_str(&format!("  '{}': {}\n", key, value));
    }
    types_content.push_str("}\n\n");

    // Generate helper types
    types_content.push_str(&generate_helper_types());

    // Write types.ts
    let types_path = output_dir.join("types.ts");
    fs::write(&types_path, types_content)?;

    Ok(())
}

/// Generate TypeScript interface from schema
fn generate_schema_interface(name: &str, schema: &serde_json::Value) -> String {
    // Special handling for SSE event types with oneOf pattern
    if name.starts_with("SSE") {
        if let Some(one_of) = schema.get("oneOf").and_then(|o| o.as_array()) {
            return generate_sse_event_type(name, one_of);
        }
    }

    if let Some(properties) = schema.get("properties").and_then(|p| p.as_object()) {
        let mut interface = format!("export interface {} {{\n", name);

        for (prop_name, prop_schema) in properties {
            let prop_type = infer_typescript_type(prop_schema);
            let required = schema
                .get("required")
                .and_then(|r| r.as_array())
                .map(|arr| arr.iter().any(|v| v.as_str() == Some(prop_name)))
                .unwrap_or(false);

            let optional = if required { "" } else { "?" };
            interface.push_str(&format!("  {}{}: {}\n", prop_name, optional, prop_type));
        }

        interface.push_str("}");
        interface
    } else if let Some(type_str) = schema.get("type").and_then(|t| t.as_str()) {
        // Handle non-object types
        if type_str == "array" {
            if let Some(items) = schema.get("items") {
                let item_type = infer_typescript_type(items);
                return format!("export type {} = {}[]", name, item_type);
            }
        }
        let base_type = infer_typescript_type(schema);
        format!("export type {} = {}", name, base_type)
    } else {
        format!("export type {} = any", name)
    }
}

/// Generate SSE event type with discriminated union pattern
fn generate_sse_event_type(name: &str, one_of_variants: &[serde_json::Value]) -> String {
    let mut event_types = Vec::new();

    for variant in one_of_variants {
        if let Some(properties) = variant.get("properties").and_then(|p| p.as_object()) {
            // Each variant should have a single property representing the event name
            if properties.len() == 1 {
                let (event_name, event_data_schema) = properties.iter().next().unwrap();
                let data_type = infer_typescript_type(event_data_schema);
                event_types.push(format!("  {}: {}", event_name, data_type));
            }
        }
    }

    if event_types.is_empty() {
        return format!("export type {} = any", name);
    }

    format!(
        "export type {} = {{\n{}\n}}",
        name,
        event_types.join("\n")
    )
}

/// Generate parameter type for an endpoint
fn generate_parameter_type(operation: &serde_json::Value, path: &str) -> String {
    let mut param_types = Vec::new();

    // Add path parameters
    let path_params: Vec<&str> = path
        .split('/')
        .filter(|s| s.starts_with('{') && s.ends_with('}'))
        .map(|s| &s[1..s.len()-1])
        .collect();

    let has_path_params = !path_params.is_empty();

    for param in &path_params {
        param_types.push(format!("{}: string", param));
    }

    // Add query parameters
    if let Some(parameters) = operation.get("parameters").and_then(|p| p.as_array()) {
        for param in parameters {
            if let Some(param_in) = param.get("in").and_then(|i| i.as_str()) {
                if param_in == "query" {
                    if let Some(param_name) = param.get("name").and_then(|n| n.as_str()) {
                        let required = param.get("required").and_then(|r| r.as_bool()).unwrap_or(false);
                        let optional = if required { "" } else { "?" };

                        let param_type = if let Some(schema) = param.get("schema") {
                            infer_typescript_type(schema)
                        } else {
                            "any".to_string()
                        };

                        param_types.push(format!("{}{}: {}", param_name, optional, param_type));
                    }
                }
            }
        }
    }

    // Add request body type
    if let Some(request_body) = operation.get("requestBody") {
        if let Some(content) = request_body.get("content") {
            if let Some(json_content) = content.get("application/json") {
                if let Some(schema) = json_content.get("schema") {
                    let body_type = infer_typescript_type(schema);
                    if param_types.is_empty() {
                        return body_type;
                    } else {
                        return format!("{{ {} }} & {}", param_types.join("; "), body_type);
                    }
                }
            }
        }
    }

    // Return parameter object type or void
    if param_types.is_empty() {
        "void".to_string()
    } else if param_types.len() == 1 && !has_path_params {
        // Single query parameter
        format!("{{ {} }}", param_types[0])
    } else {
        format!("{{ {} }}", param_types.join("; "))
    }
}

/// Generate response type for an endpoint
fn generate_response_type(operation: &serde_json::Value) -> String {
    if let Some(responses) = operation.get("responses") {
        // Check for 204 No Content
        if responses.get("204").is_some() {
            return "void".to_string();
        }

        // Look for successful responses (200, 201, 202)
        for status in &["200", "201", "202"] {
            if let Some(response) = responses.get(*status) {
                if let Some(content) = response.get("content") {
                    if let Some(json_content) = content.get("application/json") {
                        if let Some(schema) = json_content.get("schema") {
                            return infer_typescript_type(schema);
                        }
                    }
                }
                // Response exists but no content
                return "void".to_string();
            }
        }
    }

    "any".to_string()
}

/// Generate helper types section
fn generate_helper_types() -> String {
    r#"// Type helpers
export type ApiEndpoint = keyof typeof ApiEndpoints
export type ApiEndpointUrl = (typeof ApiEndpoints)[ApiEndpoint]

// Extract endpoint key from URL pattern
export function getEndpointKey(url: string): ApiEndpoint | undefined {
  const entries = Object.entries(ApiEndpoints) as [ApiEndpoint, string][]
  const found = entries.find(([_key, value]) => value === url)
  return found ? found[0] : undefined
}

// Get parameter type for endpoint
export type GetParameterType<K extends ApiEndpoint> = ApiEndpointParameters[K]

// Get response type for endpoint
export type GetResponseType<K extends ApiEndpoint> = ApiEndpointResponses[K]

// Create reverse mapping from URL to endpoint key
export type UrlToEndpoint<U extends ApiEndpointUrl> = {
  [K in keyof typeof ApiEndpoints]: (typeof ApiEndpoints)[K] extends U
    ? K
    : never
}[keyof typeof ApiEndpoints]

// Helper types to get parameter and response types by URL
export type ParameterByUrl<U extends ApiEndpointUrl> =
  ApiEndpointParameters[UrlToEndpoint<U>]
export type ResponseByUrl<U extends ApiEndpointUrl> =
  ApiEndpointResponses[UrlToEndpoint<U>]

// Type-safe validation - this will cause a TypeScript error if any endpoint is missing
type ValidateParametersComplete = {
  [K in keyof typeof ApiEndpoints]: K extends keyof ApiEndpointParameters
    ? true
    : false
}

type ValidateResponsesComplete = {
  [K in keyof typeof ApiEndpoints]: K extends keyof ApiEndpointResponses
    ? true
    : false
}

// Type-safe validation - these will cause a TypeScript error if any endpoint is missing
// from Parameters or Responses. They are used for compile-time validation only.
export type { ValidateParametersComplete, ValidateResponsesComplete }
"#.to_string()
}

/// Infer TypeScript type from JSON schema
fn infer_typescript_type(schema: &serde_json::Value) -> String {
    // Handle $ref
    if let Some(ref_str) = schema.get("$ref").and_then(|r| r.as_str()) {
        return ref_str
            .replace("#/components/schemas/", "")
            .to_string();
    }

    // Handle type
    if let Some(type_str) = schema.get("type").and_then(|t| t.as_str()) {
        return match type_str {
            "string" => "string".to_string(),
            "number" | "integer" => "number".to_string(),
            "boolean" => "boolean".to_string(),
            "array" => {
                if let Some(items) = schema.get("items") {
                    format!("{}[]", infer_typescript_type(items))
                } else {
                    "any[]".to_string()
                }
            }
            "object" => "any".to_string(),
            _ => "any".to_string(),
        };
    }

    "any".to_string()
}

#[derive(Debug, Clone)]
struct PermissionInfo {
    name: String,
    value: String,
    description: String,
}

/// Extract all unique permissions from OpenAPI spec
fn extract_permissions(spec: &serde_json::Value) -> Vec<PermissionInfo> {
    let mut permissions = std::collections::BTreeMap::new();

    // Look through all paths and operations for 403 responses with permission details
    if let Some(paths) = spec.get("paths").and_then(|p| p.as_object()) {
        for (_path, methods) in paths {
            if let Some(methods_obj) = methods.as_object() {
                for (_method, operation) in methods_obj {
                    if let Some(responses) = operation.get("responses") {
                        if let Some(forbidden_response) = responses.get("403") {
                            // Check if there's a PermissionError example
                            if let Some(content) = forbidden_response.get("content") {
                                if let Some(json_content) = content.get("application/json") {
                                    if let Some(example) = json_content.get("example") {
                                        if let Some(details) = example.get("details") {
                                            if let Some(required_perms) = details.get("required_permissions").and_then(|p| p.as_array()) {
                                                for perm in required_perms {
                                                    if let (Some(name), Some(value), Some(desc)) = (
                                                        perm.get("name").and_then(|n| n.as_str()),
                                                        perm.get("value").and_then(|v| v.as_str()),
                                                        perm.get("description").and_then(|d| d.as_str()),
                                                    ) {
                                                        permissions.insert(
                                                            value.to_string(),
                                                            PermissionInfo {
                                                                name: name.to_string(),
                                                                value: value.to_string(),
                                                                description: desc.to_string(),
                                                            },
                                                        );
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    // Sort by value and return
    let mut result: Vec<PermissionInfo> = permissions.into_values().collect();
    result.sort_by(|a, b| a.value.cmp(&b.value));
    result
}

/// Generate TypeScript Permission enum
fn generate_permission_enum(permissions: &[PermissionInfo]) -> String {
    let mut enum_str = String::from("export enum Permission {\n");

    for perm in permissions {
        enum_str.push_str(&format!("  {} = '{}',\n", perm.name, perm.value));
    }

    enum_str.push_str("}\n");
    enum_str
}
