// AUTO-GENERATED by scripts/gen-crawl-cassette.mjs — DO NOT EDIT.
// Run `npm run gen:gallery-crawl` after re-recording. 60 recorded
// paramless GET endpoints (54 typed, 6 loose).
// The typed block is `satisfies Cassette` so each recorded response is checked
// against its api-client response type (drift fails tsc). The loose block is
// openapi-valid (ajv contract test) but types.ts-strict-mismatched, so it's cast.
import type { Cassette } from '../mockApi'
import raw from './recorded/crawl.json'

const typed = {
  "Assistant.getDefault": raw["Assistant.getDefault"],
  "Assistant.list": raw["Assistant.list"],
  "AssistantTemplate.getDefault": raw["AssistantTemplate.getDefault"],
  "AssistantTemplate.list": raw["AssistantTemplate.list"],
  "Auth.listProviders": raw["Auth.listProviders"],
  "AuthProviders.list": raw["AuthProviders.list"],
  "Chat.getUserLlmProviders": raw["Chat.getUserLlmProviders"],
  "Citations.list": raw["Citations.list"],
  "Citations.listStyles": raw["Citations.listStyles"],
  "CodeSandbox.getResourceLimits": raw["CodeSandbox.getResourceLimits"],
  "CodeSandbox.listFlavors": raw["CodeSandbox.listFlavors"],
  "Conversation.list": raw["Conversation.list"],
  "File.list": raw["File.list"],
  "FileRagAdmin.get": raw["FileRagAdmin.get"],
  "Hardware.info": raw["Hardware.info"],
  "Hub.getAssistantsVersion": raw["Hub.getAssistantsVersion"],
  "Hub.getInstalled": raw["Hub.getInstalled"],
  "Hub.getLocalProviders": raw["Hub.getLocalProviders"],
  "Hub.getMCPServers": raw["Hub.getMCPServers"],
  "Hub.getMCPServersVersion": raw["Hub.getMCPServersVersion"],
  "Hub.getModelsVersion": raw["Hub.getModelsVersion"],
  "LitSearch.getConnectors": raw["LitSearch.getConnectors"],
  "LitSearch.getSettings": raw["LitSearch.getSettings"],
  "LitSearch.listUserKeys": raw["LitSearch.listUserKeys"],
  "LlmProvider.getUserLlmProviders": raw["LlmProvider.getUserLlmProviders"],
  "LlmProvider.list": raw["LlmProvider.list"],
  "LlmProvider.listUserApiKeys": raw["LlmProvider.listUserApiKeys"],
  "LlmRepository.list": raw["LlmRepository.list"],
  "LocalRuntime.detectGpu": raw["LocalRuntime.detectGpu"],
  "LocalRuntime.getRuntimeSettings": raw["LocalRuntime.getRuntimeSettings"],
  "Mcp.getDefaults": raw["Mcp.getDefaults"],
  "McpToolCall.list": raw["McpToolCall.list"],
  "McpUserPolicy.get": raw["McpUserPolicy.get"],
  "Memory.list": raw["Memory.list"],
  "MemoryAdmin.ftsRebuildStatus": raw["MemoryAdmin.ftsRebuildStatus"],
  "MemoryAdmin.get": raw["MemoryAdmin.get"],
  "MemoryAdmin.rebuildStatus": raw["MemoryAdmin.rebuildStatus"],
  "MemoryAudit.list": raw["MemoryAudit.list"],
  "MemorySettings.get": raw["MemorySettings.get"],
  "Onboarding.getProgress": raw["Onboarding.getProgress"],
  "Project.list": raw["Project.list"],
  "RuntimeVersion.list": raw["RuntimeVersion.list"],
  "RuntimeVersion.usage": raw["RuntimeVersion.usage"],
  "ServerUpdate.getStatus": raw["ServerUpdate.getStatus"],
  "Skill.list": raw["Skill.list"],
  "SkillSystem.list": raw["SkillSystem.list"],
  "SummarizationAdmin.get": raw["SummarizationAdmin.get"],
  "User.list": raw["User.list"],
  "UserGroup.list": raw["UserGroup.list"],
  "WebSearch.getProviders": raw["WebSearch.getProviders"],
  "WebSearch.getSettings": raw["WebSearch.getSettings"],
  "WebSearch.listUserKeys": raw["WebSearch.listUserKeys"],
  "Workflow.list": raw["Workflow.list"],
  "Workflow.listSystem": raw["Workflow.listSystem"],
} satisfies Cassette

// openapi-valid, types.ts-strict — gated by the ajv contract test, not tsc.
const loose = {
  "Hub.getAssistants": raw["Hub.getAssistants"],
  "Hub.getCatalog": raw["Hub.getCatalog"],
  "Hub.getCatalogVersion": raw["Hub.getCatalogVersion"],
  "Hub.getModels": raw["Hub.getModels"],
  "McpServer.listAccessible": raw["McpServer.listAccessible"],
  "McpServerSystem.list": raw["McpServerSystem.list"],
} as unknown as Cassette

export const crawlCassette: Cassette = { ...typed, ...loose }
