// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  clearAssistant: typeof import('./actions/clearAssistant')['default']
  getAssistantId: typeof import('./actions/getAssistantId')['default']
  loadAssistants: typeof import('./actions/loadAssistants')['default']
  selectAssistant: typeof import('./actions/selectAssistant')['default']
}
