// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  assignServerToGroups: typeof import('./actions/assignServerToGroups')['default']
  clearSystemMcpErrors: typeof import('./actions/clearSystemMcpErrors')['default']
  createSystemServer: typeof import('./actions/createSystemServer')['default']
  deleteSystemServer: typeof import('./actions/deleteSystemServer')['default']
  getEnabledSystemServers: typeof import('./actions/getEnabledSystemServers')['default']
  getServerGroups: typeof import('./actions/getServerGroups')['default']
  getServersForGroup: typeof import('./actions/getServersForGroup')['default']
  getSystemServerById: typeof import('./actions/getSystemServerById')['default']
  isServerOperationLoading: typeof import('./actions/isServerOperationLoading')['default']
  loadSystemServers: typeof import('./actions/loadSystemServers')['default']
  refreshSystemServers: typeof import('./actions/refreshSystemServers')['default']
  removeServerFromGroup: typeof import('./actions/removeServerFromGroup')['default']
  searchSystemServers: typeof import('./actions/searchSystemServers')['default']
  setSearchTerm: typeof import('./actions/setSearchTerm')['default']
  setStatusFilter: typeof import('./actions/setStatusFilter')['default']
  testSystemServerConnection: typeof import('./actions/testSystemServerConnection')['default']
  updateGroupServers: typeof import('./actions/updateGroupServers')['default']
  updateSystemServer: typeof import('./actions/updateSystemServer')['default']
}
