// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  clearError: typeof import('./actions/clearError')['default']
  loadGpu: typeof import('./actions/loadGpu')['default']
  loadSettings: typeof import('./actions/loadSettings')['default']
  saveSettings: typeof import('./actions/saveSettings')['default']
}
