// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  assignGroupToProvider: typeof import('./actions/assignGroupToProvider')['default']
  clearLlmProviderStoreError: typeof import('./actions/clearLlmProviderStoreError')['default']
  createLlmModel: typeof import('./actions/createLlmModel')['default']
  createLlmProvider: typeof import('./actions/createLlmProvider')['default']
  deleteLlmModel: typeof import('./actions/deleteLlmModel')['default']
  deleteLlmProvider: typeof import('./actions/deleteLlmProvider')['default']
  disableLlmModel: typeof import('./actions/disableLlmModel')['default']
  discoverModels: typeof import('./actions/discoverModels')['default']
  enableLlmModel: typeof import('./actions/enableLlmModel')['default']
  findLlmModelById: typeof import('./actions/findLlmModelById')['default']
  findLlmProviderById: typeof import('./actions/findLlmProviderById')['default']
  getGroupsForProvider: typeof import('./actions/getGroupsForProvider')['default']
  getProvidersForGroup: typeof import('./actions/getProvidersForGroup')['default']
  llmProviderHasCredentials: typeof import('./actions/llmProviderHasCredentials')['default']
  loadLlmProviders: typeof import('./actions/loadLlmProviders')['default']
  loadModelsForProvider: typeof import('./actions/loadModelsForProvider')['default']
  refreshProviderModels: typeof import('./actions/refreshProviderModels')['default']
  removeGroupFromProvider: typeof import('./actions/removeGroupFromProvider')['default']
  updateGroupProviders: typeof import('./actions/updateGroupProviders')['default']
  updateLlmModel: typeof import('./actions/updateLlmModel')['default']
  updateLlmProvider: typeof import('./actions/updateLlmProvider')['default']
}
