// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  addExternalDownload: typeof import('./actions/addExternalDownload')['default']
  cancelLlmModelDownload: typeof import('./actions/cancelLlmModelDownload')['default']
  clearAllLlmModelDownloads: typeof import('./actions/clearAllLlmModelDownloads')['default']
  clearLlmModelDownload: typeof import('./actions/clearLlmModelDownload')['default']
  deleteLlmModelDownload: typeof import('./actions/deleteLlmModelDownload')['default']
  disconnectSSE: typeof import('./actions/disconnectSSE')['default']
  downloadLlmModelFromRepository: typeof import('./actions/downloadLlmModelFromRepository')['default']
  findDownloadById: typeof import('./actions/findDownloadById')['default']
  getAllActiveDownloads: typeof import('./actions/getAllActiveDownloads')['default']
  initializeDownloadTracking: typeof import('./actions/initializeDownloadTracking')['default']
  listRepositoryFiles: typeof import('./actions/listRepositoryFiles')['default']
  setupDownloadTracking: typeof import('./actions/setupDownloadTracking')['default']
  subscribeToDownloadProgress: typeof import('./actions/subscribeToDownloadProgress')['default']
}
