// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  defaultModelId: typeof import('./actions/defaultModelId')['default']
  getModelId: typeof import('./actions/getModelId')['default']
  initializeFromConversation: typeof import('./actions/initializeFromConversation')['default']
  loadProviders: typeof import('./actions/loadProviders')['default']
  setModelId: typeof import('./actions/setModelId')['default']
}
