// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  clearError: typeof import('./actions/clearError')['default']
  createUser: typeof import('./actions/createUser')['default']
  deleteUser: typeof import('./actions/deleteUser')['default']
  loadUserRegistrationSettings: typeof import('./actions/loadUserRegistrationSettings')['default']
  loadUsers: typeof import('./actions/loadUsers')['default']
  resetUserPassword: typeof import('./actions/resetUserPassword')['default']
  toggleUserActiveStatus: typeof import('./actions/toggleUserActiveStatus')['default']
  updateUser: typeof import('./actions/updateUser')['default']
  updateUserRegistrationSettings: typeof import('./actions/updateUserRegistrationSettings')['default']
}
