// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  check: typeof import('./actions/check')['default']
  download: typeof import('./actions/download')['default']
  install: typeof import('./actions/install')['default']
  installAndRestart: typeof import('./actions/installAndRestart')['default']
  loadStatus: typeof import('./actions/loadStatus')['default']
  remindLater: typeof import('./actions/remindLater')['default']
  startDailyChecks: typeof import('./actions/startDailyChecks')['default']
  startPolling: typeof import('./actions/startPolling')['default']
  stopDailyChecks: typeof import('./actions/stopDailyChecks')['default']
  stopPolling: typeof import('./actions/stopPolling')['default']
}
