import { useState } from 'react'
import { Card, Divider, Flex, Typography } from 'antd'
import { CompressOutlined, RightOutlined, DownOutlined } from '@ant-design/icons'
import { Stores } from '@/core/stores'
import { useMessageContext } from '@/modules/chat/core/MessageContext'

const { Text, Paragraph } = Typography

/**
 * In-thread persistent marker shown on the boundary message — i.e. the
 * message whose `id` equals the summary's `summarized_up_to_id`.
 *
 * Registered in the `message_footer` slot (rendered inside
 * `MessageContext.Provider` per `ChatMessage.tsx`). Each
 * `ChatMessage` mounts one instance; the instance whose message id
 * matches the summary anchor renders the divider, the others return
 * null. Cheap — every other instance bails out in the first useState
 * call.
 *
 * `message_footer` was chosen over `message_item_prefix` /
 * `message_item_suffix` (the prior session's audit confirmed the
 * suffix slot isn't actually rendered, and prefix sits before the
 * message bubble — visually misleading for a "earlier turns
 * condensed" marker). The footer sits directly below the last
 * condensed turn, which reads naturally.
 *
 * The summary itself lives in `Stores.ConversationSummarization.current`
 * — loaded by `SummarizationStatusPill` on every conversation switch
 * and on every `messages.size` change.
 */
export function SummaryBoundaryMarker() {
  const message = useMessageContext()
  const current = Stores.ConversationSummarization.current
  const [expanded, setExpanded] = useState(false)

  if (!message) return null
  if (!current?.summary) return null
  if (current.summary.summarized_up_to_id !== message.id) return null

  const summary = current.summary
  const updatedAt = new Date(summary.updated_at).toLocaleString()

  return (
    <div className="mt-3 mb-1">
      <Divider style={{ margin: '12px 0' }}>
        <Flex
          align="center"
          gap={6}
          style={{ cursor: 'pointer', userSelect: 'none' }}
          role="button"
          tabIndex={0}
          aria-expanded={expanded}
          aria-label={
            expanded
              ? 'Collapse condensed-conversation summary'
              : 'Expand condensed-conversation summary'
          }
          onClick={() => setExpanded(!expanded)}
          onKeyDown={e => {
            if (e.key === 'Enter' || e.key === ' ') {
              e.preventDefault()
              setExpanded(!expanded)
            }
          }}
        >
          <CompressOutlined style={{ opacity: 0.7 }} />
          <Text type="secondary" style={{ fontSize: 12 }}>
            Earlier {summary.message_count} messages condensed into a summary
          </Text>
          {expanded ? (
            <DownOutlined style={{ fontSize: 10, opacity: 0.5 }} />
          ) : (
            <RightOutlined style={{ fontSize: 10, opacity: 0.5 }} />
          )}
        </Flex>
      </Divider>
      {expanded && (
        <Card size="small" style={{ marginBottom: 12 }}>
          <Paragraph
            type="secondary"
            style={{
              whiteSpace: 'pre-wrap',
              fontSize: 13,
              marginBottom: 8,
            }}
          >
            {summary.summary_text}
          </Paragraph>
          <Text type="secondary" style={{ fontSize: 11 }}>
            {summary.model_used
              ? `Generated by ${summary.model_used} at ${updatedAt}`
              : `Generated at ${updatedAt}`}
          </Text>
        </Card>
      )}
    </div>
  )
}
