import { useState } from 'react'
import { Card, Separator, Flex, Text } from '@/components/ui'
import { CompressOutlined, RightOutlined, DownOutlined } from '@ant-design/icons'
import { Stores } from '@/core/stores'
import { useMessageContext } from '@/modules/chat/core/MessageContext'

/**
 * In-thread persistent marker shown on the boundary message — i.e. the
 * message whose `id` equals the summary's `summarized_up_to_id`.
 *
 * Registered in the `message_footer` slot (rendered inside
 * `MessageContext.Provider` per `ChatMessage.tsx`). Each
 * `ChatMessage` mounts one instance; the instance whose message id
 * matches the summary anchor renders the divider, the others return
 * null. Cheap — every other instance bails out in the first useState
 * call.
 *
 * `message_footer` was chosen over `message_item_prefix` /
 * `message_item_suffix` (the prior session's audit confirmed the
 * suffix slot isn't actually rendered, and prefix sits before the
 * message bubble — visually misleading for a "earlier turns
 * condensed" marker). The footer sits directly below the last
 * condensed turn, which reads naturally.
 *
 * The summary itself lives in `Stores.ConversationSummarization.current`
 * — loaded by `SummarizationStatusPill` on every conversation switch
 * and on every `messages.size` change.
 */
export function SummaryBoundaryMarker() {
  const message = useMessageContext()
  const current = Stores.ConversationSummarization.current
  const [expanded, setExpanded] = useState(false)

  if (!message) return null
  if (!current?.summary) return null
  if (current.summary.summarized_up_to_id !== message.id) return null

  const summary = current.summary
  const updatedAt = new Date(summary.updated_at).toLocaleString()

  return (
    <div className="mt-3 mb-1">
      <Separator>
        <Flex
          align="center"
          gap="middle"
          className="cursor-pointer select-none"
          role="button"
          tabIndex={0}
          aria-expanded={expanded}
          aria-label={
            expanded
              ? 'Collapse condensed-conversation summary'
              : 'Expand condensed-conversation summary'
          }
          onClick={() => setExpanded(!expanded)}
          onKeyDown={e => {
            if (e.key === 'Enter' || e.key === ' ') {
              e.preventDefault()
              setExpanded(!expanded)
            }
          }}
        >
          <CompressOutlined className="opacity-70" />
          <Text type="secondary" className="text-xs">
            Earlier {summary.message_count} messages condensed into a summary
          </Text>
          {expanded ? (
            <DownOutlined className="text-[10px] opacity-50" />
          ) : (
            <RightOutlined className="text-[10px] opacity-50" />
          )}
        </Flex>
      </Separator>
      {expanded && (
        <Card size="sm" className="mb-3">
          <Text
            type="secondary"
            className="whitespace-pre-wrap text-xs mb-2"
          >
            {summary.summary_text}
          </Text>
          <Text type="secondary" className="text-[11px]">
            {summary.model_used
              ? `Generated by ${summary.model_used} at ${updatedAt}`
              : `Generated at ${updatedAt}`}
          </Text>
        </Card>
      )}
    </div>
  )
}
