#!/usr/bin/env bash
# Stand up a local "GitHub Releases" mirror on loopback so the
# server's auto-fetch path can validate against it WITHOUT cutting a
# real GitHub release tag.
#
# Purpose: dev a path the operator never sees. After this script
# exits, you can `cargo run -- ` the server with
# `code_sandbox.enabled: true` plus the two env vars below; the
# first execute_command MCP call will go through the full
# download → sha256-verify → install → mount flow against the local
# mirror.
#
# The only thing it does NOT validate is cosign keyless signing —
# that needs the real GitHub Actions OIDC issuer. For that, cut a
# release on a personal fork.
#
# Requires (host): bubblewrap, squashfuse, python3.
# Requires (binary): a debug build of ziee. The two env vars
# the server reads (CODE_SANDBOX_KNOWN_REVISIONS_OVERRIDE +
# loopback http:// in CODE_SANDBOX_ROOTFS_MIRROR) are physically
# compiled out in release builds.
#
# Usage:  scripts/dev-release.sh [flavor] [port]
#         flavor defaults to "minimal"
#         port   defaults to 8765

set -euo pipefail

FLAVOR="${1:-minimal}"
PORT="${2:-8765}"

case "$FLAVOR" in
  minimal|full) ;;
  *) echo "ERROR: flavor must be 'minimal' or 'full' (got '$FLAVOR')" >&2; exit 2 ;;
esac

if ! [[ "$PORT" =~ ^[0-9]+$ ]] || (( PORT < 1024 || PORT > 65535 )); then
  echo "ERROR: port must be 1024-65535 (got '$PORT')" >&2
  exit 2
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CACHE="$REPO_ROOT/.ziee-cache/sandbox-rootfs"
DEV_ROOT="$REPO_ROOT/.ziee-cache/dev-release"

# Schema is read from compat.toml so this stays in sync if schema bumps.
SCHEMA=$(awk -F'=' '/^current_schema/ {gsub(/ /, "", $2); print $2; exit}' \
  "$REPO_ROOT/src-app/sandbox-rootfs/compat.toml")
REVISION="r0"
ARCH=$(uname -m)
TAG="sandbox-rootfs-v${SCHEMA}.${REVISION}-${ARCH}"
ASSET="ziee-sandbox-rootfs-v${SCHEMA}.${REVISION}-${ARCH}-${FLAVOR}.squashfs"
SQFS="$CACHE/$ASSET"

echo "==> dev-release"
echo "    flavor:   $FLAVOR"
echo "    arch:     $ARCH"
echo "    tag:      $TAG"
echo "    port:     $PORT (loopback)"
echo

# Sanity checks before doing any work.
for cmd in python3 squashfuse bwrap sha256sum; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "ERROR: required command '$cmd' not on PATH" >&2
    exit 2
  fi
done

# Step 1: build the rootfs only if not already cached.
mkdir -p "$CACHE"
if [[ -f "$SQFS" ]]; then
  echo "==> Using cached $ASSET"
else
  echo "==> Building $FLAVOR rootfs (5-15 min first time)"
  "$REPO_ROOT/src-app/sandbox-rootfs/build.sh" --flavor "$FLAVOR"
fi

# Step 2: sha256.
SHA=$(sha256sum "$SQFS" | cut -d' ' -f1)
echo "==> sha256: $SHA"

# Step 3: dev-only known_revisions toml. signed=false so cosign is
# skipped (opportunistic verification path in runtime_fetch::fetch_flavor).
mkdir -p "$DEV_ROOT"
DEV_TOML="$DEV_ROOT/known_revisions.dev.toml"
cat > "$DEV_TOML" <<EOF
# Auto-generated by scripts/dev-release.sh. Do not commit.
# Loaded by ziee only when CODE_SANDBOX_KNOWN_REVISIONS_OVERRIDE
# points here AND the binary is a debug build.

[[revision]]
schema = $SCHEMA
revision = "$REVISION"
arch = "$ARCH"
flavor = "$FLAVOR"
sha256 = "$SHA"
signed = false
yanked = false
EOF

# Step 4: stage the artifact under the URL path the binary will request:
#   $base_url/$TAG/$ASSET
# Symlink keeps a single source of truth — no copy, no drift.
mkdir -p "$DEV_ROOT/$TAG"
ln -sf "$SQFS" "$DEV_ROOT/$TAG/$ASSET"

# Step 5: spin up the local registry. Bind to loopback only — the
# binary's debug-build allowance accepts http:// only for loopback.
echo "==> Starting http server on 127.0.0.1:$PORT (serving $DEV_ROOT)"
python3 -m http.server "$PORT" --bind 127.0.0.1 --directory "$DEV_ROOT" \
  >"$DEV_ROOT/http.log" 2>&1 &
HTTP_PID=$!
# Make sure we always tear it down — success, failure, or Ctrl+C.
cleanup() {
  if kill -0 "$HTTP_PID" 2>/dev/null; then
    kill "$HTTP_PID" 2>/dev/null || true
    wait "$HTTP_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT INT TERM

# Wait for the server to accept connections (typically <100ms).
for i in 1 2 3 4 5 6 7 8 9 10; do
  if curl -sf "http://127.0.0.1:$PORT/" >/dev/null 2>&1; then
    break
  fi
  if (( i == 10 )); then
    echo "ERROR: http server didn't come up on port $PORT" >&2
    tail "$DEV_ROOT/http.log" >&2 || true
    exit 1
  fi
  sleep 0.1
done

# Step 6: keep the mirror up for the server to consume.
#
# Server boot needs both env vars below to fetch from the local mirror
# instead of GitHub Releases. Keep this script in the foreground while
# you exercise the auto-fetch path; ctrl-C tears down the mirror.
echo
echo "==> Local mirror ready"
echo "    serving:  http://127.0.0.1:$PORT/$TAG/$ASSET"
echo "    sha256:   $SHA"
echo
echo "Boot the server in another terminal with:"
echo
echo "    cd $REPO_ROOT/src-app/server && \\"
echo "      CODE_SANDBOX_KNOWN_REVISIONS_OVERRIDE=$DEV_TOML \\"
echo "      CODE_SANDBOX_ROOTFS_MIRROR=http://127.0.0.1:$PORT \\"
echo "      CONFIG_FILE=config/dev.yaml cargo run --bin ziee"
echo
echo "Then any execute_command MCP call against /api/code-sandbox will"
echo "auto-fetch ${FLAVOR} from this mirror, sha256-verify, mount."
echo
echo "For bwrap-direct Tier 4/6 tests (skip server, mount directly):"
echo "    just sandbox-mount && just check-sandbox"
echo
echo "Press Ctrl-C to stop the mirror."

# Block until the user kills the script (or the http server dies for
# some other reason). The trap on HTTP_PID at the top tears it down.
wait "$HTTP_PID"
