// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  deleteRun: typeof import('./actions/deleteRun')['default']
  loadRuns: typeof import('./actions/loadRuns')['default']
}
