// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  cancelRecording: typeof import('./actions/cancelRecording')['default']
  fetchCapability: typeof import('./actions/fetchCapability')['default']
  setLiveCaptions: typeof import('./actions/setLiveCaptions')['default']
  startRecording: typeof import('./actions/startRecording')['default']
  stopRecording: typeof import('./actions/stopRecording')['default']
}
