// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  exchangeMagicLink: typeof import('./actions/exchangeMagicLink')['default']
  loadAuthConfig: typeof import('./actions/loadAuthConfig')['default']
  phonePasswordLogin: typeof import('./actions/phonePasswordLogin')['default']
}
