// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  close: typeof import('./actions/close')['default']
  openCreate: typeof import('./actions/openCreate')['default']
  openEdit: typeof import('./actions/openEdit')['default']
  setLoading: typeof import('./actions/setLoading')['default']
}
