// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  clearText: typeof import('./actions/clearText')['default']
  getBackupMessage: typeof import('./actions/getBackupMessage')['default']
  getText: typeof import('./actions/getText')['default']
  restoreFromBackup: typeof import('./actions/restoreFromBackup')['default']
  setBackupMessage: typeof import('./actions/setBackupMessage')['default']
  setClearMessage: typeof import('./actions/setClearMessage')['default']
  setGetMessage: typeof import('./actions/setGetMessage')['default']
  setSetMessage: typeof import('./actions/setSetMessage')['default']
  setText: typeof import('./actions/setText')['default']
}
