// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  clearUserAssistantsStoreError: typeof import('./actions/clearUserAssistantsStoreError')['default']
  createUserAssistant: typeof import('./actions/createUserAssistant')['default']
  deleteUserAssistant: typeof import('./actions/deleteUserAssistant')['default']
  getUserDefaultAssistant: typeof import('./actions/getUserDefaultAssistant')['default']
  loadUserAssistants: typeof import('./actions/loadUserAssistants')['default']
  updateUserAssistant: typeof import('./actions/updateUserAssistant')['default']
}
