// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  cancel: typeof import('./actions/cancel')['default']
  submitElicitation: typeof import('./actions/submitElicitation')['default']
  subscribe: typeof import('./actions/subscribe')['default']
  unsubscribe: typeof import('./actions/unsubscribe')['default']
}
