// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  closeProjectDrawer: typeof import('./actions/closeProjectDrawer')['default']
  openProjectDrawer: typeof import('./actions/openProjectDrawer')['default']
  setProjectDrawerLoading: typeof import('./actions/setProjectDrawerLoading')['default']
}
