// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  closeAssistantDrawer: typeof import('./actions/closeAssistantDrawer')['default']
  openAssistantDrawer: typeof import('./actions/openAssistantDrawer')['default']
  setAssistantDrawerLoading: typeof import('./actions/setAssistantDrawerLoading')['default']
}
