// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  load: typeof import('./actions/load')['default']
  loadCandidateModels: typeof import('./actions/loadCandidateModels')['default']
  loadFtsRebuildStatus: typeof import('./actions/loadFtsRebuildStatus')['default']
  loadRebuildStatus: typeof import('./actions/loadRebuildStatus')['default']
  triggerFtsRebuild: typeof import('./actions/triggerFtsRebuild')['default']
  triggerReembed: typeof import('./actions/triggerReembed')['default']
  update: typeof import('./actions/update')['default']
}
