// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  reset: typeof import('./actions/reset')['default']
  setAttempt: typeof import('./actions/setAttempt')['default']
  setStatus: typeof import('./actions/setStatus')['default']
}
