// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  deleteSkill: typeof import('./actions/deleteSkill')['default']
  getSkill: typeof import('./actions/getSkill')['default']
  importSkill: typeof import('./actions/importSkill')['default']
  installFromHub: typeof import('./actions/installFromHub')['default']
  loadSkills: typeof import('./actions/loadSkills')['default']
  updateSkill: typeof import('./actions/updateSkill')['default']
  validateSkill: typeof import('./actions/validateSkill')['default']
}
