// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  activate: typeof import('./actions/activate')['default']
  clearError: typeof import('./actions/clearError')['default']
  loadCatalog: typeof import('./actions/loadCatalog')['default']
  loadInstalled: typeof import('./actions/loadInstalled')['default']
  loadStatus: typeof import('./actions/loadStatus')['default']
  remove: typeof import('./actions/remove')['default']
}
