// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  createProvider: typeof import('./actions/createProvider')['default']
  deleteProvider: typeof import('./actions/deleteProvider')['default']
  loadProviders: typeof import('./actions/loadProviders')['default']
  testConfig: typeof import('./actions/testConfig')['default']
  testProvider: typeof import('./actions/testProvider')['default']
  updateProvider: typeof import('./actions/updateProvider')['default']
}
