// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  loadEmbeddingCapableModels: typeof import('./actions/loadEmbeddingCapableModels')['default']
  reset: typeof import('./actions/reset')['default']
  saveSettings: typeof import('./actions/saveSettings')['default']
  setEmbeddingModelId: typeof import('./actions/setEmbeddingModelId')['default']
  setEnableMemory: typeof import('./actions/setEnableMemory')['default']
}
