//! Integration tests for MCP content data types (McpContentData, Annotation, etc.)

use ziee_chat::{Annotation, McpContentData, RichFile};

#[test]
fn test_tool_use_conversion() {
    let tool_use = McpContentData::ToolUse {
        id: "toolu_01".to_string(),
        name: "get_weather".to_string(),
        server_id: "550e8400-e29b-41d4-a716-446655440000".to_string(),
        input: serde_json::json!({"location": "SF"}),
    };

    // Convert to MessageContentData
    let msg_content = tool_use.to_message_content();
    // Verify it's a ToolUse variant (MessageContentData variants are generated by macro)
    assert_eq!(msg_content.content_type(), "tool_use");

    // Convert back
    let recovered = McpContentData::from_message_content(&msg_content).unwrap();
    match recovered {
        McpContentData::ToolUse { id, name, server_id, .. } => {
            assert_eq!(id, "toolu_01");
            assert_eq!(name, "get_weather");
            assert_eq!(server_id, "550e8400-e29b-41d4-a716-446655440000");
        }
        _ => panic!("Expected ToolUse"),
    }
}

#[test]
fn test_tool_result_conversion() {
    let tool_result = McpContentData::ToolResult {
        tool_use_id: "toolu_01".to_string(),
        name: Some("get_weather".to_string()),
        content: "Sunny, 72°F".to_string(),
        is_error: Some(false),
        annotations: None,
        attachment: None,
    };

    // Convert to MessageContentData
    let msg_content = tool_result.to_message_content();

    // Convert back
    let recovered = McpContentData::from_message_content(&msg_content).unwrap();
    match recovered {
        McpContentData::ToolResult {
            tool_use_id,
            name,
            content,
            is_error,
            ..
        } => {
            assert_eq!(tool_use_id, "toolu_01");
            assert_eq!(name, Some("get_weather".to_string()));
            assert_eq!(content, "Sunny, 72°F");
            assert_eq!(is_error, Some(false));
        }
        _ => panic!("Expected ToolResult"),
    }
}

#[test]
fn test_to_content_block() {
    let tool_use = McpContentData::ToolUse {
        id: "toolu_01".to_string(),
        name: "get_weather".to_string(),
        server_id: "550e8400-e29b-41d4-a716-446655440000".to_string(),
        input: serde_json::json!({"location": "SF"}),
    };

    let block = tool_use.to_content_block().unwrap();
    match block {
        ai_providers::ContentBlock::ToolUse { name, .. } => {
            // Should reconstruct server_id__name format
            assert_eq!(name, "550e8400-e29b-41d4-a716-446655440000__get_weather");
        }
        _ => panic!("Expected ToolUse"),
    }
}

#[test]
fn test_from_content_block() {
    // AI providers return server_id__tool_name format
    let block = ai_providers::ContentBlock::ToolUse {
        id: "toolu_01".to_string(),
        name: "550e8400-e29b-41d4-a716-446655440000__get_weather".to_string(),
        input: serde_json::json!({"location": "SF"}),
    };

    let mcp_content = McpContentData::from_content_block(&block).unwrap();
    match mcp_content {
        McpContentData::ToolUse { id, name, server_id, .. } => {
            assert_eq!(id, "toolu_01");
            assert_eq!(name, "get_weather");
            assert_eq!(server_id, "550e8400-e29b-41d4-a716-446655440000");
        }
        _ => panic!("Expected ToolUse"),
    }
}

#[test]
fn test_tool_result_with_annotations_roundtrip() {
    // McpContentData is persisted as JSON in the DB, so test JSON roundtrip
    let tool_result = McpContentData::ToolResult {
        tool_use_id: "toolu_02".to_string(),
        name: Some("search".to_string()),
        content: "Some results [chunk-abc123-000001]".to_string(),
        is_error: Some(false),
        annotations: Some(vec![Annotation {
            id: "chunk-abc123-000001".to_string(),
            annotation_type: "citation".to_string(),
            label: Some("Paper on X (2023)".to_string()),
            content: "## Paper on X\n\n**Authors:** Doe, J.\n\n> Full chunk text...".to_string(),
        }]),
        attachment: None,
    };

    let json = serde_json::to_value(&tool_result).expect("Should serialize");
    let recovered: McpContentData = serde_json::from_value(json).expect("Should deserialize");
    match recovered {
        McpContentData::ToolResult { annotations, .. } => {
            let anns = annotations.expect("Annotations should be preserved");
            assert_eq!(anns.len(), 1);
            assert_eq!(anns[0].id, "chunk-abc123-000001");
            assert_eq!(anns[0].annotation_type, "citation");
            assert_eq!(anns[0].label, Some("Paper on X (2023)".to_string()));
            assert!(anns[0].content.contains("Paper on X"));
        }
        _ => panic!("Expected ToolResult"),
    }
}

#[test]
fn test_to_content_block_does_not_append_annotations_to_llm() {
    // Annotations are handled via AnnotatedText, not appended to LLM content
    let tool_result = McpContentData::ToolResult {
        tool_use_id: "toolu_03".to_string(),
        name: Some("search".to_string()),
        content: "Main result".to_string(),
        is_error: Some(false),
        annotations: Some(vec![Annotation {
            id: "chunk-aaa-000001".to_string(),
            annotation_type: "citation".to_string(),
            label: None,
            content: "## Doc A\n\n> Doc A content".to_string(),
        }]),
        attachment: None,
    };

    let block = tool_result.to_content_block().unwrap();
    match block {
        ai_providers::ContentBlock::ToolResult { content, .. } => {
            let text = content
                .iter()
                .filter_map(|b| match b {
                    ai_providers::ContentBlock::Text { text } => Some(text.as_str()),
                    _ => None,
                })
                .collect::<Vec<_>>()
                .join("");
            // Annotations must NOT be appended to LLM content — they go in AnnotatedText
            assert!(!text.contains("Sources:"), "Should not contain Sources section");
            assert_eq!(text.trim(), "Main result");
        }
        _ => panic!("Expected ToolResult"),
    }
}

#[test]
fn test_tool_result_no_annotations_no_sources_section() {
    let tool_result = McpContentData::ToolResult {
        tool_use_id: "toolu_04".to_string(),
        name: Some("search".to_string()),
        content: "Simple result".to_string(),
        is_error: Some(false),
        annotations: None,
        attachment: None,
    };

    let block = tool_result.to_content_block().unwrap();
    match block {
        ai_providers::ContentBlock::ToolResult { content, .. } => {
            let text = content
                .iter()
                .filter_map(|b| match b {
                    ai_providers::ContentBlock::Text { text } => Some(text.as_str()),
                    _ => None,
                })
                .collect::<Vec<_>>()
                .join("");
            assert!(
                !text.contains("Sources:"),
                "Should not contain Sources section"
            );
        }
        _ => panic!("Expected ToolResult"),
    }
}

#[test]
fn test_tool_result_with_attachment_roundtrip() {
    // McpContentData is persisted as JSON in the DB, so test JSON roundtrip
    let tool_result = McpContentData::ToolResult {
        tool_use_id: "toolu_05".to_string(),
        name: Some("generate_chart".to_string()),
        content: "Chart generated".to_string(),
        is_error: Some(false),
        annotations: None,
        attachment: Some(RichFile {
            filename: "chart.png".to_string(),
            mime_type: "image/png".to_string(),
            data: "base64encodeddata".to_string(),
        }),
    };

    let json = serde_json::to_value(&tool_result).expect("Should serialize");
    let recovered: McpContentData = serde_json::from_value(json).expect("Should deserialize");
    match recovered {
        McpContentData::ToolResult { attachment, .. } => {
            let file = attachment.expect("Attachment should be preserved");
            assert_eq!(file.filename, "chart.png");
            assert_eq!(file.mime_type, "image/png");
            assert_eq!(file.data, "base64encodeddata");
        }
        _ => panic!("Expected ToolResult"),
    }
}
