// AUTO-GENERATED — do not edit. Regenerate with `just openapi-regen`.
// Human-readable permission labels, split out of `types.ts` so they load only
// where used (the permission picker) instead of on every page.

export const PermissionDescriptions: Record<string, string> = {
  AssistantsCreate: 'Create user assistants',
  AssistantsDelete: 'Delete user assistants',
  AssistantsEdit: 'Edit user assistants',
  AssistantsRead: 'Read user assistants',
  AssistantsTemplateCreate: 'Create system-wide template assistants',
  AssistantsTemplateDelete: 'Delete system-wide template assistants',
  AssistantsTemplateEdit: 'Edit system-wide template assistants',
  AssistantsTemplateRead: 'Read system-wide template assistants',
  AuthProvidersManage: 'Create, update, delete, enable/disable, and test auth providers.',
  AuthProvidersRead: 'List configured auth providers and view their (masked) config.',
  BranchesCreate: 'Create message branches for edit/regenerate',
  BranchesSwitch: 'Switch between conversation branches',
  CitationsManage: 'Create, import, verify, remove, and organize citations + CSL styles.',
  CitationsUse: 'Use the citation tools and read your bibliography library.',
  CodeSandboxEnvironmentsManage: 'Trigger pre-fetch + cache management of sandbox rootfs environments.',
  CodeSandboxEnvironmentsRead: 'List rootfs versions and watch install progress.',
  CodeSandboxResourceLimitsManage: 'Update the sandbox memory/CPU/PID caps + per-exec timeout + idle-evict policy.',
  CodeSandboxResourceLimitsRead: 'Read the sandbox resource limits configuration.',
  ConversationsCreate: 'Create new chat conversations',
  ConversationsDelete: 'Delete chat conversations',
  ConversationsEdit: 'Edit conversation titles and metadata',
  ConversationsRead: 'View chat conversations',
  CoreMemoryRead: 'Read own assistant core memory blocks.',
  CoreMemoryWrite: 'Upsert / delete own assistant core memory blocks.',
  FileRagAdminManage: 'Update Document-RAG admin settings, trigger re-embed and backfill.',
  FileRagAdminRead: 'Read Document-RAG admin settings (embedding model, tuning).',
  FilesDelete: 'Delete files',
  FilesDownload: 'Download file content',
  FilesGenerateToken: 'Generate download tokens',
  FilesPreview: 'View file thumbnails and previews',
  FilesRead: 'View file metadata and list files',
  FilesUpload: 'Upload new files',
  GroupsAssignUsers: 'Assign users to groups and remove users from groups',
  GroupsCreate: 'Create new groups',
  GroupsDelete: 'Delete non-system groups',
  GroupsEdit: 'Edit existing group information and permissions',
  GroupsRead: 'View groups and group information',
  HardwareMonitor: 'Monitor real-time hardware usage',
  HardwareRead: 'View hardware information',
  HubAssistantsCreate: 'Create assistants from hub',
  HubAssistantsRead: 'View hub assistants',
  HubAssistantsRefresh: 'Refresh hub assistants from GitHub',
  HubAssistantsVersionRead: 'View hub assistants version information',
  HubCatalogManage: 'Refresh + activate hub catalog versions',
  HubCatalogRead: 'View hub catalog versions + pending updates',
  HubMcpServersCreate: 'Create MCP servers from hub',
  HubMCPServersRead: 'View hub MCP servers',
  HubMCPServersRefresh: 'Refresh hub MCP servers from GitHub',
  HubMCPServersVersionRead: 'View hub MCP servers version information',
  HubModelsCreate: 'Download models from hub',
  HubModelsRead: 'View hub models',
  HubModelsRefresh: 'Refresh hub models from GitHub',
  HubModelsVersionRead: 'View hub models version information',
  JsToolSettingsManage: 'Update the run_js (js_tool) memory/stack/wall-clock/approval-timeout/concurrency/trace caps.',
  JsToolSettingsRead: 'Read the run_js (js_tool) resource-limits configuration.',
  KnowledgeBaseManage: 'Create, rename, delete knowledge bases and manage their documents.',
  KnowledgeBaseUse: 'Search your knowledge bases and attach them to conversations/projects.',
  LitSearchAdminManage: 'Update literature search settings, active sources, and source API keys.',
  LitSearchAdminRead: 'Read literature search settings (enable, active sources, caps).',
  LitSearchUse: 'Use the literature search + screening tools.',
  LlmModelsCreate: 'Create new LLM models',
  LlmModelsDelete: 'Delete LLM models',
  LlmModelsDownloadsCancel: 'Cancel active downloads',
  LlmModelsDownloadsDelete: 'Delete download instances',
  LlmModelsDownloadsRead: 'Read download instances',
  LlmModelsEdit: 'Edit existing LLM models',
  LlmModelsRead: 'Read LLM models',
  LlmProvidersAssignGroups: 'Assign LLM providers to user groups',
  LlmProvidersCreate: 'Create new LLM provider configurations',
  LlmProvidersDelete: 'Delete non-built-in LLM providers',
  LlmProvidersEdit: 'Edit existing LLM provider information and settings',
  LlmProvidersRead: 'View LLM providers and list available providers',
  LlmRepositoriesCreate: 'Create new LLM repositories',
  LlmRepositoriesDelete: 'Delete non-built-in LLM repositories',
  LlmRepositoriesEdit: 'Edit existing LLM repository information and authentication',
  LlmRepositoriesRead: 'View LLM repositories and list repositories',
  LocalRuntimeLogs: 'View runtime instance logs',
  LocalRuntimeManage: 'Start, stop, and restart local LLM runtime instances',
  LocalRuntimeRead: 'View local LLM runtime instances and their status',
  McpServersAdminCreate: 'Create system MCP servers',
  McpServersAdminDelete: 'Delete system MCP servers',
  McpServersAdminEdit: 'Edit system MCP servers and manage group assignments',
  McpServersAdminRead: 'View system MCP servers',
  McpServersCreate: 'Create MCP servers',
  McpServersDelete: 'Delete MCP servers',
  McpServersEdit: 'Edit MCP servers',
  McpServersRead: 'View MCP servers',
  McpUserPolicyEdit: 'Edit MCP user policy (allowed transports + sandbox flavor)',
  MemoryAdminManage: 'Update memory admin settings (embedding model, enable/disable).',
  MemoryAdminRead: 'Read memory admin settings (embedding model, defaults).',
  MemoryRead: 'List and read own memories.',
  MemoryWrite: 'Create, edit, and delete own memories.',
  MessagesCreate: 'Send messages in conversations',
  MessagesDelete: 'Delete messages from conversations',
  MessagesRead: 'Read messages in conversations',
  NotificationsRead: 'Read and manage your own notifications.',
  ProfileEdit: 'Edit own profile information',
  ProfileRead: 'View own profile information',
  ProjectsCreate: 'Create chat projects',
  ProjectsDelete: 'Delete chat projects',
  ProjectsEdit: 'Edit chat projects (incl. attach/detach files)',
  ProjectsRead: 'Read chat projects',
  RuntimeSettingsManage: 'Modify runtime singleton settings (idle/auto-start/drain)',
  RuntimeSettingsRead: 'Read runtime singleton settings (idle/auto-start/drain)',
  RuntimeVersionCreate: 'Download and register new runtime versions',
  RuntimeVersionDelete: 'Delete runtime versions',
  RuntimeVersionRead: 'View runtime versions and check for updates',
  RuntimeVersionUpdate: 'Update runtime version settings and defaults',
  SchedulerAdminManage: 'Change deployment-wide scheduler settings.',
  SchedulerAdminRead: 'View deployment-wide scheduler settings.',
  SchedulerUse: 'Create, run, test, and manage your own scheduled/recurring tasks.',
  ServerUpdateRead: 'View the cached server update-availability status.',
  SessionSettingsManage: 'Update session settings (access-token TTL + max session length).',
  SessionSettingsRead: 'Read session settings (access-token TTL + max session length).',
  SkillsAssignToGroups: 'Manage group assignments for system-scope skills',
  SkillsInstall: 'Install user-scope skills (from hub or local import)',
  SkillsManageSystem: 'Install / edit / delete system-scope skills (admin)',
  SkillsRead: 'View installed skills',
  SummarizationSettingsManage: 'Update deployment-wide summarization settings (enable, model, thresholds, prompts).',
  SummarizationSettingsRead: 'Read deployment-wide summarization settings (model + thresholds + prompt overrides).',
  UserLlmProvidersRead: 'View available LLM providers and models',
  UsersCreate: 'Create new user accounts',
  UsersDelete: 'Delete user accounts',
  UsersEdit: 'Edit existing user information',
  UsersRead: 'View user information and list users',
  UsersResetPassword: 'Reset user passwords',
  UsersToggleStatus: 'Enable or disable user accounts',
  VoiceAdminManage: 'Update voice settings, manage whisper runtime versions and models, and control the instance.',
  VoiceAdminRead: 'Read voice dictation settings, runtime versions, model and instance state.',
  VoiceTranscribe: 'Record audio and transcribe it into the chat composer.',
  WebSearchAdminManage: 'Update web search settings, provider chain, and provider API keys.',
  WebSearchAdminRead: 'Read web search settings (enable, provider chain, caps).',
  WebSearchUse: 'Use the web search + page-fetch tools.',
  WorkflowsAssignToGroups: 'Manage group assignments for system-scope workflows',
  WorkflowsExecute: 'Kick off a workflow run',
  WorkflowsInstall: 'Install user-scope workflows',
  WorkflowsManage: 'Edit / delete own user-scope workflows',
  WorkflowsManageSystem: 'Install / edit / delete system-scope workflows (admin)',
  WorkflowsRead: 'View installed workflows'
}
