/**
 * Generated API endpoint definitions
 * Auto-generated from OpenAPI specification
 * 
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY ⚠️
 * This file is automatically generated from the OpenAPI specification generated from the server code.
 */

// =============================================================================
// TYPE DEFINITIONS
// =============================================================================

export type ApprovalMode = 'disabled' | 'auto_approve' | 'manual_approve'

export interface AssignProviderToGroupRequest {
  group_id: string
}

export interface AssignUserToGroupRequest {
  group_id: string
  user_id: string
}

export interface Assistant {
  description?: string
  created_at: string
  created_by?: string
  enabled: boolean
  id: string
  instructions?: string
  is_default: boolean
  is_template: boolean
  name: string
  parameters?: any
  updated_at: string
}

export interface AssistantFromHubResponse {
  assistant: Assistant
  hub_tracking: HubEntity
}

export interface AssistantListResponse {
  assistants: Assistant[]
  total: number
}

export interface AuthResponse {
  access_token: string
  expires_in: number
  refresh_token: string
  token_type: string
  user: User
}

export interface AutoApprovedServer {
  server_id: string
  tools: string[]
}

export interface AvailableUpdatesResponse {
  available_versions: string[]
  engine: string
}

export interface Branch {
  conversation_id: string
  created_at: string
  created_from_message_id?: string
  fork_level: string
  id: string
  parent_branch_id?: string
}

export interface CPUInfo {
  architecture: string
  base_frequency?: number
  cores: number
  max_frequency?: number
  model: string
  threads?: number
}

export interface CPUUsage {
  frequency?: number
  temperature?: number
  usage_percentage: number
}

export interface CallToolRequest {
  arguments: any
}

export interface CallToolResponse {
  content: ToolContent[]
  is_error: boolean
}

export interface ChatStreamChunk {
  branch_id?: string
  content?: ContentBlockDelta[]
  conversation_id?: string
  error?: StreamError
  finish_reason?: string
  message_id?: string
  usage?: Usage
}

export interface CodeSandboxResourceLimits {
  address_space_bytes: number
  cpu_max: string
  cpu_secs_max: number
  created_at: string
  fsize_bytes: number
  mac_vm_ram_mib: number
  mac_vm_vcpus: number
  memory_max_bytes: number
  memory_swap_max_bytes: number
  nofile_max: number
  nproc_max: number
  pids_max: number
  timeout_secs: number
  updated_at: string
  vm_idle_evict_secs: number
  vm_max_concurrent_execs: number
}

export type ContentBlockDelta = {
  type: 'text_delta'
  delta: string
  index: number
} | {
  type: 'thinking_delta'
  delta: string
  index: number
} | {
  type: 'tool_use_delta'
  id?: string | null
  index: number
  input_delta?: string | null
  name?: string | null
}

export interface Conversation {
  title?: string
  active_branch_id?: string
  created_at: string
  id: string
  model_id?: string
  updated_at: string
  user_id: string
}

export interface ConversationMcpSettingsResponse {
  approval_mode: ApprovalMode
  auto_approved_tools: AutoApprovedServer[]
  conversation_id: string
  created_at: string
  disabled_servers: DisabledServer[]
  id: string
  loop_settings: LoopSettings
  updated_at: string
  user_id: string
}

export interface ConversationResponse {
  title?: string
  active_branch_id?: string
  created_at: string
  id: string
  message_count: number
  model_id?: string
  updated_at: string
  user_id: string
}

export interface CreateAssistantFromHubRequest {
  description?: string
  enabled?: boolean
  hub_id: string
  instructions?: string
  is_default?: boolean
  name?: string
  parameters?: any
}

export interface CreateAssistantRequest {
  description?: string
  enabled?: boolean
  instructions?: string
  is_default?: boolean
  is_template?: boolean
  name?: string
  parameters?: ModelParameters
}

export interface CreateBranchRequest {
  fork_level?: string
  from_message_id: string
}

export interface CreateConversationRequest {
  title?: string
  model_id?: string
}

export interface CreateGroupRequest {
  description?: string
  name: string
  permissions: string[]
}

export interface CreateLlmModelRequest {
  description?: string
  capabilities?: ModelCapabilities
  display_name: string
  enabled?: boolean
  engine_settings?: ModelEngineSettings
  engine_type: EngineType
  file_format: FileFormat
  name: string
  parameters?: ModelParameters
  provider_id: string
}

export interface CreateLlmProviderRequest {
  api_key?: string
  base_url?: string
  enabled?: boolean
  name: string
  provider_type: string
  proxy_settings?: ProxySettings
}

export interface CreateLlmRepositoryRequest {
  auth_config?: RepositoryAuthConfig
  auth_type: string
  enabled?: boolean
  name: string
  url: string
}

export interface CreateMcpServerFromHubRequest {
  display_name?: string
  enabled?: boolean
  hub_id: string
  name?: string
}

export interface CreateMcpServerRequest {
  description?: string
  args?: string[]
  command?: string
  display_name: string
  enabled?: boolean
  environment_variables?: any
  headers?: any
  max_concurrent_sessions?: number
  name: string
  supports_sampling?: boolean
  timeout_seconds?: number
  transport_type: TransportType
  url?: string
  usage_mode?: UsageMode
}

export interface CreateModelFromHubRequest {
  display_name?: string
  enabled?: boolean
  hub_id: string
  provider_id: string
  quantization_name?: string
}

export interface CreateUserRequest {
  display_name?: string
  email: string
  password: string
  permissions?: string[]
  username: string
}

export interface DeleteVersionQuery {
  remove_binary?: boolean
}

export type DeviceType = 'cpu' | 'cuda' | 'metal' | 'rocm' | 'vulkan' | 'opencl' | 'auto'

export interface DisabledServer {
  server_id: string
  tools: string[]
}

export interface DownloadFromRepositoryRequest {
  description?: string
  capabilities?: ModelCapabilities
  display_name: string
  engine_settings?: ModelEngineSettings
  engine_type?: EngineType
  file_format: FileFormat
  main_filename: string
  name: string
  parameters?: ModelParameters
  provider_id: string
  repository_branch?: string
  repository_id: string
  repository_path: string
}

export interface DownloadInstance {
  completed_at?: string
  created_at: string
  error_message?: string
  id: string
  model_id?: string
  progress_data?: DownloadProgressData
  provider_id: string
  repository_id: string
  request_data: DownloadRequestData
  started_at: string
  status: DownloadStatus
  updated_at: string
}

export interface DownloadInstanceListResponse {
  downloads: DownloadInstance[]
  page: number
  per_page: number
  total: number
}

export interface DownloadPaginationQuery {
  page?: number
  per_page?: number
  status?: string
}

export type DownloadPhase = 'created' | 'connecting' | 'analyzing' | 'downloading' | 'receiving' | 'resolving' | 'checkingout' | 'committing' | 'complete' | 'error'

export interface DownloadProgressData {
  current: number
  eta_seconds: number
  message: string
  phase: DownloadPhase
  speed_bps: number
  total: number
}

export interface DownloadProgressUpdate {
  current?: number
  error_message?: string
  eta_seconds?: number
  id: string
  message?: string
  model_id?: string
  phase: DownloadPhase
  provider_id: string
  speed_bps?: number
  status: string
  total?: number
}

export interface DownloadRequestData {
  description?: string
  capabilities?: ModelCapabilities
  display_name?: string
  engine_settings?: ModelEngineSettings
  engine_type?: EngineType
  file_format?: string
  files?: string[]
  main_filename?: string
  model_name: string
  parameters?: ModelParameters
  quantization?: string
  repository_path?: string
  revision?: string
}

export type DownloadStatus = 'pending' | 'downloading' | 'completed' | 'failed' | 'cancelled'

export interface DownloadTokenQuery {
  token: string
}

export interface DownloadTokenResponse {
  expires_in: number
  token: string
}

export interface DownloadVersionRequest {
  arch: string
  backend: string
  engine: string
  platform: string
  version: string
}

export interface DownloadVersionResponse {
  downloaded: boolean
  message: string
  version: RuntimeVersionResponse
}

export interface EditMessageRequest {
  content: string
}

export interface EditMessageResponse {
  branch: Branch
  message: Message
}

export type EngineType = 'mistralrs' | 'llamacpp' | 'none'

export interface EnvironmentInfo {
  description: string
  approximate_size_mb: number
  cached: boolean
  cached_size_bytes?: number
  flavor: string
  mounted: boolean
}

export interface EnvironmentsResponse {
  available: EnvironmentInfo[]
}

export type FetchPhase = 'resolving' | 'downloading' | 'verifying_sha256' | 'verifying_cosign' | 'installing'

export interface File {
  checksum?: string
  created_at: string
  created_by: string
  file_size: number
  filename: string
  has_thumbnail: boolean
  id: string
  mime_type?: string
  preview_page_count: number
  processing_metadata: any
  text_page_count: number
  updated_at: string
  user_id: string
}

export type FileFormat = 'safetensors' | 'pytorch' | 'gguf'

export type FileFormat2 = 'gguf' | 'safetensors' | 'pytorch'

export interface FileListResponse {
  files: File[]
  page: number
  per_page: number
  total: number
}

export interface GPUComputeCapabilities {
  cuda_support: boolean
  cuda_version?: string
  metal_support: boolean
  opencl_support: boolean
  vulkan_support?: boolean
}

export interface GPUDevice {
  compute_capabilities: GPUComputeCapabilities
  device_id: string
  driver_version?: string
  memory?: number
  name: string
  vendor: string
}

export interface GPUUsage {
  device_id: string
  device_name: string
  memory_total?: number
  memory_usage_percentage?: number
  memory_used?: number
  power_usage?: number
  temperature?: number
  utilization_percentage?: number
}

export interface GetPromptRequest {
  arguments?: any
  name: string
}

export interface GetPromptResponse {
  description?: string
  messages: any[]
}

export interface GetUserProvidersResponse {
  providers: ProviderWithModels[]
}

export interface GetUserProvidersResponse2 {
  providers: ProviderWithModels2[]
}

export interface Group {
  description?: string
  created_at: string
  id: string
  is_active: boolean
  is_default: boolean
  is_system: boolean
  name: string
  permissions: string[]
  updated_at: string
}

export interface GroupListResponse {
  groups: Group[]
  page: number
  per_page: number
  total: number
  total_pages: number
}

export interface GroupProvidersResponse {
  providers: LlmProvider[]
}

export interface GroupSystemServersResponse {
  servers: McpServer[]
}

export interface HardwareInfo {
  cpu: CPUInfo
  gpu_devices: GPUDevice[]
  memory: MemoryInfo
  operating_system: OperatingSystemInfo
}

export interface HardwareInfoResponse {
  hardware: HardwareInfo
}

export interface HardwareUsageUpdate {
  cpu: CPUUsage
  gpu_devices: GPUUsage[]
  memory: MemoryUsage
  timestamp: string
}

export interface HealthCheckResponse {
  healthy: boolean
  message?: string
  response_time_ms?: number
}

export interface HealthResponse {
  status: string
}

export interface HubAssistant {
  description?: string
  author?: string
  capabilities_required?: string[]
  category?: string
  created_ids?: string[]
  display_name: string
  example_prompts?: string[]
  id: string
  instructions?: string
  name: string
  parameters: any
  popularity_score?: number
  recommended_models?: string[]
  tags?: string[]
  use_cases?: string[]
}

export interface HubEntity {
  created_at: string
  created_by?: string
  entity_id: string
  entity_type: string
  hub_category: string
  hub_id: string
  id: string
}

export interface HubLocalProvider {
  id: string
  name: string
}

export interface HubLocalProvidersResponse {
  providers: HubLocalProvider[]
}

export interface HubMCPServer {
  description?: string
  args?: string[]
  author?: string
  category?: string
  command?: string
  created_ids?: string[]
  display_name: string
  documentation_url?: string
  download_count?: number
  environment_variables?: any
  example_prompts?: string[]
  example_tools?: string[]
  headers?: any
  homepage?: string
  icon_url?: string
  id: string
  license?: string
  minimum_version?: string
  name: string
  platform_support?: string[]
  popularity_score?: number
  rating?: number
  repository_url?: string
  requires_desktop?: boolean
  supports_sampling?: boolean
  tags?: string[]
  tool_categories?: string[]
  tool_count?: number
  transport_type?: string
  url?: string
  use_cases?: string[]
  version?: string
}

export interface HubModel {
  description?: string
  auth_required?: boolean
  author?: string
  capabilities?: ModelCapabilities2
  context_length?: number
  created_ids?: string[]
  display_name: string
  file_format: FileFormat2
  homepage_url?: string
  id: string
  language_support?: string[]
  license?: string
  main_filename: string
  name: string
  popularity_score: number
  public?: boolean
  quantization_options?: HubModelQuantizationOption[]
  recommended_engine?: string
  recommended_engine_settings?: any
  recommended_parameters?: any
  repository_path: string
  repository_url: string
  size_gb: number
  tags?: string[]
}

export interface HubModelQuantizationOption {
  main_filename: string
  name: string
  size_gb?: number
}

export interface HubQuery {
  lang?: string
}

export interface HubRefreshResponse {
  updated: boolean
  version: string
}

export interface HubVersionResponse {
  last_updated?: string
  version: string
}

export type ImageSource = {
  type: 'url'
  url: string
} | {
  type: 'base64'
  data: string
  media_type: string
} | {
  type: 'file'
  file_id: string
}

export interface InstanceResponse {
  base_url: string
  error_message?: string
  id: string
  last_health_check?: string
  local_port: number
  model_id: string
  provider_id: string
  runtime_version_id?: string
  started_at: string
  status: string
  stopped_at?: string
}

export interface InstanceStatusResponse {
  base_url?: string
  model_id: string
  status: string
  uptime_seconds?: number
}

export interface ListModelsQuery {
  page?: number
  perPage?: number
  providerId?: string
}

export interface ListPrefetchTasksResponse {
  tasks: PrefetchTaskSummary[]
}

export interface ListPromptsResponse {
  prompts: Prompt[]
}

export interface ListResourcesResponse {
  resources: Resource[]
}

export interface ListToolsResponse {
  tools: Tool[]
}

export interface ListVersionsQuery {
  engine?: string
}

export interface LlamaCppSettings {
  batch_size?: number
  cache_type_k?: string
  cache_type_v?: string
  cont_batching?: boolean
  ctx_size?: number
  device_ids?: number[]
  device_type?: DeviceType
  flash_attn?: boolean
  keep?: number
  main_gpu?: number
  mlock?: boolean
  n_gpu_layers?: number
  no_kv_offload?: boolean
  no_mmap?: boolean
  numa?: string
  parallel?: number
  rope_freq_base?: number
  rope_freq_scale?: number
  rope_scaling?: string
  seed?: number
  split_mode?: string
  tensor_split?: string
  threads?: number
  threads_batch?: number
  ubatch_size?: number
}

export interface LlmModel {
  description?: string
  capabilities: ModelCapabilities
  created_at: string
  display_name: string
  enabled: boolean
  engine_settings?: ModelEngineSettings
  engine_type: EngineType
  file_format: FileFormat
  file_size_bytes?: number
  id: string
  is_active: boolean
  is_deprecated: boolean
  name: string
  parameters: ModelParameters
  pid?: number
  port?: number
  provider_id: string
  required_runtime_version_id?: string
  updated_at: string
  validation_issues?: string[]
  validation_status?: string
}

export interface LlmModelListResponse {
  models: LlmModel[]
  page: number
  per_page: number
  total: number
}

export interface LlmProvider {
  api_key?: string
  base_url?: string
  built_in: boolean
  created_at: string
  default_runtime_version_id?: string
  enabled: boolean
  id: string
  name: string
  provider_type: string
  proxy_settings: ProxySettings
  updated_at: string
}

export interface LlmProviderListResponse {
  page: number
  per_page: number
  providers: LlmProvider[]
  total: number
}

export interface LlmRepository {
  auth_config: RepositoryAuthConfig
  auth_type: string
  built_in: boolean
  created_at: string
  enabled: boolean
  id: string
  name: string
  updated_at: string
  url: string
}

export interface LlmRepositoryListResponse {
  page: number
  per_page: number
  repositories: LlmRepository[]
  total: number
}

export interface LoginRequest {
  password: string
  provider?: string
  username: string
}

export interface LogsResponse {
  logs: string[]
  model_id: string
}

export interface LoopSettings {
  force_final_answer?: boolean
  max_iteration?: number
  per_tool_max_iteration?: PerToolLimit[]
  stop_when_no_tool_calling?: boolean
  stop_when_tools_called?: ToolIdentifier[]
}

export interface McpConfig {
  mcp_servers: McpServerConfig[]
}

export interface McpServer {
  description?: string
  args: any
  command?: string
  created_at: string
  display_name: string
  enabled: boolean
  environment_variables: any
  headers: any
  id: string
  is_built_in: boolean
  is_system: boolean
  max_concurrent_sessions?: number
  name: string
  supports_sampling: boolean
  timeout_seconds: number
  transport_type: TransportType
  updated_at: string
  url?: string
  usage_mode: UsageMode
  user_id?: string
}

export interface McpServerConfig {
  server_id: string
  tools?: string[]
}

export interface McpServerFromHubResponse {
  hub_tracking: HubEntity
  server: McpServer
}

export interface McpServerListResponse {
  page: number
  per_page: number
  servers: McpServer[]
  total: number
  total_pages: number
}

export interface McpServerOAuthConfigResponse {
  client_id: string
  created_at: string
  has_client_secret: boolean
  resource?: string
  scopes?: string
  server_id: string
  updated_at: string
}

export interface McpSettingsResponse {
  settings?: ConversationMcpSettingsResponse
}

export interface MeResponse {
  permissions: string[]
  user: User
}

export interface MemoryInfo {
  total_ram: number
  total_swap?: number
}

export interface MemoryUsage {
  available_ram: number
  available_swap?: number
  usage_percentage: number
  used_ram: number
  used_swap?: number
}

export interface Message {
  assistant_id?: string
  created_at: string
  edit_count: number
  id: string
  mcp_server_ids?: string[]
  model_id?: string
  originated_from_id: string
  role: string
}

export interface MessageContent {
  content: MessageContentData
  content_type: string
  created_at: string
  id: string
  message_id: string
  sequence_order: number
  updated_at: string
}

export interface MessageContentDataText {
  type: 'text'
  text: string
}
export interface MessageContentDataThinking {
  type: 'thinking'
  metadata?: ThinkingMetadata | null
  thinking: string
}
export interface MessageContentDataImage {
  type: 'image'
  alt_text?: string | null
  source: ImageSource
}
export interface MessageContentDataFileAttachment {
  type: 'file_attachment'
  file_id: string
  file_size: number
  filename: string
  mime_type?: string | null
}
export interface MessageContentDataToolUse {
  type: 'tool_use'
  id: string
  input: any
  name: string
  server_id: string
}
export interface MessageContentDataToolResult {
  type: 'tool_result'
  content: string
  hidden_content?: string | null
  is_error?: boolean | null
  name?: string | null
  tool_use_id: string
}
export interface MessageContentDataElicitationRequest {
  type: 'elicitation_request'
  elicitation_id: string
  message: string
  requested_schema: any
  response_content?: any
  server: string
  status: string
}

export type MessageContentData = MessageContentDataText | MessageContentDataThinking | MessageContentDataImage | MessageContentDataFileAttachment | MessageContentDataToolUse | MessageContentDataToolResult | MessageContentDataElicitationRequest

export interface MessageWithContent {
  assistant_id?: string
  contents: MessageContent[]
  created_at: string
  edit_count: number
  id: string
  mcp_server_ids?: string[]
  model_id?: string
  originated_from_id: string
  role: string
}

export type MistralRsCommand = 'plain' | 'gguf' | 'run' | 'vision-plain' | 'x-lora' | 'lora' | 'toml'

export interface MistralRsSettings {
  arch?: string
  chat_template?: string
  command?: MistralRsCommand
  cpu?: boolean
  device_ids?: number[]
  device_type?: DeviceType
  dtype?: string
  enable_search?: boolean
  enable_thinking?: boolean
  in_situ_quant?: string
  interactive_mode?: boolean
  jinja_explicit?: string
  log_file?: string
  max_edge?: number
  max_image_length?: number
  max_num_images?: number
  max_seq_len?: number
  max_seqs?: number
  model_id_name?: string
  no_kv_cache?: boolean
  no_paged_attn?: boolean
  num_device_layers?: string[]
  paged_attn?: boolean
  paged_attn_block_size?: number
  paged_attn_gpu_mem?: number
  paged_attn_gpu_mem_usage?: number
  paged_ctxt_len?: number
  prefix_cache_n?: number
  prompt_chunksize?: number
  quantized_filename?: string
  search_bert_model?: string
  seed?: number
  serve_ip?: string
  token_source?: string
  tokenizer_json?: string
  truncate_sequence?: boolean
  weight_file?: string
}

export interface ModelCapabilities {
  audio?: boolean
  chat?: boolean
  code_interpreter?: boolean
  image_generator?: boolean
  text_embedding?: boolean
  tools?: boolean
  vision?: boolean
}

export interface ModelCapabilities2 {
  audio?: boolean
  chat?: boolean
  code_interpreter?: boolean
  image_generator?: boolean
  text_embedding?: boolean
  tools?: boolean
  vision?: boolean
}

export interface ModelEngineSettings {
  llamacpp?: LlamaCppSettings
  mistralrs?: MistralRsSettings
}

export interface ModelFromHubResponse {
  download: DownloadInstance
  hub_tracking: HubEntity
}

export interface ModelParameters {
  frequency_penalty?: number
  max_tokens?: number
  min_p?: number
  presence_penalty?: number
  repeat_last_n?: number
  repeat_penalty?: number
  seed?: number
  stop?: string[]
  temperature?: number
  top_k?: number
  top_p?: number
}

export interface OperatingSystemInfo {
  architecture: string
  kernel_version?: string
  name: string
  version: string
}

export interface PaginationQuery {
  page?: number
  per_page?: number
}

export interface PaginationQuery2 {
  page?: number
  per_page?: number
}

export interface PaginationQuery3 {
  limit: number
  page: number
}

export interface PaginationQuery4 {
  limit?: number
  page?: number
}

export interface PendingApprovalsResponse {
  approvals: ToolUseApproval[]
}

export interface PerToolLimit {
  max_iteration: number
  server_id: string
  tool_name: string
}

export interface PermissionDetail {
  description: string
  name: string
  value: string
}

export interface PermissionError {
  details: PermissionErrorDetails
  error: string
  error_code: string
}

export interface PermissionErrorDetails {
  required_permissions: PermissionDetail[]
}

export interface PingResponse {
  ok: boolean
}

export type PrefetchStatus = 'running' | 'completed' | 'failed' | 'already_cached'

export interface PrefetchTaskSummary {
  error?: string
  flavor: string
  last_phase?: FetchPhase
  outcome?: SSEPrefetchCompleteData
  started_at: string
  status: PrefetchStatus
  task_id: string
}

export interface PreviewQuery {
  page?: number
}

export interface Prompt {
  description?: string
  arguments?: PromptArgument[]
  name: string
}

export interface PromptArgument {
  description?: string
  name: string
  required?: boolean
}

export interface ProviderInstancesResponse {
  instances: InstanceResponse[]
  provider_id: string
}

export interface ProviderWithModels {
  api_key?: string
  api_key_configured: boolean
  base_url?: string
  built_in: boolean
  created_at: string
  default_runtime_version_id?: string
  enabled: boolean
  id: string
  llm_models: LlmModel[]
  name: string
  provider_type: string
  proxy_settings: ProxySettings
  updated_at: string
}

export interface ProviderWithModels2 {
  api_key?: string
  base_url?: string
  built_in: boolean
  created_at: string
  default_runtime_version_id?: string
  enabled: boolean
  id: string
  llm_models: LlmModel[]
  name: string
  provider_type: string
  proxy_settings: ProxySettings
  updated_at: string
}

export interface ProxySettings {
  enabled?: boolean
  ignore_ssl_certificates?: boolean
  no_proxy?: string
  password?: string
  url?: string
  username?: string
}

export interface ReadResourceRequest {
  uri: string
}

export interface ReadResourceResponse {
  content: any
}

export interface RefreshTokenRequest {
  refresh_token: string
}

export interface RegisterRequest {
  display_name?: string
  email: string
  password: string
  username: string
}

export interface RepositoryAuthConfig {
  api_key?: string
  auth_test_api_endpoint?: string
  password?: string
  token?: string
  username?: string
}

export interface ResetPasswordRequest {
  new_password: string
  user_id: string
}

export interface Resource {
  description?: string
  mime_type?: string
  name: string
  uri: string
}

export interface RespondToElicitationRequest {
  action: string
  content?: any
}

export interface RespondToElicitationResponse {
  success: boolean
}

export interface RuntimeVersionListResponse {
  versions: RuntimeVersionResponse[]
}

export interface RuntimeVersionResponse {
  arch: string
  backend: string
  binary_path: string
  created_at: string
  engine: string
  id: string
  is_system_default: boolean
  platform: string
  version: string
}

export interface SSEChatStreamArtifactCreatedData {
  file_id: string
  file_size: number
  filename: string
  mime_type?: string
}

export interface SSEChatStreamCompleteData {
  finish_reason: string
  usage?: Usage
}

export interface SSEChatStreamErrorData {
  code?: string
  message: string
}

export type SSEChatStreamEvent = {
  started: SSEChatStreamStartedData
  content: ChatStreamChunk
  complete: SSEChatStreamCompleteData
  error: SSEChatStreamErrorData
  mcpToolStart: SSEChatStreamMcpToolStartData
  mcpToolComplete: SSEChatStreamMcpToolCompleteData
  mcpApprovalRequired: SSEChatStreamMcpApprovalRequiredData
  mcpElicitationRequired: SSEChatStreamMcpElicitationRequiredData
  mcpToolProgress: SSEChatStreamMcpToolProgressData
  artifactCreated: SSEChatStreamArtifactCreatedData
  titleUpdated: SSEChatStreamTitleUpdatedData
}

export interface SSEChatStreamMcpApprovalRequiredData {
  input: any
  server: string
  server_id: string
  tool_name: string
  tool_use_id: string
}

export interface SSEChatStreamMcpElicitationRequiredData {
  elicitation_id: string
  message: string
  message_id?: string
  requested_schema: any
  server: string
}

export interface SSEChatStreamMcpToolCompleteData {
  is_error: boolean
  result?: string
  server: string
  tool_name: string
  tool_use_id: string
}

export interface SSEChatStreamMcpToolProgressData {
  message?: string
  message_id?: string
  progress: number
  progress_token?: any
  server: string
  total?: number
}

export interface SSEChatStreamMcpToolStartData {
  input: any
  server: string
  tool_name: string
  tool_use_id: string
}

export interface SSEChatStreamStartedData {
  branch_id: string
  conversation_id: string
  user_message_id?: string
}

export interface SSEChatStreamTitleUpdatedData {
  title: string
}

export interface SSEDownloadProgressConnectedData {
  message?: string
}

export type SSEDownloadProgressEvent = {
  connected: SSEDownloadProgressConnectedData
  update: DownloadProgressUpdate[]
  complete: string
  error: string
}

export interface SSEHardwareUsageConnectedData {
  message: string
}

export type SSEHardwareUsageEvent = {
  connected: SSEHardwareUsageConnectedData
  update: HardwareUsageUpdate
}

export interface SSEPrefetchCompleteData {
  bytes_downloaded: number
  cosign_verified: boolean
  duration_ms: number
}

export interface SSEPrefetchConnectedData {
  expected_size_mb: number
  flavor: string
  status: PrefetchStatus
  task_id: string
}

export type SSEPrefetchEvent = {
  connected: SSEPrefetchConnectedData
  progress: SSEPrefetchProgressData
  complete: SSEPrefetchCompleteData
  failed: SSEPrefetchFailedData
}

export interface SSEPrefetchFailedData {
  error: string
}

export interface SSEPrefetchProgressData {
  message: string
  phase: FetchPhase
}

export interface SaveUserApiKeyRequest {
  api_key: string
  provider_id: string
}

export interface SendMessageRequest {
  assistant_id?: string
  branch_id: string
  content: string
  create_branch_from_message_id?: string
  enable_mcp?: boolean
  file_ids?: string[]
  fork_level?: string
  mcp_config?: McpConfig
  model_id: string
  tool_approvals?: ToolApprovalDecision[]
}

export interface ServerGroupsRequest {
  group_ids: string[]
}

export interface SetMcpServerOAuthConfigRequest {
  client_id: string
  client_secret: string
  resource?: string
  scopes?: string
}

export interface SetupAdminRequest {
  display_name?: string
  email: string
  password: string
  username: string
}

export interface SetupStatusResponse {
  needs_setup: boolean
}

export type StartInstanceRequest = any

export interface StartPrefetchBody {
  flavor: string
}

export interface StartPrefetchResponse {
  events_url: string
  expected_size_mb: number
  flavor: string
  status: PrefetchStatus
  task_id: string
}

export interface StreamError {
  code?: string
  message: string
}

export interface SyncCacheResponse {
  message: string
  synced_count: number
}

export interface TestRepositoryConnectionRequest {
  auth_config?: RepositoryAuthConfig
  auth_type: string
  name: string
  url: string
}

export interface TestRepositoryConnectionResponse {
  message: string
  success: boolean
}

export interface TextPageQuery {
  page?: number
}

export interface ThinkingMetadata {
  token_count?: number
}

export interface TokenPair {
  access_token: string
  expires_in: number
  refresh_token: string
  token_type: string
}

export interface Tool {
  description?: string
  input_schema: any
  name: string
}

export interface ToolApprovalDecision {
  decision: string
  note?: string
  tool_use_id: string
}

export type ToolContent = any

export interface ToolIdentifier {
  server_id: string
  tool_name: string
}

export interface ToolUseApproval {
  approval_note?: string
  approved_at?: string
  approved_by?: string
  branch_id: string
  conversation_id: string
  created_at: string
  id: string
  input: any
  message_id: string
  server_id?: string
  server_name: string
  status: string
  tool_name: string
  tool_use_id: string
  updated_at: string
  user_id: string
}

export type TransportType = 'stdio' | 'http' | 'sse'

export interface UpdateAssistantRequest {
  description?: string
  enabled?: boolean
  instructions?: string
  is_default?: boolean
  name?: string
  parameters?: ModelParameters
}

export interface UpdateCodeSandboxResourceLimits {
  address_space_bytes?: number
  cpu_max?: string
  cpu_secs_max?: number
  fsize_bytes?: number
  mac_vm_ram_mib?: number
  mac_vm_vcpus?: number
  memory_max_bytes?: number
  memory_swap_max_bytes?: number
  nofile_max?: number
  nproc_max?: number
  pids_max?: number
  timeout_secs?: number
  vm_idle_evict_secs?: number
  vm_max_concurrent_execs?: number
}

export interface UpdateConversationRequest {
  title?: string
}

export interface UpdateGroupProvidersRequest {
  provider_ids: string[]
}

export interface UpdateGroupRequest {
  description?: string
  is_active?: boolean
  name?: string
  permissions?: string[]
}

export interface UpdateGroupSystemServersRequest {
  server_ids: string[]
}

export interface UpdateLlmModelRequest {
  description?: string
  capabilities?: ModelCapabilities
  display_name?: string
  enabled?: boolean
  engine_settings?: ModelEngineSettings
  engine_type?: EngineType
  file_format?: FileFormat
  is_active?: boolean
  name?: string
  parameters?: ModelParameters
}

export interface UpdateLlmProviderRequest {
  api_key?: string
  base_url?: string
  enabled?: boolean
  name?: string
  proxy_settings?: ProxySettings
}

export interface UpdateLlmRepositoryRequest {
  auth_config?: RepositoryAuthConfig
  auth_type?: string
  enabled?: boolean
  name?: string
  url?: string
}

export interface UpdateMcpServerRequest {
  description?: string
  args?: string[]
  command?: string
  display_name?: string
  enabled?: boolean
  environment_variables?: any
  headers?: any
  max_concurrent_sessions?: number
  name?: string
  supports_sampling?: boolean
  timeout_seconds?: number
  url?: string
  usage_mode?: UsageMode
}

export interface UpdateUserRequest {
  display_name?: string
  is_active?: boolean
  username?: string
}

export interface UpsertMcpSettingsRequest {
  approval_mode: ApprovalMode
  auto_approved_tools?: AutoApprovedServer[]
  disabled_servers?: DisabledServer[]
  loop_settings?: LoopSettings
}

export interface UpsertUserMcpDefaultsRequest {
  approval_mode: ApprovalMode
  auto_approved_tools?: AutoApprovedServer[]
  disabled_servers?: DisabledServer[]
  loop_settings?: LoopSettings
}

export interface Usage {
  input_tokens?: number
  output_tokens?: number
}

export type UsageMode = 'auto' | 'always'

export interface User {
  avatar_url?: string
  completed_onboarding_ids: string[]
  completed_onboarding_step_ids: string[]
  created_at: string
  display_name?: string
  email: string
  email_verified: boolean
  id: string
  is_active: boolean
  is_admin: boolean
  last_login_at?: string
  permissions: string[]
  updated_at: string
  username: string
}

export interface UserActiveStatusResponse {
  is_active: boolean
  user_id: string
}

export interface UserApiKeyEntry {
  masked_key: string
  provider_id: string
}

export interface UserApiKeyListResponse {
  keys: UserApiKeyEntry[]
}

export interface UserListResponse {
  page: number
  per_page: number
  total: number
  total_pages: number
  users: User[]
}

export interface UserMcpDefaultsGetResponse {
  defaults?: UserMcpDefaultsResponse
}

export interface UserMcpDefaultsResponse {
  approval_mode: ApprovalMode
  auto_approved_tools: AutoApprovedServer[]
  created_at: string
  disabled_servers: DisabledServer[]
  id: string
  loop_settings: LoopSettings
  updated_at: string
  user_id: string
}

// =============================================================================
// PERMISSIONS
// =============================================================================

export enum Permissions {
  AssistantsCreate = 'assistants::create',
  AssistantsDelete = 'assistants::delete',
  AssistantsEdit = 'assistants::edit',
  AssistantsRead = 'assistants::read',
  AssistantsTemplateCreate = 'assistant_templates::create',
  AssistantsTemplateDelete = 'assistant_templates::delete',
  AssistantsTemplateEdit = 'assistant_templates::edit',
  AssistantsTemplateRead = 'assistant_templates::read',
  BranchesCreate = 'branches::create',
  BranchesSwitch = 'branches::switch',
  CodeSandboxEnvironmentsManage = 'code_sandbox::environments::manage',
  CodeSandboxEnvironmentsRead = 'code_sandbox::environments::read',
  CodeSandboxResourceLimitsManage = 'code_sandbox::resource_limits::manage',
  CodeSandboxResourceLimitsRead = 'code_sandbox::resource_limits::read',
  ConversationsCreate = 'conversations::create',
  ConversationsDelete = 'conversations::delete',
  ConversationsEdit = 'conversations::edit',
  ConversationsRead = 'conversations::read',
  FilesDelete = 'files::delete',
  FilesDownload = 'files::download',
  FilesGenerateToken = 'files::generate_token',
  FilesPreview = 'files::preview',
  FilesRead = 'files::read',
  FilesUpload = 'files::upload',
  GroupsAssignUsers = 'groups::assign_users',
  GroupsCreate = 'groups::create',
  GroupsDelete = 'groups::delete',
  GroupsEdit = 'groups::edit',
  GroupsRead = 'groups::read',
  HardwareMonitor = 'hardware::monitor',
  HardwareRead = 'hardware::read',
  HubAssistantsCreate = 'hub::assistants::create',
  HubAssistantsRead = 'hub::assistants::read',
  HubAssistantsRefresh = 'hub::assistants::refresh',
  HubAssistantsVersionRead = 'hub::assistants::read_version',
  HubMcpServersCreate = 'hub::mcp_servers::create',
  HubMCPServersRead = 'hub::mcp_servers::read',
  HubMCPServersRefresh = 'hub::mcp_servers::refresh',
  HubMCPServersVersionRead = 'hub::mcp_servers::read_version',
  HubModelsCreate = 'hub::models::download',
  HubModelsRead = 'hub::models::read',
  HubModelsRefresh = 'hub::models::refresh',
  HubModelsVersionRead = 'hub::models::read_version',
  LlmModelsCreate = 'llm_models::create',
  LlmModelsDelete = 'llm_models::delete',
  LlmModelsDownloadsCancel = 'llm_models::downloads_cancel',
  LlmModelsDownloadsDelete = 'llm_models::downloads_delete',
  LlmModelsDownloadsRead = 'llm_models::downloads_read',
  LlmModelsEdit = 'llm_models::edit',
  LlmModelsRead = 'llm_models::read',
  LlmProvidersAssignGroups = 'llm_providers::assign_groups',
  LlmProvidersCreate = 'llm_providers::create',
  LlmProvidersDelete = 'llm_providers::delete',
  LlmProvidersEdit = 'llm_providers::edit',
  LlmProvidersRead = 'llm_providers::read',
  LlmRepositoriesCreate = 'llm_repositories::create',
  LlmRepositoriesDelete = 'llm_repositories::delete',
  LlmRepositoriesEdit = 'llm_repositories::edit',
  LlmRepositoriesRead = 'llm_repositories::read',
  LocalRuntimeLogs = 'llm_local_runtime::logs',
  LocalRuntimeManage = 'llm_local_runtime::manage',
  LocalRuntimeRead = 'llm_local_runtime::read',
  McpServersAdminCreate = 'mcp_servers_admin::create',
  McpServersAdminDelete = 'mcp_servers_admin::delete',
  McpServersAdminEdit = 'mcp_servers_admin::edit',
  McpServersAdminRead = 'mcp_servers_admin::read',
  McpServersCreate = 'mcp_servers::create',
  McpServersDelete = 'mcp_servers::delete',
  McpServersEdit = 'mcp_servers::edit',
  McpServersRead = 'mcp_servers::read',
  MessagesCreate = 'messages::create',
  MessagesDelete = 'messages::delete',
  MessagesRead = 'messages::read',
  ProfileEdit = 'profile::edit',
  ProfileRead = 'profile::read',
  RuntimeVersionCreate = 'llm_local_runtime::create',
  RuntimeVersionDelete = 'llm_local_runtime::delete',
  RuntimeVersionRead = 'llm_local_runtime::versions_read',
  RuntimeVersionUpdate = 'llm_local_runtime::update',
  UserLlmProvidersRead = 'user_llm_providers::read',
  UsersCreate = 'users::create',
  UsersDelete = 'users::delete',
  UsersEdit = 'users::edit',
  UsersRead = 'users::read',
  UsersResetPassword = 'users::reset_password',
  UsersToggleStatus = 'users::toggle_status'
}

export const PermissionDescriptions: Record<string, string> = {
  AssistantsCreate: 'Create user assistants',
  AssistantsDelete: 'Delete user assistants',
  AssistantsEdit: 'Edit user assistants',
  AssistantsRead: 'Read user assistants',
  AssistantsTemplateCreate: 'Create system-wide template assistants',
  AssistantsTemplateDelete: 'Delete system-wide template assistants',
  AssistantsTemplateEdit: 'Edit system-wide template assistants',
  AssistantsTemplateRead: 'Read system-wide template assistants',
  BranchesCreate: 'Create message branches for edit/regenerate',
  BranchesSwitch: 'Switch between conversation branches',
  CodeSandboxEnvironmentsManage: 'Trigger pre-fetch + cache management of sandbox rootfs environments.',
  CodeSandboxEnvironmentsRead: 'List available sandbox environments and watch prefetch progress.',
  CodeSandboxResourceLimitsManage: 'Update the sandbox memory/CPU/PID caps + per-exec timeout + idle-evict policy.',
  CodeSandboxResourceLimitsRead: 'Read the sandbox resource limits configuration.',
  ConversationsCreate: 'Create new chat conversations',
  ConversationsDelete: 'Delete chat conversations',
  ConversationsEdit: 'Edit conversation titles and metadata',
  ConversationsRead: 'View chat conversations',
  FilesDelete: 'Delete files',
  FilesDownload: 'Download file content',
  FilesGenerateToken: 'Generate download tokens',
  FilesPreview: 'View file thumbnails and previews',
  FilesRead: 'View file metadata and list files',
  FilesUpload: 'Upload new files',
  GroupsAssignUsers: 'Assign users to groups and remove users from groups',
  GroupsCreate: 'Create new groups',
  GroupsDelete: 'Delete non-system groups',
  GroupsEdit: 'Edit existing group information and permissions',
  GroupsRead: 'View groups and group information',
  HardwareMonitor: 'Monitor real-time hardware usage',
  HardwareRead: 'View hardware information',
  HubAssistantsCreate: 'Create assistants from hub',
  HubAssistantsRead: 'View hub assistants',
  HubAssistantsRefresh: 'Refresh hub assistants from GitHub',
  HubAssistantsVersionRead: 'View hub assistants version information',
  HubMcpServersCreate: 'Create MCP servers from hub',
  HubMCPServersRead: 'View hub MCP servers',
  HubMCPServersRefresh: 'Refresh hub MCP servers from GitHub',
  HubMCPServersVersionRead: 'View hub MCP servers version information',
  HubModelsCreate: 'Download models from hub',
  HubModelsRead: 'View hub models',
  HubModelsRefresh: 'Refresh hub models from GitHub',
  HubModelsVersionRead: 'View hub models version information',
  LlmModelsCreate: 'Create new LLM models',
  LlmModelsDelete: 'Delete LLM models',
  LlmModelsDownloadsCancel: 'Cancel active downloads',
  LlmModelsDownloadsDelete: 'Delete download instances',
  LlmModelsDownloadsRead: 'Read download instances',
  LlmModelsEdit: 'Edit existing LLM models',
  LlmModelsRead: 'Read LLM models',
  LlmProvidersAssignGroups: 'Assign LLM providers to user groups',
  LlmProvidersCreate: 'Create new LLM provider configurations',
  LlmProvidersDelete: 'Delete non-built-in LLM providers',
  LlmProvidersEdit: 'Edit existing LLM provider information and settings',
  LlmProvidersRead: 'View LLM providers and list available providers',
  LlmRepositoriesCreate: 'Create new LLM repositories',
  LlmRepositoriesDelete: 'Delete non-built-in LLM repositories',
  LlmRepositoriesEdit: 'Edit existing LLM repository information and authentication',
  LlmRepositoriesRead: 'View LLM repositories and list repositories',
  LocalRuntimeLogs: 'View runtime instance logs',
  LocalRuntimeManage: 'Start, stop, and restart local LLM runtime instances',
  LocalRuntimeRead: 'View local LLM runtime instances and their status',
  McpServersAdminCreate: 'Create system MCP servers',
  McpServersAdminDelete: 'Delete system MCP servers',
  McpServersAdminEdit: 'Edit system MCP servers and manage group assignments',
  McpServersAdminRead: 'View system MCP servers',
  McpServersCreate: 'Create MCP servers',
  McpServersDelete: 'Delete MCP servers',
  McpServersEdit: 'Edit MCP servers',
  McpServersRead: 'View MCP servers',
  MessagesCreate: 'Send messages in conversations',
  MessagesDelete: 'Delete messages from conversations',
  MessagesRead: 'Read messages in conversations',
  ProfileEdit: 'Edit own profile information',
  ProfileRead: 'View own profile information',
  RuntimeVersionCreate: 'Download and register new runtime versions',
  RuntimeVersionDelete: 'Delete runtime versions',
  RuntimeVersionRead: 'View runtime versions and check for updates',
  RuntimeVersionUpdate: 'Update runtime version settings and defaults',
  UserLlmProvidersRead: 'View available LLM providers and models',
  UsersCreate: 'Create new user accounts',
  UsersDelete: 'Delete user accounts',
  UsersEdit: 'Edit existing user information',
  UsersRead: 'View user information and list users',
  UsersResetPassword: 'Reset user passwords',
  UsersToggleStatus: 'Enable or disable user accounts'
}

// =============================================================================
// API ENDPOINTS
// =============================================================================

// API endpoint definitions
export const ApiEndpoints = {
  'App.getSetupStatus': 'GET /api/app/setup/status',
  'App.setupAdmin': 'POST /api/app/setup/admin',
  'Assistant.create': 'POST /api/assistants',
  'Assistant.delete': 'DELETE /api/assistants/{id}',
  'Assistant.get': 'GET /api/assistants/{id}',
  'Assistant.getDefault': 'GET /api/assistants/default',
  'Assistant.list': 'GET /api/assistants',
  'Assistant.update': 'PUT /api/assistants/{id}',
  'AssistantTemplate.create': 'POST /api/assistant-templates',
  'AssistantTemplate.delete': 'DELETE /api/assistant-templates/{id}',
  'AssistantTemplate.get': 'GET /api/assistant-templates/{id}',
  'AssistantTemplate.getDefault': 'GET /api/assistant-templates/default',
  'AssistantTemplate.list': 'GET /api/assistant-templates',
  'AssistantTemplate.update': 'PUT /api/assistant-templates/{id}',
  'Auth.login': 'POST /api/auth/login',
  'Auth.logout': 'POST /api/auth/logout',
  'Auth.me': 'GET /api/auth/me',
  'Auth.refresh': 'POST /api/auth/refresh',
  'Auth.register': 'POST /api/auth/register',
  'Branch.activate': 'POST /api/conversations/{id}/branches/{branch_id}/activate',
  'Branch.create': 'POST /api/conversations/{id}/branches',
  'Branch.getPendingApprovals': 'GET /api/branches/{branch_id}/pending-approvals',
  'Branch.list': 'GET /api/conversations/{id}/branches',
  'Chat.getUserLlmProviders': 'GET /api/chat/llm-providers',
  'CodeSandbox.evictEnvironment': 'DELETE /api/code-sandbox/environments/{flavor}',
  'CodeSandbox.getResourceLimits': 'GET /api/code-sandbox/resource-limits',
  'CodeSandbox.listEnvironments': 'GET /api/code-sandbox/environments',
  'CodeSandbox.listPrefetchTasks': 'GET /api/code-sandbox/prefetch',
  'CodeSandbox.startPrefetch': 'POST /api/code-sandbox/prefetch',
  'CodeSandbox.subscribePrefetchEvents': 'GET /api/code-sandbox/prefetch/{flavor}/events',
  'CodeSandbox.updateResourceLimits': 'PUT /api/code-sandbox/resource-limits',
  'Conversation.create': 'POST /api/conversations',
  'Conversation.delete': 'DELETE /api/conversations/{id}',
  'Conversation.get': 'GET /api/conversations/{id}',
  'Conversation.getMcpSettings': 'GET /api/conversations/{id}/mcp-settings',
  'Conversation.list': 'GET /api/conversations',
  'Conversation.update': 'PUT /api/conversations/{id}',
  'Conversation.updateMcpSettings': 'PUT /api/conversations/{id}/mcp-settings',
  'File.delete': 'DELETE /api/files/{file_id}',
  'File.download': 'GET /api/files/{file_id}/download',
  'File.downloadWithToken': 'GET /api/files/{file_id}/download-with-token',
  'File.generateDownloadToken': 'POST /api/files/{file_id}/download-token',
  'File.get': 'GET /api/files/{file_id}',
  'File.getPreview': 'GET /api/files/{file_id}/preview',
  'File.getTextContent': 'GET /api/files/{file_id}/text',
  'File.getThumbnail': 'GET /api/files/{file_id}/thumbnail',
  'File.list': 'GET /api/files',
  'File.upload': 'POST /api/files/upload',
  'Group.getProviders': 'GET /api/groups/{group_id}/providers',
  'Group.getSystemServers': 'GET /api/groups/{group_id}/system-servers',
  'Group.updateProviders': 'PUT /api/groups/{group_id}/providers',
  'Group.updateSystemServers': 'PUT /api/groups/{group_id}/system-servers',
  'Hardware.info': 'GET /api/hardware',
  'Hardware.stream': 'GET /api/hardware/usage-stream',
  'Health.check': 'GET /api/health',
  'Hub.createAssistantFromHub': 'POST /api/hub/assistants/create',
  'Hub.createMcpServerFromHub': 'POST /api/hub/mcp-servers/create',
  'Hub.createModelFromHub': 'POST /api/hub/models/download',
  'Hub.getAssistants': 'GET /api/hub/assistants',
  'Hub.getAssistantsVersion': 'GET /api/hub/assistants/version',
  'Hub.getLocalProviders': 'GET /api/hub/models/local-providers',
  'Hub.getMCPServers': 'GET /api/hub/mcp-servers',
  'Hub.getMCPServersVersion': 'GET /api/hub/mcp-servers/version',
  'Hub.getModels': 'GET /api/hub/models',
  'Hub.getModelsVersion': 'GET /api/hub/models/version',
  'Hub.refreshAssistants': 'POST /api/hub/assistants/refresh',
  'Hub.refreshMCPServers': 'POST /api/hub/mcp-servers/refresh',
  'Hub.refreshModels': 'POST /api/hub/models/refresh',
  'LlmModel.cancelDownload': 'POST /api/llm-models/downloads/{download_id}/cancel',
  'LlmModel.create': 'POST /api/llm-models',
  'LlmModel.delete': 'DELETE /api/llm-models/{model_id}',
  'LlmModel.deleteDownload': 'DELETE /api/llm-models/downloads/{download_id}',
  'LlmModel.disable': 'POST /api/llm-models/{model_id}/disable',
  'LlmModel.download': 'POST /api/llm-models/download',
  'LlmModel.enable': 'POST /api/llm-models/{model_id}/enable',
  'LlmModel.get': 'GET /api/llm-models/{model_id}',
  'LlmModel.getDownload': 'GET /api/llm-models/downloads/{download_id}',
  'LlmModel.list': 'GET /api/llm-models',
  'LlmModel.listDownloads': 'GET /api/llm-models/downloads',
  'LlmModel.subscribeDownloadProgress': 'GET /api/llm-models/downloads/subscribe',
  'LlmModel.update': 'POST /api/llm-models/{model_id}',
  'LlmModel.upload': 'POST /api/llm-models/upload',
  'LlmProvider.assignGroup': 'POST /api/llm-providers/{provider_id}/groups',
  'LlmProvider.create': 'POST /api/llm-providers',
  'LlmProvider.delete': 'DELETE /api/llm-providers/{provider_id}',
  'LlmProvider.deleteUserApiKey': 'DELETE /api/user-llm-providers/api-keys/{provider_id}',
  'LlmProvider.get': 'GET /api/llm-providers/{provider_id}',
  'LlmProvider.getGroups': 'GET /api/llm-providers/{provider_id}/groups',
  'LlmProvider.getUserLlmProviders': 'GET /api/user-llm-providers',
  'LlmProvider.list': 'GET /api/llm-providers',
  'LlmProvider.listUserApiKeys': 'GET /api/user-llm-providers/api-keys',
  'LlmProvider.removeGroup': 'DELETE /api/llm-providers/{provider_id}/groups/{group_id}',
  'LlmProvider.saveUserApiKey': 'POST /api/user-llm-providers/api-keys',
  'LlmProvider.update': 'POST /api/llm-providers/{provider_id}',
  'LlmRepository.create': 'POST /api/llm-repositories',
  'LlmRepository.delete': 'DELETE /api/llm-repositories/{repository_id}',
  'LlmRepository.get': 'GET /api/llm-repositories/{repository_id}',
  'LlmRepository.list': 'GET /api/llm-repositories',
  'LlmRepository.test': 'POST /api/llm-repositories/test',
  'LlmRepository.update': 'POST /api/llm-repositories/{repository_id}',
  'LocalRuntime.getInstance': 'GET /api/local-runtime/models/{model_id}/instance',
  'LocalRuntime.getLogs': 'GET /api/local-runtime/models/{model_id}/logs',
  'LocalRuntime.getProviderInstances': 'GET /api/local-runtime/providers/{provider_id}/instances',
  'LocalRuntime.getStatus': 'GET /api/local-runtime/models/{model_id}/status',
  'LocalRuntime.healthCheck': 'GET /api/local-runtime/models/{model_id}/health',
  'LocalRuntime.restartModel': 'POST /api/local-runtime/models/{model_id}/restart',
  'LocalRuntime.startModel': 'POST /api/local-runtime/models/{model_id}/start',
  'LocalRuntime.stopModel': 'POST /api/local-runtime/models/{model_id}/stop',
  'Mcp.getDefaults': 'GET /api/mcp/defaults',
  'Mcp.respondToElicitation': 'POST /api/mcp/elicitation/{elicitation_id}/respond',
  'Mcp.updateDefaults': 'PUT /api/mcp/defaults',
  'McpServer.create': 'POST /api/mcp/servers',
  'McpServer.delete': 'DELETE /api/mcp/servers/{id}',
  'McpServer.deleteOAuthConfig': 'DELETE /api/mcp/servers/{id}/oauth',
  'McpServer.get': 'GET /api/mcp/servers/{id}',
  'McpServer.getOAuthConfig': 'GET /api/mcp/servers/{id}/oauth',
  'McpServer.listAccessible': 'GET /api/mcp/servers',
  'McpServer.setOAuthConfig': 'PUT /api/mcp/servers/{id}/oauth',
  'McpServer.update': 'PUT /api/mcp/servers/{id}',
  'McpServerRuntime.callTool': 'POST /api/mcp/servers/{id}/tools/{name}/call',
  'McpServerRuntime.disconnect': 'DELETE /api/mcp/servers/{id}/disconnect',
  'McpServerRuntime.getPrompt': 'POST /api/mcp/servers/{id}/prompts/get',
  'McpServerRuntime.listPrompts': 'GET /api/mcp/servers/{id}/prompts',
  'McpServerRuntime.listResources': 'GET /api/mcp/servers/{id}/resources',
  'McpServerRuntime.listTools': 'GET /api/mcp/servers/{id}/tools',
  'McpServerRuntime.ping': 'POST /api/mcp/servers/{id}/ping',
  'McpServerRuntime.readResource': 'POST /api/mcp/servers/{id}/resources/read',
  'McpServerSystem.assignServerToGroups': 'POST /api/mcp/system-servers/{id}/groups',
  'McpServerSystem.create': 'POST /api/mcp/system-servers',
  'McpServerSystem.delete': 'DELETE /api/mcp/system-servers/{id}',
  'McpServerSystem.get': 'GET /api/mcp/system-servers/{id}',
  'McpServerSystem.getServerGroups': 'GET /api/mcp/system-servers/{id}/groups',
  'McpServerSystem.list': 'GET /api/mcp/system-servers',
  'McpServerSystem.removeServerFromGroup': 'DELETE /api/mcp/system-servers/{id}/groups/{group_id}',
  'McpServerSystem.update': 'PUT /api/mcp/system-servers/{id}',
  'Message.delete': 'DELETE /api/messages/{id}',
  'Message.edit': 'PUT /api/conversations/{conversation_id}/messages/{message_id}',
  'Message.get': 'GET /api/messages/{id}',
  'Message.getHistory': 'GET /api/conversations/{id}/messages',
  'Message.sendStream': 'POST /api/conversations/{id}/messages/stream',
  'Onboarding.complete': 'POST /api/onboarding/{guide_id}/complete',
  'Onboarding.completeStep': 'POST /api/onboarding/{guide_id}/steps/{step_id}/complete',
  'RuntimeVersion.checkUpdates': 'GET /api/local-runtime/versions/{engine}/check-updates',
  'RuntimeVersion.delete': 'DELETE /api/local-runtime/versions/{version_id}',
  'RuntimeVersion.download': 'POST /api/local-runtime/versions/download',
  'RuntimeVersion.get': 'GET /api/local-runtime/versions/{version_id}',
  'RuntimeVersion.list': 'GET /api/local-runtime/versions',
  'RuntimeVersion.setDefault': 'POST /api/local-runtime/versions/{version_id}/set-default',
  'RuntimeVersion.syncCache': 'POST /api/local-runtime/versions/sync-cache',
  'User.create': 'POST /api/users',
  'User.delete': 'DELETE /api/users/{user_id}',
  'User.get': 'GET /api/users/{user_id}',
  'User.list': 'GET /api/users',
  'User.resetPassword': 'POST /api/users/reset-password',
  'User.toggleActive': 'POST /api/users/{user_id}/toggle-active',
  'User.update': 'POST /api/users/{user_id}',
  'UserGroup.assignUser': 'POST /api/groups/assign',
  'UserGroup.create': 'POST /api/groups',
  'UserGroup.delete': 'DELETE /api/groups/{group_id}',
  'UserGroup.get': 'GET /api/groups/{group_id}',
  'UserGroup.getMembers': 'GET /api/groups/{group_id}/members',
  'UserGroup.list': 'GET /api/groups',
  'UserGroup.removeUser': 'DELETE /api/groups/{user_id}/{group_id}/remove',
  'UserGroup.update': 'POST /api/groups/{group_id}'
} as const

// API endpoint parameters
export type ApiEndpointParameters = {
  'App.getSetupStatus': void
  'App.setupAdmin': SetupAdminRequest
  'Assistant.create': CreateAssistantRequest
  'Assistant.delete': { id: string }
  'Assistant.get': { id: string }
  'Assistant.getDefault': void
  'Assistant.list': { limit: number; page: number }
  'Assistant.update': { id: string } & UpdateAssistantRequest
  'AssistantTemplate.create': CreateAssistantRequest
  'AssistantTemplate.delete': { id: string }
  'AssistantTemplate.get': { id: string }
  'AssistantTemplate.getDefault': void
  'AssistantTemplate.list': { limit: number; page: number }
  'AssistantTemplate.update': { id: string } & UpdateAssistantRequest
  'Auth.login': LoginRequest
  'Auth.logout': void
  'Auth.me': void
  'Auth.refresh': RefreshTokenRequest
  'Auth.register': RegisterRequest
  'Branch.activate': { id: string; branch_id: string }
  'Branch.create': { id: string } & CreateBranchRequest
  'Branch.getPendingApprovals': { branch_id: string }
  'Branch.list': { id: string }
  'Chat.getUserLlmProviders': void
  'CodeSandbox.evictEnvironment': { flavor: string }
  'CodeSandbox.getResourceLimits': void
  'CodeSandbox.listEnvironments': void
  'CodeSandbox.listPrefetchTasks': void
  'CodeSandbox.startPrefetch': StartPrefetchBody
  'CodeSandbox.subscribePrefetchEvents': { flavor: string }
  'CodeSandbox.updateResourceLimits': UpdateCodeSandboxResourceLimits
  'Conversation.create': CreateConversationRequest
  'Conversation.delete': { id: string }
  'Conversation.get': { id: string }
  'Conversation.getMcpSettings': { id: string }
  'Conversation.list': { limit?: number; page?: number }
  'Conversation.update': { id: string } & UpdateConversationRequest
  'Conversation.updateMcpSettings': { id: string } & UpsertMcpSettingsRequest
  'File.delete': { file_id: string }
  'File.download': { file_id: string }
  'File.downloadWithToken': { file_id: string; token: string }
  'File.generateDownloadToken': { file_id: string }
  'File.get': { file_id: string }
  'File.getPreview': { file_id: string; page?: number }
  'File.getTextContent': { file_id: string; page?: number }
  'File.getThumbnail': { file_id: string }
  'File.list': PaginationQuery
  'File.upload': FormData
  'Group.getProviders': { group_id: string }
  'Group.getSystemServers': { group_id: string }
  'Group.updateProviders': { group_id: string } & UpdateGroupProvidersRequest
  'Group.updateSystemServers': { group_id: string } & UpdateGroupSystemServersRequest
  'Hardware.info': void
  'Hardware.stream': void
  'Health.check': void
  'Hub.createAssistantFromHub': CreateAssistantFromHubRequest
  'Hub.createMcpServerFromHub': CreateMcpServerFromHubRequest
  'Hub.createModelFromHub': CreateModelFromHubRequest
  'Hub.getAssistants': { lang?: string }
  'Hub.getAssistantsVersion': void
  'Hub.getLocalProviders': void
  'Hub.getMCPServers': { lang?: string }
  'Hub.getMCPServersVersion': void
  'Hub.getModels': { lang?: string }
  'Hub.getModelsVersion': void
  'Hub.refreshAssistants': void
  'Hub.refreshMCPServers': void
  'Hub.refreshModels': void
  'LlmModel.cancelDownload': { download_id: string }
  'LlmModel.create': CreateLlmModelRequest
  'LlmModel.delete': { model_id: string }
  'LlmModel.deleteDownload': { download_id: string }
  'LlmModel.disable': { model_id: string }
  'LlmModel.download': DownloadFromRepositoryRequest
  'LlmModel.enable': { model_id: string }
  'LlmModel.get': { model_id: string }
  'LlmModel.getDownload': { download_id: string }
  'LlmModel.list': { page?: number; perPage?: number; providerId?: string }
  'LlmModel.listDownloads': { page?: number; per_page?: number; status?: string }
  'LlmModel.subscribeDownloadProgress': void
  'LlmModel.update': { model_id: string } & UpdateLlmModelRequest
  'LlmModel.upload': FormData
  'LlmProvider.assignGroup': { provider_id: string } & AssignProviderToGroupRequest
  'LlmProvider.create': CreateLlmProviderRequest
  'LlmProvider.delete': { provider_id: string }
  'LlmProvider.deleteUserApiKey': { provider_id: string }
  'LlmProvider.get': { provider_id: string }
  'LlmProvider.getGroups': { provider_id: string }
  'LlmProvider.getUserLlmProviders': void
  'LlmProvider.list': PaginationQuery
  'LlmProvider.listUserApiKeys': void
  'LlmProvider.removeGroup': { provider_id: string; group_id: string }
  'LlmProvider.saveUserApiKey': SaveUserApiKeyRequest
  'LlmProvider.update': { provider_id: string } & UpdateLlmProviderRequest
  'LlmRepository.create': CreateLlmRepositoryRequest
  'LlmRepository.delete': { repository_id: string }
  'LlmRepository.get': { repository_id: string }
  'LlmRepository.list': PaginationQuery
  'LlmRepository.test': TestRepositoryConnectionRequest
  'LlmRepository.update': { repository_id: string } & UpdateLlmRepositoryRequest
  'LocalRuntime.getInstance': { model_id: string }
  'LocalRuntime.getLogs': { model_id: string }
  'LocalRuntime.getProviderInstances': { provider_id: string }
  'LocalRuntime.getStatus': { model_id: string }
  'LocalRuntime.healthCheck': { model_id: string }
  'LocalRuntime.restartModel': { model_id: string }
  'LocalRuntime.startModel': { model_id: string } & StartInstanceRequest
  'LocalRuntime.stopModel': { model_id: string }
  'Mcp.getDefaults': void
  'Mcp.respondToElicitation': { elicitation_id: string } & RespondToElicitationRequest
  'Mcp.updateDefaults': UpsertUserMcpDefaultsRequest
  'McpServer.create': CreateMcpServerRequest
  'McpServer.delete': { id: string }
  'McpServer.deleteOAuthConfig': { id: string }
  'McpServer.get': { id: string }
  'McpServer.getOAuthConfig': { id: string }
  'McpServer.listAccessible': PaginationQuery
  'McpServer.setOAuthConfig': { id: string } & SetMcpServerOAuthConfigRequest
  'McpServer.update': { id: string } & UpdateMcpServerRequest
  'McpServerRuntime.callTool': { id: string; name: string } & CallToolRequest
  'McpServerRuntime.disconnect': { id: string }
  'McpServerRuntime.getPrompt': { id: string } & GetPromptRequest
  'McpServerRuntime.listPrompts': { id: string }
  'McpServerRuntime.listResources': { id: string }
  'McpServerRuntime.listTools': { id: string }
  'McpServerRuntime.ping': { id: string }
  'McpServerRuntime.readResource': { id: string } & ReadResourceRequest
  'McpServerSystem.assignServerToGroups': { id: string } & ServerGroupsRequest
  'McpServerSystem.create': CreateMcpServerRequest
  'McpServerSystem.delete': { id: string }
  'McpServerSystem.get': { id: string }
  'McpServerSystem.getServerGroups': { id: string }
  'McpServerSystem.list': PaginationQuery
  'McpServerSystem.removeServerFromGroup': { id: string; group_id: string }
  'McpServerSystem.update': { id: string } & UpdateMcpServerRequest
  'Message.delete': { id: string }
  'Message.edit': { conversation_id: string; message_id: string } & EditMessageRequest
  'Message.get': { id: string }
  'Message.getHistory': { id: string }
  'Message.sendStream': { id: string } & SendMessageRequest
  'Onboarding.complete': { guide_id: string }
  'Onboarding.completeStep': { guide_id: string; step_id: string }
  'RuntimeVersion.checkUpdates': { engine: string }
  'RuntimeVersion.delete': { version_id: string; remove_binary?: boolean }
  'RuntimeVersion.download': DownloadVersionRequest
  'RuntimeVersion.get': { version_id: string }
  'RuntimeVersion.list': { engine?: string }
  'RuntimeVersion.setDefault': { version_id: string }
  'RuntimeVersion.syncCache': void
  'User.create': CreateUserRequest
  'User.delete': { user_id: string }
  'User.get': { user_id: string }
  'User.list': PaginationQuery
  'User.resetPassword': ResetPasswordRequest
  'User.toggleActive': { user_id: string }
  'User.update': { user_id: string } & UpdateUserRequest
  'UserGroup.assignUser': AssignUserToGroupRequest
  'UserGroup.create': CreateGroupRequest
  'UserGroup.delete': { group_id: string }
  'UserGroup.get': { group_id: string }
  'UserGroup.getMembers': { group_id: string } & PaginationQuery
  'UserGroup.list': PaginationQuery
  'UserGroup.removeUser': { user_id: string; group_id: string }
  'UserGroup.update': { group_id: string } & UpdateGroupRequest
}

// API endpoint responses
export type ApiEndpointResponses = {
  'App.getSetupStatus': SetupStatusResponse
  'App.setupAdmin': AuthResponse
  'Assistant.create': Assistant
  'Assistant.delete': void
  'Assistant.get': Assistant
  'Assistant.getDefault': Assistant
  'Assistant.list': AssistantListResponse
  'Assistant.update': Assistant
  'AssistantTemplate.create': Assistant
  'AssistantTemplate.delete': void
  'AssistantTemplate.get': Assistant
  'AssistantTemplate.getDefault': Assistant
  'AssistantTemplate.list': AssistantListResponse
  'AssistantTemplate.update': Assistant
  'Auth.login': AuthResponse
  'Auth.logout': void
  'Auth.me': MeResponse
  'Auth.refresh': TokenPair
  'Auth.register': AuthResponse
  'Branch.activate': void
  'Branch.create': Branch
  'Branch.getPendingApprovals': PendingApprovalsResponse
  'Branch.list': Branch[]
  'Chat.getUserLlmProviders': GetUserProvidersResponse2
  'CodeSandbox.evictEnvironment': EnvironmentsResponse
  'CodeSandbox.getResourceLimits': CodeSandboxResourceLimits
  'CodeSandbox.listEnvironments': EnvironmentsResponse
  'CodeSandbox.listPrefetchTasks': ListPrefetchTasksResponse
  'CodeSandbox.startPrefetch': StartPrefetchResponse
  'CodeSandbox.subscribePrefetchEvents': SSEPrefetchEvent
  'CodeSandbox.updateResourceLimits': CodeSandboxResourceLimits
  'Conversation.create': Conversation
  'Conversation.delete': void
  'Conversation.get': Conversation
  'Conversation.getMcpSettings': McpSettingsResponse
  'Conversation.list': ConversationResponse[]
  'Conversation.update': Conversation
  'Conversation.updateMcpSettings': ConversationMcpSettingsResponse
  'File.delete': void
  'File.download': Blob
  'File.downloadWithToken': Blob
  'File.generateDownloadToken': DownloadTokenResponse
  'File.get': File
  'File.getPreview': Blob
  'File.getTextContent': Blob
  'File.getThumbnail': Blob
  'File.list': FileListResponse
  'File.upload': File
  'Group.getProviders': GroupProvidersResponse
  'Group.getSystemServers': GroupSystemServersResponse
  'Group.updateProviders': GroupProvidersResponse
  'Group.updateSystemServers': GroupSystemServersResponse
  'Hardware.info': HardwareInfoResponse
  'Hardware.stream': SSEHardwareUsageEvent
  'Health.check': HealthResponse
  'Hub.createAssistantFromHub': AssistantFromHubResponse
  'Hub.createMcpServerFromHub': McpServerFromHubResponse
  'Hub.createModelFromHub': ModelFromHubResponse
  'Hub.getAssistants': HubAssistant[]
  'Hub.getAssistantsVersion': HubVersionResponse
  'Hub.getLocalProviders': HubLocalProvidersResponse
  'Hub.getMCPServers': HubMCPServer[]
  'Hub.getMCPServersVersion': HubVersionResponse
  'Hub.getModels': HubModel[]
  'Hub.getModelsVersion': HubVersionResponse
  'Hub.refreshAssistants': HubRefreshResponse
  'Hub.refreshMCPServers': HubRefreshResponse
  'Hub.refreshModels': HubRefreshResponse
  'LlmModel.cancelDownload': void
  'LlmModel.create': LlmModel
  'LlmModel.delete': void
  'LlmModel.deleteDownload': void
  'LlmModel.disable': LlmModel
  'LlmModel.download': DownloadInstance
  'LlmModel.enable': LlmModel
  'LlmModel.get': LlmModel
  'LlmModel.getDownload': DownloadInstance
  'LlmModel.list': LlmModelListResponse
  'LlmModel.listDownloads': DownloadInstanceListResponse
  'LlmModel.subscribeDownloadProgress': SSEDownloadProgressEvent
  'LlmModel.update': LlmModel
  'LlmModel.upload': LlmModel
  'LlmProvider.assignGroup': void
  'LlmProvider.create': LlmProvider
  'LlmProvider.delete': void
  'LlmProvider.deleteUserApiKey': void
  'LlmProvider.get': LlmProvider
  'LlmProvider.getGroups': Group[]
  'LlmProvider.getUserLlmProviders': GetUserProvidersResponse
  'LlmProvider.list': LlmProviderListResponse
  'LlmProvider.listUserApiKeys': UserApiKeyListResponse
  'LlmProvider.removeGroup': void
  'LlmProvider.saveUserApiKey': void
  'LlmProvider.update': LlmProvider
  'LlmRepository.create': LlmRepository
  'LlmRepository.delete': void
  'LlmRepository.get': LlmRepository
  'LlmRepository.list': LlmRepositoryListResponse
  'LlmRepository.test': TestRepositoryConnectionResponse
  'LlmRepository.update': LlmRepository
  'LocalRuntime.getInstance': InstanceResponse
  'LocalRuntime.getLogs': LogsResponse
  'LocalRuntime.getProviderInstances': ProviderInstancesResponse
  'LocalRuntime.getStatus': InstanceStatusResponse
  'LocalRuntime.healthCheck': HealthCheckResponse
  'LocalRuntime.restartModel': InstanceResponse
  'LocalRuntime.startModel': InstanceResponse
  'LocalRuntime.stopModel': InstanceResponse
  'Mcp.getDefaults': UserMcpDefaultsGetResponse
  'Mcp.respondToElicitation': RespondToElicitationResponse
  'Mcp.updateDefaults': UserMcpDefaultsResponse
  'McpServer.create': McpServer
  'McpServer.delete': void
  'McpServer.deleteOAuthConfig': void
  'McpServer.get': McpServer
  'McpServer.getOAuthConfig': McpServerOAuthConfigResponse | null
  'McpServer.listAccessible': McpServerListResponse
  'McpServer.setOAuthConfig': McpServerOAuthConfigResponse
  'McpServer.update': McpServer
  'McpServerRuntime.callTool': CallToolResponse
  'McpServerRuntime.disconnect': any
  'McpServerRuntime.getPrompt': GetPromptResponse
  'McpServerRuntime.listPrompts': ListPromptsResponse
  'McpServerRuntime.listResources': ListResourcesResponse
  'McpServerRuntime.listTools': ListToolsResponse
  'McpServerRuntime.ping': PingResponse
  'McpServerRuntime.readResource': ReadResourceResponse
  'McpServerSystem.assignServerToGroups': void
  'McpServerSystem.create': McpServer
  'McpServerSystem.delete': void
  'McpServerSystem.get': McpServer
  'McpServerSystem.getServerGroups': string[]
  'McpServerSystem.list': McpServerListResponse
  'McpServerSystem.removeServerFromGroup': void
  'McpServerSystem.update': McpServer
  'Message.delete': void
  'Message.edit': EditMessageResponse
  'Message.get': MessageWithContent
  'Message.getHistory': MessageWithContent[]
  'Message.sendStream': SSEChatStreamEvent
  'Onboarding.complete': User
  'Onboarding.completeStep': User
  'RuntimeVersion.checkUpdates': AvailableUpdatesResponse
  'RuntimeVersion.delete': void
  'RuntimeVersion.download': DownloadVersionResponse
  'RuntimeVersion.get': RuntimeVersionResponse
  'RuntimeVersion.list': RuntimeVersionListResponse
  'RuntimeVersion.setDefault': RuntimeVersionResponse
  'RuntimeVersion.syncCache': SyncCacheResponse
  'User.create': User
  'User.delete': void
  'User.get': User
  'User.list': UserListResponse
  'User.resetPassword': void
  'User.toggleActive': UserActiveStatusResponse
  'User.update': User
  'UserGroup.assignUser': void
  'UserGroup.create': Group
  'UserGroup.delete': void
  'UserGroup.get': Group
  'UserGroup.getMembers': UserListResponse
  'UserGroup.list': GroupListResponse
  'UserGroup.removeUser': void
  'UserGroup.update': Group
}

// Type helpers
export type ApiEndpoint = keyof typeof ApiEndpoints
export type ApiEndpointUrl = (typeof ApiEndpoints)[ApiEndpoint]

// Extract endpoint key from URL pattern
export function getEndpointKey(url: string): ApiEndpoint | undefined {
  const entries = Object.entries(ApiEndpoints) as [ApiEndpoint, string][]
  const found = entries.find(([_key, value]) => value === url)
  return found ? found[0] : undefined
}

// Get parameter type for endpoint
export type GetParameterType<K extends ApiEndpoint> = ApiEndpointParameters[K]

// Get response type for endpoint  
export type GetResponseType<K extends ApiEndpoint> = ApiEndpointResponses[K]

// Create reverse mapping from URL to endpoint key
export type UrlToEndpoint<U extends ApiEndpointUrl> = {
  [K in keyof typeof ApiEndpoints]: (typeof ApiEndpoints)[K] extends U
    ? K
    : never
}[keyof typeof ApiEndpoints]

// Helper types to get parameter and response types by URL
export type ParameterByUrl<U extends ApiEndpointUrl> =
  ApiEndpointParameters[UrlToEndpoint<U>]
export type ResponseByUrl<U extends ApiEndpointUrl> =
  ApiEndpointResponses[UrlToEndpoint<U>]

// Type-safe validation - this will cause a TypeScript error if any endpoint is missing
type ValidateParametersComplete = {
  [K in keyof typeof ApiEndpoints]: K extends keyof ApiEndpointParameters
    ? true
    : false
}

type ValidateResponsesComplete = {
  [K in keyof typeof ApiEndpoints]: K extends keyof ApiEndpointResponses
    ? true
    : false
}

// Type-safe validation - these will cause a TypeScript error if any endpoint is missing
// from Parameters or Responses. They are used for compile-time validation only.
export type { ValidateParametersComplete, ValidateResponsesComplete }
