// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  loadProviders: typeof import('./actions/loadProviders')['default']
  reset: typeof import('./actions/reset')['default']
  saveKey: typeof import('./actions/saveKey')['default']
  setApiKey: typeof import('./actions/setApiKey')['default']
}
