// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  doConnectors: typeof import('./actions/doConnectors')['default']
  doSettings: typeof import('./actions/doSettings')['default']
  load: typeof import('./actions/load')['default']
  updateConnector: typeof import('./actions/updateConnector')['default']
  updateSettings: typeof import('./actions/updateSettings')['default']
}
