// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  load: typeof import('./actions/load')['default']
  loadEmbeddingModels: typeof import('./actions/loadEmbeddingModels')['default']
  loadRerankerModels: typeof import('./actions/loadRerankerModels')['default']
  triggerBackfill: typeof import('./actions/triggerBackfill')['default']
  triggerReembed: typeof import('./actions/triggerReembed')['default']
  update: typeof import('./actions/update')['default']
}
