// AUTO-GENERATED by `npm run gen:store-actions` — do not edit.
// Typed name→factory map for the actions/ folder. Runtime registration is
// `import.meta.glob('./actions/*.ts')` in index.ts; these are the TYPES.

export type Actions = {
  clearMcpError: typeof import('./actions/clearMcpError')['default']
  createMcpServer: typeof import('./actions/createMcpServer')['default']
  deleteMcpServer: typeof import('./actions/deleteMcpServer')['default']
  deleteMcpServerOAuthConfig: typeof import('./actions/deleteMcpServerOAuthConfig')['default']
  getEnabledServers: typeof import('./actions/getEnabledServers')['default']
  getMcpServer: typeof import('./actions/getMcpServer')['default']
  getMcpServerOAuthConfig: typeof import('./actions/getMcpServerOAuthConfig')['default']
  getSandboxFlavors: typeof import('./actions/getSandboxFlavors')['default']
  getServersByType: typeof import('./actions/getServersByType')['default']
  getSystemServers: typeof import('./actions/getSystemServers')['default']
  getUserServers: typeof import('./actions/getUserServers')['default']
  loadMcpServers: typeof import('./actions/loadMcpServers')['default']
  searchServers: typeof import('./actions/searchServers')['default']
  setMcpServerOAuthConfig: typeof import('./actions/setMcpServerOAuthConfig')['default']
  setSearchTerm: typeof import('./actions/setSearchTerm')['default']
  setStatusFilter: typeof import('./actions/setStatusFilter')['default']
  testMcpServerConnection: typeof import('./actions/testMcpServerConnection')['default']
  updateMcpServer: typeof import('./actions/updateMcpServer')['default']
}
