-- Drop a redundant duplicate unique index on message_contents(message_id, sequence_order).
--
-- Two migrations independently added the SAME guard on the SAME columns:
--   * 114 (unique_message_contents_sequence) created the unique INDEX
--     `idx_message_contents_message_seq_unique`.
--   * 124 (message_contents_sequence_unique) added the named CONSTRAINT
--     `uq_message_contents_message_sequence` — whose backing index is an
--     independent second index over the identical columns. Its header re-argues
--     the case as if unmet ("There was no UNIQUE constraint to catch this"),
--     unaware 114 had already shipped one.
--
-- Postgres permits duplicate unique indexes, so both survive on every deployed
-- DB: every message_contents INSERT pays two index writes, and a violation
-- reports whichever name Postgres happens to check first — confusing to debug.
--
-- Keep 124's named CONSTRAINT and drop 114's bare index:
--   * a named constraint yields a clearer violation error than a bare index, and
--   * 124 is the later, authoritative statement of intent.
-- The protection is UNCHANGED — the surviving constraint enforces exactly the
-- same rule on exactly the same columns.
--
-- Safety: DROP INDEX cannot remove a constraint's backing index (Postgres
-- refuses with "cannot drop index ... because constraint ... requires it"), so
-- if these names were ever confused this migration fails loudly rather than
-- silently deleting the real guard. IF EXISTS keeps it idempotent for a DB that
-- somehow never ran 114.

DROP INDEX IF EXISTS idx_message_contents_message_seq_unique;
