-- Drop the orphan `llm_download_instances` table.
--
-- Migration 4 created `llm_download_instances`, but migration 5 immediately
-- superseded it with `download_instances`, which is the table every
-- repository / handler path actually reads and writes (see
-- llm_model/repository.rs + handlers/uploads.rs). `llm_download_instances`
-- has ZERO code references anywhere in the server and is therefore always
-- empty — no data move is required to retire it. Its indexes are dropped
-- implicitly with the table.
--
-- This consolidates the two download-instance tables down to the single
-- live `download_instances`, removing the schema duplication.
DROP TABLE IF EXISTS llm_download_instances CASCADE;
